### ISSUE TITLE
Nettoyage comptes collectivités en production

### ISSUE THREAD

**Issue by Nickvalley** [betagouv/territoires-en-transitions#1048]
- [ ] Nettoyer la liste des collectivités des comptes test avec l'arrivée du nouveau Back (ne garder qu'un compte test : "Territoire en Transition (compte test)" avec toute l'équipe en référents)
- [ ] Décider ce que l'on fait des comptes hors cible et des doublons 
   - [x] Du compte DREAL et des 2 comptes Région,
   - [ ] Des multiples comptes de la CA Épinal (2), de la CA Grand Avignon (2), CC Balcons du Dauphiné (3), CC Pays de l'Arbresle (2), CC PSMV (2), CC Pays Orne-Moselle (2), CC Piémont Cévenol (2), Epinal (3), Orléans Métropole (2), SYTRAD (2), VALDEM (2) 
   - [x] Suppression des comptes "CC Rochefoucauld Porte du Périgord" et « EPCI La Rochefoucauld porte du Périgord » pour ne conserver que « CC La Rochefoucauld porte du Périgord »

**Comment by Emelinejy** [comment]
CA Épinal : données renseignées par G. Rousselle dans CA Epinal mais compte rattaché à Adeline Evain pour CA Épinal (mais compte collectivité vide)

**Comment by Emelinejy** [comment]
CC Balcons du Dauphiné

**Comment by Emelinejy** [comment]
CC Pays Orne-Moselle : données renseignées par Ludovic Schneider mais compte rattaché à Juliette Leonard (sans donnée)

**Comment by Emelinejy** [comment]
Epinal : vérifier si aucune donnée renseignée sur les 3 comptes lors du retour de l'accès à la palteforme
