### ISSUE TITLE
Lier un indicateur des référentiels dans une fiche action déjà créée: broken ! (peut être que c'est un pb de mon ordi, mais le refresh et la nav privée n'y change rien)

### ISSUE THREAD

**Issue by MartinRUAU** [betagouv/territoires-en-transitions#110]
Exemple1: [Ville de test] action 11 et 12 du "1.1 sous axe numéro 2", je ne peux pas lier d'indicateur des référentiels ni des perso

Exemple 2: si je créé une nouvelle fiche action, tout fonctionne parfaitement. Si je sélectionne une autre action que la 11 et 12, cela fonctionne parfaitement.

**Comment by Nickvalley** [comment]
Bug corrigé
