### ISSUE TITLE
T/T - Ajouter les collectivités manquantes

### ISSUE THREAD

**Issue by bertrandlalo** [betagouv/territoires-en-transitions#1121]
- [x] Ajouter les EPCI manquants (depuis base banatic)
- [x] Ajouter les villes (communes de plus de 3000 habitants) (depuis base INSEE)
  - [x] support pour le type commune #1329

**Comment by Nickvalley** [comment]
Question @bertrandlalo  + ping @Emelinejy : 
Est-ce qu'il y a bien l'ajout des villes  de prévu pour la liste des collectivités manquantes dans cette tâche du sprint en cours ? (au delà des EPCI manquants) 
Je repose la question car il n'y a pas de description dans la carte et que ça va être bloquant par la bascule car nous avons déjà une trentaine de villes actives sur la plateforme.
