### ISSUE TITLE
Nettoyer la carte #248

### ISSUE THREAD

**Issue by Nickvalley** [betagouv/territoires-en-transitions#1136]
#248 

-  Vérifier que les items qui sont toujours pertinents sont bien dans figma
- Faire une liste des trucs qui manquent 
- cocher ce qui est ok
- Pinger dev sur ce qui manque

**Comment by Emelinejy** [comment]
Ce qui n'a pas été repris : 
**Pages référentiel**
- [ ] Mettre un séparateur entre les sous-axes (cf maquette)
- [ ] Remonter les descriptions des actions en infobulle (modale?) à côté du titre pour mieux distinguer les contenus/informations fournis par les référentiels des champs sur lesquels il est attendu une saisie de contenu par l'utilisateur
- [ ] Réduire la taille de police afin de rendre plus compact réduire le besoin de scroller MAIS à voir à l'usage si le nouvel affichage permet de résoudre ce problème

**Pages mesures/orientations**
- [ ] Reprendre les choses de façon homogène avec la page référentiels
Descriptions en infobulle + Compacité/lisibilité + taille de police
- [ ] Affichage plus condensé dont une version repliée (cf. maquette) (⚠️ à rediscuter car cela doit rester incitatif pour saisir des commentaires qualitatifs lorsque l'on a mis à jour un statut

**Partout**
- [ ] Les flèches pour déplier ou aller vers quelque chose ne sont pas visibles/pratiques (sur indicateurs, sur les référentiels, sur le tableau de bord pour aller vers le plan d'actions). Améliorer l'ergonomie
- [ ] Proposer une alternative aux cadres "gris" et carrés. (La transition écologique c'est pas triste et avec des angles qui font mal)

**Page indicateur**
- [ ] Renommer le titre du champ "Commentaire" afin d'encourager les personnes à apporter des précisions qualitatives.
- Proposition A modification du titre "Remplacer "Commentaires" par "Précisions sur l'indicateur (évolutions, sources, etc.)"
- Proposition B mettre un texte explicatif directement dans le champ commentaire (Ca s'appelle comment d'ailleurs "Hint?" Ca m'aiderait de connaitre le terme technique?). "Renseignez ici les informations que vous souhaitez préciser vis-à-vis de l'indicateur. Analyse de la tendance d'évolution, éléments de contexte sur l'évolution des valeurs, sources, etc."
- Faire A+B 🤔 ?
