### ISSUE TITLE
US Je veux pouvoir datavisualiser les données renseignées pour mes indicateurs avec des graphiques

### ISSUE THREAD

**Issue by Nickvalley** [betagouv/territoires-en-transitions#114]
Visualiser dans un graphique : 
- [x] les valeurs saisies par année
- [x] la tendance des valeurs saisies dans le futur, 
- [x] la comparaison par rapport aux valeurs d'objectifs fixés (une ou plusieurs valeurs)
- [x] Contrôler les champs d'indicateur pour qu'ils soient au format nombre et éviter les erreurs de saisie.  
![image](https://user-images.githubusercontent.com/67585509/131619952-0c187bc1-d1ec-4a5a-9781-062f0c5c53cd.png)
- [x] gérer les "." ou "," comme séparateur de décimale pour faciliter la saisie et les copier-coller (?)

**Comment by maiwann** [comment]
>  la tendance des valeurs saisies dans le futur,

J'ai l'impression que renseigner des valeurs dans le futur n'est pas une feature qui est utile lorsque j'en discute avec les personnes. On pourrait proposer de n'avoir que les années jusqu'à celle en cours ?

>  En présence d'une seule valeur, l'objectif est représenté par une ligne horizontale permettant de visualiser les résultats par rapport à l'objectif

Je suis embêtée par cette solution car si on met aussi des lignes pour les valeurs seuils et cible, on va utiliser le même rendu graphique pour des données très différentes, et qui ne viennent pas du même endroit. Quel est le problème si on reste dans la représentation actuelle, c'est à dire que l'objectif est représenté par un cercle, comme ici ?

![image](https://user-images.githubusercontent.com/27999224/126174421-d27fc99f-875e-46e3-9b45-ec5e26e2b63f.png)

**Comment by penelopel** [comment]
> > la tendance des valeurs saisies dans le futur,
> 
> J'ai l'impression que renseigner des valeurs dans le futur n'est pas une feature qui est utile lorsque j'en discute avec les personnes. On pourrait proposer de n'avoir que les années jusqu'à celle en cours ?

Il me semble que la "tendance des valeurs saisies dans le futur", cela veut dire donner à l'utilisateur la projection de ce que ça va donner dans les prochaines années si on extrapole en gardant la même tendance que les données historiques (et pas lui donner la possibilité de renseigner des valeurs dans le futur). Du coup, il faut forcément mettre les années suivantes non ? Pour qu'ils voient quand ils atteignent les objectifs.

**Comment by maiwann** [comment]
TO DO : Rajouter des unités et un titre au graphique

**Comment by maiwann** [comment]
![Capture d’écran 2021-08-03 à 16 24 17](https://user-images.githubusercontent.com/27999224/128032604-0279bd53-b875-4439-9279-0a0c800109c2.png)

- La ligne bleue représente les résultats
- La ligne grise pointillés représente les objectifs 
- Les lignes horizontales en pointillés orange et bleues seront les limites seuils et cibles

**Comment by derfurth** [comment]
possibilité de s'inspirer des graphs de https://lte.fairness.dev/ repo https://github.com/NicolasDievart/lte-metrics

**Comment by Nickvalley** [comment]
Ne pas mettre le numéro de l'action dans la nomenclature  du référentiel sur le titre du graphique  (ex. ici "1a")  car ça n'a pas de valeur ajoutée et si ils utilisent cet indicateur dans leur plan d'action peut-être qu'il a un autre numéro chez eux en interne ou tout simplement pas de numérotation

**Comment by bertrandlalo** [comment]
> En présence d'une seule valeur, l'objectif est représenté par une ligne horizontale permettant de visualiser les résultats par rapport à l'objectif 
C'est à dire ?

**Comment by Nickvalley** [comment]
L'idée initiale c'était que un objectif unique s'affiche comme une ligne horizontale (comme les valeurs seuils ou cible) sur la maquette mais Maïtané était plutôt contre pour éviter la confusion. Tu en penses quoi en termes de lisibilité de la datavisualisation des obectifs de ton côté?
