### ISSUE TITLE
Regarder le besoin métier / support pour la mise en place de Crisp

### ISSUE THREAD

**Issue by Nickvalley** [betagouv/territoires-en-transitions#1141]
- [x] Regarder les [fonctionnalités](https://crisp.chat/fr/pricing/) à mettre en place au prochain sprint : 
   - [x] Livechat
   - [x] Courriel intégré et campagnes de mailing (Pro)
   - [x] Base de connaissances (FAQ) - (Unlimited)

Pour plus tard : 
-  Formulaire de contact Crisp sur une page contact du site statique
-  Campagnes automatiques (exemple : accueil des nouveaux utilisateurs)
-  Messages automatiques d'assistance liés à la base de connaissance
-  Visio live à partir du chat

**Comment by penelopel** [comment]
![image](https://user-images.githubusercontent.com/5320547/149927616-929a7984-f1e6-4f71-98b4-2c4931269070.png)
