### ISSUE TITLE
Misc UI  Emeline x Pénélope

### ISSUE THREAD

**Issue by bertrandlalo** [betagouv/territoires-en-transitions#1170]
**Auth** 
- [x] Message explicite si on coche pas les politiques ADEME
- [x] UX ambigu du "Créer un compte"

**Sélectionner collectivité**
- [x] Afficher le message suivant si la collectivité n'apparaît pas : Vous ne trouvez pas la collectivité que vous recherchez ? Merci d'envoyer un mail à contact@territoiresentransitions avec le nom et numéro SIREN de cette collectivité pour que nous puissions vous aider
- [x] Inverser la ligne "Mes collectivités" et la ligne pour rejoindre une collectivité

**Plan d'actions**
- [x] Dans le formulaire d'une fiche action, si pas d'axe créer, un petit carré moche dans le dropdown. 
- [x] Le plan d'action en cours n'apparaît pas actif dans les puces  

**Référentiel**
- [x] N'afficher que les % qui ne sont pas 0. dans le tooltip; mettre des majuscules et des espaces avant les ":" 
- [x] Remettre le toggle "afficher uniquement les actions non renseignées" 

**Indicateurs**
- [x] Les indicateurs ne sont pas ordonnées par leur identifiants
- [x] Toggle : supprimer le petit true/false

- [x] **Typo**
  - [x] génerale => Générale
  - [x] d'actions => d'action 
  - [x] sous axe => Sous-axe 
  - [x] lecture seule => Lecture seule 
  - [x] Selectionner => Sélectionner 
  - [x] Dans le footer : écrivez-nous à : (espace !)

**Comment by derfurth** [comment]
Modification du lien entre "se connecter" vers "créer un compte" plus standard (ex gmail) 
![image](https://user-images.githubusercontent.com/1872471/149355056-8af2bb57-355a-4724-81ca-efaa211d35c1.png)

**Comment by derfurth** [comment]
terminé dans pr #1193
