### ISSUE TITLE
[Markdown Référentiel]  Reprendre la dernière version et s'assurer que :

### ISSUE THREAD

**Issue by bertrandlalo** [betagouv/territoires-en-transitions#1175]
- [x] id -> identifiant `id: ([\d+.]+)$` `identifiant: $1`
- [x] point -> pourcentage pour les sous actions jusqu'au taches cae: `identifiant: ([\d+.]{5}.+)$` eci: `identifiant: ([\d+.]{4}.+)$`
- [x] les points des actions réglementaires eci à 0 `identifiant: ([\d+.]+\.0)$`
- [x] y a bien la 2.4.0 
- [x] s'assurer du contenu #787

**Comment by Emelinejy** [comment]
Les sous-actions réglementaires pour le référentiel ECi sont celles X.X.**0** dans les actions suivantes : 
- 2.1 - Disposer d'un programme de prévention des déchets ménagers et assimilés
- 2.2 - Améliorer l'efficience du système de collecte 
- 2.3 - Améliorer la valorisation des déchets (dont organiques) 
- 2.4 – Réduire les impacts environnementaux et sociaux de la gestion des déchets
- 3.2 - Réaliser des achats responsables 
- 4.1 - Connaître les coûts de la gestion des déchets pour maîtriser les dépenses publiques
