### ISSUE TITLE
Améliorer la page statistiques publiques

### ISSUE THREAD

**Issue by derfurth** [betagouv/territoires-en-transitions#1180]
Compléter la page statistiques publiques avec des histogrammes complémentaires sur l'utilisation:
- [ ] Nombre total d'actions des référentiels renseignées (distinct 1 graphe par référentiel CAE et ECi)
- [ ] Nombre total d'indicateurs renseignés (distinct 1 graphe par référentiel CAE et ECi)
- [ ] Convertir les graphes de remplissage référentiels ECI/CAE par un graphique en aires empilées niveau de remplissage pour voir l'évolution dans le temps 
Exemple : Aire 2D dans Excel ![image](https://user-images.githubusercontent.com/67585509/158167299-83461ed8-8e8a-4a9b-86aa-ccd7aafa517b.png)

**Comment by Emelinejy** [comment]
Reprise dans carte #2346
