### ISSUE TITLE
Filtrer les actions de mon plan d'actions pour suivre mon plan d'action

### ISSUE THREAD

**Issue by pntbr** [betagouv/territoires-en-transitions#12]
- doit permettre de filtrer par statut "en cours" par exemple
- doit permettre de filtrer par "Direction pilote"
- doit permettre de filtrer par "personne référente"

**Comment by maiwann** [comment]
![image](https://user-images.githubusercontent.com/27999224/118658036-4dc73d80-b7ec-11eb-912d-326d7c202140.png)

La maquette, 3 listes déroulantes avec l'intitulé du champ qui correspond. Est-ce que c'est plus simple pour vous si je rajoute un bouton "Filtrer" ? Je voudrais éviter mais c'est peut-être mieux coté dev et/ou éco-conception ?

**Comment by maiwann** [comment]
@derfurth Il faudrait changer le "StatuS" en "StatuT"… je fais une autre issue pour ça ?
