### ISSUE TITLE
T - mettre à jour le footer

### ISSUE THREAD

**Issue by derfurth** [betagouv/territoires-en-transitions#1287]
- [x] Seul l'ensemble du footer est cliquable - Il faudrait séparer les éléments (logo et nom à gauche + texte à droite en haut (avec lien vers mail aide@…) + 3 url séparées renvoyant vers chacune l’URL concernée)
- [x] Changer le lien citergie pour territoire engagés comme sur la prod actuelle
- [x] Garder seulement la version du footer quand on est pas connecté

**Comment by marc-rutkowski** [comment]
pour le dernier point, je ne vois pas de différence entre les 2 dans le code ni en exécution locale
à re-tester donc...
