### ISSUE TITLE
US - Préciser les objectifs de mes indicateurs

### ISSUE THREAD

**Issue by Nickvalley** [betagouv/territoires-en-transitions#136]
- [x] Pouvoir saisir des valeurs d'objectifs de façon similaire aux valeurs d'indicateurs de résultats
- [x] Les valeurs des objectifs peuvent être saisis dans le passé (2008 à 2020) ET dans le futur (2021 à 2030 + 2040 + 2050 (pas les années 2031-2039, et 2041 à 2049)

**Comment by maiwann** [comment]
![image](https://user-images.githubusercontent.com/27999224/123093866-7c0fec80-d42c-11eb-8cd9-b28db26e3d0c.png)

**Comment by maiwann** [comment]
Le résultat de mes enquêtes me donnait l'impression que les utilisateurs n'avaient qu'un objectif à la fois, et qu'ils n'avaient pas d'intérêt à s'en souvenir une fois que l'année concernée par l'objectif était passée (je suis moins sure pour cette seconde partie)

Pour concevoir ça, je voudrais savoir dans quels cas les personnes :
- ont plusieurs objectifs pour 1 indicateur
- savoir à quoi cela leur sert de se souvenir des indicateurs du passé/ si ils ont la même importance que ceux du futur
- si ils ont plusieurs indicateurs pour le futur

@MartinRUAU @Nickvalley vous avez des billes là dessus ? :x

**Comment by maiwann** [comment]
Ok après discussion de vive voix avec Martin sur les questions au-dessus, nouvelle maquette : 
![image](https://user-images.githubusercontent.com/27999224/126613216-51653fc0-c333-41ac-bec7-1341b59364ca.png)

**Comment by maiwann** [comment]
@bertrandlalo On est en train de discuter de l'issue avec Nicolas, et j'ai oublié de rajouter un titre "Résultats" au dessus de la première ligne de champs de données. Est-ce que ca serait possible de le rajouter avant que tu finisses l'issue ? 😬

**Comment by Nickvalley** [comment]
@bertrandlalo En mettant à jour les milestones sur les US du sprint en cours, je viens de réaliser qu'on avait pas supprimé ce point : "(pas les années 2031-2039, et 2041 à 2049)" dans la description qui date de la mise à jour de la description début août mais que nous n'avons pas rediscuté en sprint planning. 
Du coup je sais pas si c'était clair pour toi qu'on pensait qu'on peut commencer à implémenter les objectifs avec les mêmes champs d'années que pour le réalisé et on verra plus tard pour personnaliser les champs au regard du retour des utilisateurs sur le sujet des objectifs.
