### ISSUE TITLE
TT - Pouvoir dire qu'une fiche-action est "en retard"

### ISSUE THREAD

**Issue by Nickvalley** [betagouv/territoires-en-transitions#138]
- [x] Ajout du flag `en_retard` dans le modèle
- [x] Ajout d'un booleen dans la bdd
- [x] Case à cocher "Action en retard" dans la fiche action en dessous des boutons de statut pour indiquer que l'action est en retard
- [x] Lorsque la case est cochée, l'action s'affiche dans la page de synthèse avec le cartouche "En retard" avec petit bandeau de couleur rouge (cf. [maquette de Maïtané](https://github.com/betagouv/territoires-en-transitions/issues/138#issuecomment-868329057) dans la carte)

**Comment by maiwann** [comment]
![image](https://user-images.githubusercontent.com/27999224/123396856-15acda80-d5a2-11eb-8b61-314a3f2c5e69.png)

Et quand une action est "en retard" il y a une petite étiquette dessus

**Comment by Nickvalley** [comment]
OK pour l'affichage. (Un petit picto. d'horloge rouge à gauche ça serait chouette pour l'avenir)

Je m'interroge sur deux choses qui n'ont pas été explicitées dans la carte : 
- Est-ce que "En retard" s'affiche bien automatiquement lorsque la date de fin dans le calendrier est dépassée ?
- Comment est-ce que cet affichage du "En retard" cohabite avec l'US #137 (Pouvoir visualiser le statut d'avancement des actions dans la vue de synthèse du plan d'actions )  à venir qui consiste à afficher de façon visible le statut donné manuellement à l'action dans la vue de synthèse ? Car on pourra avoir des actions "En cours" et "En retard", "Prévues" et "En retard", etc.

**Comment by maiwann** [comment]
> Est-ce que "En retard" s'affiche bien automatiquement lorsque la date de fin dans le calendrier est dépassée ?

Non, pas tant que, a minima, les champs calendrier ne sont pas juste sur du mois/année. Parce que pour l'instant, on sait que les utilisateurs n'ont pas envie de remplir ces champs qui sont trop précis


> Comment est-ce que cet affichage du "En retard" cohabite avec l'US "Pouvoir visualiser le statut d'avancement des actions dans la vue de synthèse du plan d'actions  #137" à venir qui consiste à afficher de façon visible le statut donné manuellement à l'action dans la vue de synthèse ? Car on pourra avoir des actions "En cours" et "En retard", "Prévues" et "En retard", etc.

Pour moi cette US #137 doit être creusée pour que je sache dans le détails ce qui est souhaité dans la partie "synthèse" du plan d'actions, et ensuite je verrai si ça doit cohabiter, se superposer, ou autre :) donc il me faut plus de détails sur les infos nécessaire sur la partie "synthèse"
