### ISSUE TITLE
T - aligner le texte carte collectivité

### ISSUE THREAD

**Issue by derfurth** [betagouv/territoires-en-transitions#1384]
- [x] demander à @cami-na si on centre la flèche avec le texte 
- [x] centrer voir [sshot](https://i.imgur.com/inVwT7x.png)

**Comment by cami-na** [comment]
Les textes sont bien à aligner à gauche ! (c'est une norme pour faciliter la lecture, nos yeux ont besoin de repères et l'alignement est en un :)) merci
