### ISSUE TITLE
Proposer un message pour les gens arrivant via le lien d'invitation

### ISSUE THREAD

**Issue by penelopel** [betagouv/territoires-en-transitions#1389]

**Comment by cami-na** [comment]
### Page pour les personnes arrivant via le lien d’invitation 

En tant que personne invitée sur l’app, je souhaite qu’après avoir cliqué sur le lien d’invitation, une page d’accueil spécifique s’affiche afin que je comprenne bien les prochaines étapes.

**Infos métier**

- Qui reçoit un lien d’invitation ?
- Quelles actions possibles suite à l’invitation ? Différentes selon les rôles ?

**Critères d’acceptation**

Contenu de la page 
Hiérarchie
