### ISSUE TITLE
US Je peux saisir un "Commentaire" pour préciser des informations sur la mesure/action/tâche du référentiel

### ISSUE THREAD

**Issue by MartinRUAU** [betagouv/territoires-en-transitions#139]
Pourquoi à ces 3 niveaux ? 

* Eviter d'avoir à remettre le même "Commentaire" de l'action dans toutes les tâches qu'on voudrait mettre sur l'action, la mesure
* Permettre d'avoir la reprise dans ce champ "Commentaire" les textes présents jusqu'à présent sur "Preuve" et "Mémo" au niveau de l'orientation au moment de la reprise des données
* Permettre d'avoir au niveau de la mesure le contenu des champs repris de l'EMT Cit'ergie au moment de la bascule

**Comment by maiwann** [comment]
Dans mes maquettes je l'ai nommé "Commentaire" pour que se soit plus évident que c'est un champ éditable et pas un champ texte descriptif
