### ISSUE TITLE
Repérer toutes les améliorations à bas-coût à faire sur la nouvelle interface

### ISSUE THREAD

**Issue by penelopel** [betagouv/territoires-en-transitions#1390]
Lien vers analyse Ux : https://territoires-en-transitions.notion.site/Audit-UX-de-l-application-bb84bd60eca3442a83ae73b874b88bda

- [x] @derfurth Définir la complexité
- [ ] @Nickvalley + @Emelinejy  Définir la priorisation au regard de l'impact métier / roadmap en vue du prochain comité d'investissement

**Comment by cami-na** [comment]
[Audit UX de l'application](https://territoires-en-transitions.notion.site/Audit-UX-de-l-application-bb84bd60eca3442a83ae73b874b88bda) déjà revu avec Émeline et Marc
