### ISSUE TITLE
Je peux consulter les référentiels sans avoir à créer de compte

### ISSUE THREAD

**Issue by pntbr** [betagouv/territoires-en-transitions#14]
- [ ] Accéder facilement à la version courante des référentiels depuis la Homepage en mode public (sans connexion)
- [ ] Pouvoir télécharger la version courante au format PDF avec plus ou moins de détail
- [ ] Actions avec leur description seules (pas le détail des sous-actions et des tâches)
- [ ]  Actions avec leur description + Tout le détail des sous-actions et tâches

**Comment by Nickvalley** [comment]
Fichier PDF diffusé actuellement dans le réseau CAE pouvant servir de référence pour l'affichage et l'export (PDF)
[referentiel_2021_fiches_individuelles.pdf](https://github.com/betagouv/territoires-en-transitions/files/7223876/referentiel_2021_fiches_individuelles.pdf)
