### ISSUE TITLE
US - Gérer l'ajout de fichiers preuves

### ISSUE THREAD

**Issue by MartinRUAU** [betagouv/territoires-en-transitions#140]
- [x] Pouvoir ajouter des fichiers preuves sur les actions des référentiels 

- [ ] La fonctionnalité permet à l'utilisateur de privilégier l'usage de liens vers des ressources en ligne existantes plutôt que le dépôt de fichiers si les documents sont déjà disponibles en ligne.

- [ ] Cf. maquettes pour le flow : https://www.figma.com/file/huNGZwSwBUa5dJAzXkh2Mh/TeT?node-id=730%3A19106 
   - [ ] Passer direct à l'étape ajouter un fichier pour l'ajout de preuve 1. 
   - [ ] Changer le titre en "Rechercher parmi mes fichiers"
   - [ ] Ajuster le contenu à gauche dans la modale

----
- [ ] Prévenir les utilisateurs lorsque la fonctionnalité est en ligne - nombreuses demandes

**Comment by Nickvalley** [comment]
Screenshots EMT sur l'ergonomie actuelle dans l'outil: 
- Affichage de synthèse dans l'EMT de tous les fichiers de la collectivité: 
![image](https://user-images.githubusercontent.com/67585509/132877378-21b113a0-3970-4331-af62-901d0d440da3.png)

- Affichage dans la vue de synthèse de l'ensemble du référentiel: 
![image](https://user-images.githubusercontent.com/67585509/132878282-53e8b797-3bed-4e40-95fa-61272fc66804.png)

- Affichage dans une mesure spécifique (en lecture seule) : 
![image](https://user-images.githubusercontent.com/67585509/132877766-f58d7140-ba67-4ebb-98fd-5420becefff9.png)

- Affichage dans une mesure spécifique avec les droits en modification (boutons d'ajout de fichiers)
![image](https://user-images.githubusercontent.com/67585509/132878550-99cf8b05-fde3-48cf-8d8c-273272523cde.png)

**Comment by Nickvalley** [comment]
>     * Est-ce que les données des documents-preuves sont sensibles ?

Y'a sûrement des données personnelles dans certains fichiers oui, mais je pense que si on vérifie les usagers de la communauté on doit pouvoir gérer une ouverture de ces fichiers à minima dans la communauté utilisatrice

>     * Combien de documents preuves par collectivité ? 

- Environ 70-80 par cycle sur l'ensemble du réferentiel Cit'ergie sachant qu'on aura 2 référentiels pour certaines collectivités et pas de REX numérique sur les preuves ECi pour l'instant (je pense que c'est moins)
S'ajoute à cela les documents spécifiques demandés pour la labellisation (exemple CU Dunkerque): 
- 12 documents pour le dossier de demande
- 5 documents annexes à la demande
- Et la collectivités peut uploader des fichiers généraux liés à sa démarche dans son compte en dehors des référentiels en créant des dossiers. Exemple CU Dunkerque engagée depuis 2008, fichier actuels (mis à jour en mars 2021 pour la dernière labellisation) : 
   - 10 fichiers généraux
   - 4 délibérations
   - 19 documents de diagnostic climat-air-énergie
   - 10 documents projets exemplaires
   - 1 document organigramme
   - 10 rapports de visite annuelle du conseiller (1 par année)

>     * Importance de figer dans le temps les preuves ? Ou ok si elles sont remplacées ?
- Important de garder les preuves relatives au dernier audit.

>     * A partir de combien d'années sont elles archivables ?
Je pense qu'on peut envisager d'archiver les fichiers dès lors que l'on a l'historique sur les 2 derniers cycles labellisés (=4-6 ans max car labellisation tous les 4 ans et parfois ça traine 1-2 ans).

**Comment by Emelinejy** [comment]
Dans un premier temps, les fichiers preuves doivent être accessibles par : 
- chaque utilisateur lié au compte de la collectivité 
- le conseiller CAE (et/ou l'AMO ECi) qui accompagne la collectivité
- l'auditeur qui audite la collectivité
- les membres de la CNL
- les Bureau d'Appui
- l'ADEME siège et les Directions régionales de l'ADEME (à revalider avec Nicolas, Jerry et Guillaume - peut-être dans une second temps ?)

Dans l'idéal, il faudrait que tous les fichiers soient accessibles de tous.
Si une collectivité souhaite éviter la diffusion d'un document "sensible", un statut "privé" ou "consultable à la demande uniquement" pourrait être accordé. Les utilisateurs des autres collectivités auraient alors une demande de lecture à faire à la collectivité, qui devrait l'accepter pour donner accès au document uniquement aux personnes en ayant fait la demande (pas de téléchargement possible, juste la consultation - si possible).

**Comment by cami-na** [comment]
### Preuves (collectivités)

En tant que personne référente d’une collectivité, je veux ajouter des preuves afin de compléter mon dossier en vue de l’audit et de la labellisation de ma collectivité pour les référentiels Économie circulaire et Climat Air Énergie

**Infos métier**

- Preuves nécessaires pour l’audit relatif aux deux référentiels : Économie circulaire et Climat Air Énergie
Au total environ 70-80 preuves pour Cit'Ergie

- Référentiel Économie circulaire : 
    - En moyenne 3 (maximum 5) preuves par niveau 1.2.3
    - Liste précise de preuves requises : titres + pour la moitié des preuves, 1 paragraphe de détails  
    
- Référentiel Climat Air Énergie : 
    - En moyenne 3 (maximum 5) preuves par niveau 1.2.3
    - Liste indicative de preuves suggérées (l’audit sera plus axé sur les commentaires des actions)
    - Cf EMT pour un aperçu de comment cela est fait actuellement 
    
- Caractéristiques des preuves :
    - Types de preuves :
        - Fichier (90% de PDF + Word, Excel, PPT, Jpeg)
        - Commentaire (type de preuve le plus utilisé sur le référentiel CAE)
        - Lien URL
    - Publiques sauf rares exceptions : décision de ne pas traiter ce cas exceptionnel pour l’instant
    - 1 même fichier peut être associé à plusieurs actions (dans ce cas, il ne doit pas être téléversé à nouveau)
    - Les fichiers peuvent être très lourds (nombreuses pages) : donner la possibilité pour la collectivité d’indiquer quelles pages sont concernées pour la preuve 
    - En plus des preuves requises ou indicatives, donner la possibilité d’ajouter des preuves « bonus »
    - Date d’ajout et utilisateur : à afficher dans l’historique 

- Audit : parcours miroir « En tant qu’auditeur ou auditrice, je veux consulter les preuves d’une collectivité afin d’évaluer son niveau de labellisation » à définir plus précisément pour vérifier que les deux côtés correspondent bien 
    - Pour l’instant : idée d’une liste avec possibilité de recherche par mots-clés et d’aperçu des preuves de chaque collectivité pour chaque référentiel, avec des coches pour indiquer la validation des preuves - Question sur l’export des preuves (pratique actuelle) : faire en sorte qu’il n’y ait pas besoin de sortir de l’app
    - Afficher la date d’ajout des preuves pour que l’auditeur puisse voir si c’est trop ancien

**Critères d’acceptation**

- Mention indiquant que les preuves sont publiques (phrase d’intro à formuler)
- Pour chaque niveau 1.2.3 des référentiels Économie circulaire et Climat Air Énergie : liste des preuves avec infobulle indiquant plus de détails si nécessaire (rééquilibrage à envisager pour des titres de preuves plus courts ?)
- Bouton « Ajouter » permettant de
    - téléverser un ou plusieurs fichier(s)
    - rédiger un commentaire
    - copier-coller un lien URL
    - Sélectionner un fichier déjà téléversé dans la bibliothèque : sélection possible dans une liste (recherche par mots-clés pour retrouver un fichier par son titre)
- Fichier téléversé ou lien ajouté : titre + option aperçu en cliquant sur le titre et options renommer et supprimer 
- Suivi de l’historique des actions sur les preuves

Hypothèse que les collectivités ajoutent les preuves au fur et à mesure, dans chaque action
Autre option : créer une bibliothèque de preuves à associer aux actions au statut programmé ou réalisé

[Proposition de maquette](https://www.figma.com/file/YhEoPD2YxqHuEaPn8nKWql/Maquettes-2k22?node-id=82%3A22024)

**Comment by cami-na** [comment]
### Mise à jour : clarification commentaires

**1. Légende d'un fichier ou d'un lien preuve**
Ce sont des précisions sur, par exemple : les pages à consulter, à qui s'adresse le document, à qui il a été transmis, s'il a été approuvé ou est une version provisoire

**2. Commentaires associés à des preuves** 
Ces précisions sont renseignées dans le champ "Précisions sur l'état d'avancement"

- Référentiel CAE :
Dans les champs "précisions de l'état d'avancement", les conseillers indiquent "Cf preuve..." quand ils veulent faire référence à un document déposé en tant que preuve.
Les auditeurs, comme les conseillers, savent que ce qui est écrit est à la fois le contexte mais aussi la preuve de l'action de la collectivité. 
Les preuves "physiques" sont forcément des documents. Les commentaires sont des preuves mais plus de l'ordre du ressenti, de ce qui est "connu" au niveau de la collectivité / du territoire sans que ce soit attesté par un document ou autres.

- Référentiel ECi : 
Les preuves attendues sont des documents car l'écrit a moins de valeur. 

**Mise à jour des maquettes**
- Suppression du commentaire parmi les types de preuves
- Remplacement de l'option "Renommer" un fichier ou un lien par une option "Légende"

[Nouvelle version des maquettes](https://www.figma.com/file/YhEoPD2YxqHuEaPn8nKWql/Maquettes-2k22?node-id=136%3A14599)
