### ISSUE TITLE
US - Afficher le niveau de labellisation auquel peut prétendre la collectivité

### ISSUE THREAD

**Issue by penelopel** [betagouv/territoires-en-transitions#1495]
US en doublon avec la #889 à clôturer. 

[Description](https://www.notion.so/territoires-en-transitions/EPIC-Je-peux-pr-parer-et-faire-ma-demande-de-labellisation-audit-889-372a03d9642549c487e1cd8b9bc1c916)

**Comment by cami-na** [comment]
### Visualiser la progression dans le parcours de labellisation

En tant que personne référente d’une collectivité, je veux visualiser la progression de ma collectivité dans le parcours de labellisation afin de me projeter dans les prochaines étapes à effectuer 

**Infos métier** 

Pour les référentiels CAE et ECi

Conditions pour candidater aux différents niveaux de labellisation 
- Première étoile : cf [checklist](https://www.figma.com/file/88b79ioNG1wTm8z6CKM59I/Archives?node-id=377%3A31318) 
- Deuxième étoile : 35% du score réalisé par rapport au potentiel de ma collectivité (176 points sur 500 par exemple)
- Troisième étoile : 50%
- Quatrième étoile : 65%
- Cinquième étoile : 75%

Types de scores
- **Score réalisé** : % calculé à partir du nombre de points additionnés des actions au statut "Fait" par rapport à mon potentiel
- **Score programmé** : % calculé à partir du nombre de points additionnés des actions au statut "Programmé" par rapport à mon potentiel
- **Score labellisé** : à partir de la 2e étoile : score réalisé validé par la Commission Nationale du Label 

**Critères d’acceptation**

Afficher sur le tableau de bord, pour chacun des référentiels (similaire pour ECI et CAE ?) :

Titre 1 : **Niveau de labellisation actuel** (ou **Non labellisé** si encore aucune étoile)

**Images : 5 étoiles** 
- Les étoiles sont grises par défaut
- Une fois la labellisation validée officiellement par la Commission nationale du label, l'étoile correspondante passe en bleu
- Au survol de l'étoile avec la souris, une infobulle apparaît 

**Contenu de l'infobulle au survol :** 
- Si étoile grisée : "Plus que [score requis- score courant actuel]% à réaliser pour candidater, d'après votre score actuel !" 
- Cas particulier aucune étoile : pas de comportement au survol de la souris, sur aucune étoile
- Cas particulier deuxième étoile si le score courant est supérieur à 35% : "Vous atteignez le score requis, félicitations ! Candidatez dès à présent  ou continuez à progresser jusqu’à la fin de votre cycle de labellisation."
- Si étoile bleue : "Score labellisé en [année] : [score labellisé]% // Ambition à quatre ans : [score programmé au moment de l'attribution du label]%"

Petite modif UI : inverser fond blanc de la page et fond gris des blocs avec les infos concernant les référentiels pour une meilleure lisibilité des éléments des blocs

[Proposition de maquette ](https://www.figma.com/file/YhEoPD2YxqHuEaPn8nKWql/Maquettes-2k22?node-id=187%3A14865)

**Comment by Nickvalley** [comment]
Doublon #889  
Description des choses restant à faire ici pour la 889 : [Description](https://www.notion.so/territoires-en-transitions/EPIC-Je-peux-pr-parer-et-faire-ma-demande-de-labellisation-audit-889-372a03d9642549c487e1cd8b9bc1c916)
