### ISSUE TITLE
Reprise du Design system de l'Etat

### ISSUE THREAD

**Issue by vinyll** [betagouv/territoires-en-transitions#1525]
Afin de s'assurer d'une bonne cohérence des services et une utilisation adéquate de l'esprit initial, l'utillsation du DSFR préconise et restreint le cadre d'utilisation des règles des composants, couleurs, espacement, alignements…
Exemple avec le menu de navigation d'en-tête : https://gouvfr.atlassian.net/wiki/spaces/DB/pages/222789853/Navigation+principale+-+Main+navigation#R%C3%A8gles-d%E2%80%99utilisation

## exemple avec le Header

Visuel standard

<img width="1567" alt="Screen Shot 2022-03-01 at 23 23 44" src="https://user-images.githubusercontent.com/145172/156259285-96b3ab31-3619-4961-8084-134c3138dc20.png">

Visuel TeT

<img width="1580" alt="Screen Shot 2022-03-01 at 23 22 39" src="https://user-images.githubusercontent.com/145172/156259304-eef73602-9455-42ea-b2aa-bcf5cf5aed42.png">

---

A noter qu'il existe une implémentation du DSFR en React, pour vous faciliter le bon respect du Design system et vous accélerer le développement : https://github.com/dataesr/react-dsfr ([contexte](https://gouvfr.atlassian.net/wiki/spaces/DB/pages/906231862/Les+portages+DSFR+en+cours))

**Comment by Nickvalley** [comment]
Confusion entre notre plateforme https://territoiresentransitions.fr/ et celle du CGDD/MTE https://territoires-en-transition.ecologie.gouv.fr/#
