### ISSUE TITLE
Maquettage "Prochain Objectif" et Critères (#1495)

### ISSUE THREAD

**Issue by Nickvalley** [betagouv/territoires-en-transitions#1561]
#1495

- [x] Terminer les critères (Nicolas)
- [x] Terminer les maquettes des différents cas de figure (Camille)

- [ ] Rediscuter métier/design (Nicolas & Camille) le lien avec fonctions d'usage/impact utilisateurs pour inciter les personnes utilisatrices à faire progresser leur collectivité:
- Priorité 1 : Donner envie de remplir et d'atteindre la 1ère étoile (vue liste actions non renseignées ?)
- Priorité 2 : Donner envie de réaliser les tâches (vue liste actions pas faites/programmées)

**Comment by cami-na** [comment]
Alignement Camille - Florian ok 
[- Spécifications](https://github.com/betagouv/territoires-en-transitions/issues/889#issuecomment-1061697665)
[- Proposition de maquettes ](https://www.figma.com/file/YhEoPD2YxqHuEaPn8nKWql/Maquettes-2k22?node-id=0%3A1)

@Emelinejy et @Nickvalley : revoir le parcours + finaliser les textes
