### ISSUE TITLE
Discussion sur les exports

### ISSUE THREAD

**Issue by Emelinejy** [betagouv/territoires-en-transitions#1616]
- [x] Liste des besoins associés
- [x] Discussion sur comment développer les fonctionnalités associées à ces besoins
- [ ] Prioriser ces fonctionnalités

**Comment by cami-na** [comment]
#Besoins liés à l’export

Par ordre de priorité (valeur pour les utilisateurs)

##Sauvegarde de l’ensemble des données renseignées
En tant que personne membre d’une collectivité, je veux m’assurer que toutes les données renseignées sur l’application sont sauvegardées régulièrement afin de prévenir toute perte de mon travail.

**Critères d’acceptation**
Sauvegarde automatique régulière via les serveurs - En cours dév : cf issue #1497 

Comment communiquer auprès des utilisateurs sur la mise en place de ce backup ? Rubrique Paramètres, texte explicatif en plus de la future possibilité d’export ? 

À penser en parallèle de la fonctionnalité d’historique des modifications

##Mémos, pense-bête
En tant que personne membre d’une collectivité, je veux écrire des notes pour moi-même ou mes collègues dans les fiches action afin de faciliter le suivi de l’avancement des actions, me rappeler quelles informations sont manquantes

**Critères d’acceptation** 
- Dans chaque fiche action, un champ permet d’écrire une note
- Une fois publiée, la note est uniquement visible par les membres de la collectivité 
- Les notes les plus récentes sont affichées directement dans la fiche (taille limite à définir selon la maquette)
- Les notes sont intégrées à l’historique des modifications (dans la chronologie)
- À moyen terme : possibilité d’éditer, supprimer, marquer comme résolu, tagger des personnes

##Visualisation de l'avancement sous forme de graphiques
En tant que personne membre d’une collectivité, je veux consulter des graphiques représentant l’avancement du remplissage des référentiels afin de disposer d’une synthèse visuelle pour identifier les priorités et les partager en interne

Co-design en équipe, prototypage rapide et tests pour identifier les représentations pertinentes ?

##Travail collaboratif 
En tant que personne référente d’une collectivité, je veux partager une fiche action à une personne membre de ma collectivité (collègue) afin qu’elle puisse la renseigner directement

**Critères d’acceptation** 
- Un bouton « Partager » sur chaque fiche action, permettant de copier le lien URL de la page 
    - Pour les personnes membres de la collectivité avec droits d’édition : possibilité de modifier le contenu
    - Pour les personnes membres de la collectivité avec uniquement droits de consultation : page visible mais sans possibilité de modifier le contenu
    - Pour les personnes membres de Territoires en transitions : page visible mais sans possibilité de modifier le contenu
    - Pour les personnes non membres de Territoires en transitions : page non accessible (imaginer un message d’erreur sympa)

Implique la distinction droits de consultation / édition pour les membres des collectivités -> sujet à clarifier en équipe

##Mise à jour hors connexion
En tant que personne membre d’une collectivité, je veux éditer les statuts et descriptions des actions hors connexion afin de pouvoir travailler sur l’application dans un lieu qui ne dispose pas de connexion (train, salles de réunion) et éviter la double saisie.

**Critères d’acceptation** 
Possibilité d’éditer les statuts et descriptions des actions sans connexion Internet, et enregistrement une fois la connexion retrouvée.

##Export de l’ensemble des données renseignées format Excel
En tant que personne référente ou conseillère d’une collectivité, je veux exporter les données renseignées dans l’application au format Excel afin d’effectuer des traitements personnalisés complémentaires de ceux proposés sur l’application (graphiques) et de me rassurer avec une sauvegarde personnelle.

**Critères d’acceptation**
Tableau Excel à créer à partir des champs existants dans l’application qui vont correspondre aux différentes colonnes 
1 tableau par référentiel 
Une fois tous les besoins ci-dessus adressés, cette fonctionnalité ne sera plus aussi pertinente mais reste importante pour l'aspect éthique : ce sont leurs données, les utilisateurs doivent pouvoir les récupérer quand ils le souhaitent. Ce sera sans doute utile également pour certains traitements spécifiques faits par les conseillers.
