### ISSUE TITLE
Améliorer la personnalisation en affinant certaines règles

### ISSUE THREAD

**Issue by Nickvalley** [betagouv/territoires-en-transitions#1618]
- [ ] CAE 1.1.2.1.5 que pour les communes, non concerné pour les autres
- [ ] 1.1.1.4.3 CAE - Ajouter une Question Zone PPA avec une règle dans les questions et caractéristiques - Non concerné pour les collectivités non Zone PPA
- [ ] CAE Établir un schéma directeur pour la création/extension-densification d'un réseau de chaleur (collectivités métropolitaines)
identifiant: 1.2.1.4 que pour les métropoles (et CU?)
- [ ] CAE 1.2.2.1.1 Prendre la compétence d’organisation de la mobilité (pour les communautés de communes)
- [ ] Changement de pondération -Suivre les actions mises en œuvre et atteindre des résultats significatifs id: 1.2.2.5
points: 30 (40% pour les AOM >100 000 hab)
- [ ] id: 1.2.3 - personnaliser les compétences pour basculer les actions correspondantes en "non concerné".

**Comment by Emelinejy** [comment]
Repris dans https://www.notion.so/territoires-en-transitions/Correction-am-lioration-des-r-f-rentiels-b22f94119c1e4278b882c04213a5b0d0
