### ISSUE TITLE
B - Où est l'action non renseignée de la CC Eguzon - Argenton - Vallée de la Creuse ?

### ISSUE THREAD

**Issue by derfurth** [betagouv/territoires-en-transitions#1668]
Les statut enregistrés en non renseigné :
+-----------+-------------+
|action_id  |avancement   |
+-----------+-------------+
|eci_1.2.4.1|non_renseigne|
|eci_1.2.4.4|non_renseigne|
|eci_1.2.4.3|non_renseigne|
|eci_1.2.4.2|non_renseigne|
|eci_2.5.2.3|non_renseigne|
|eci_2.5.2.2|non_renseigne|
|eci_2.5.2.1|non_renseigne|
|eci_3.2.0  |non_renseigne|
+-----------+-------------+

**Comment by Nickvalley** [comment]
Plus d'action non renseignée sur le tableau de bord - Réglé
