### ISSUE TITLE
T Référentiel vue thématique : Mettre les actions ECi dans les bonnes thématiques

### ISSUE THREAD

**Issue by Nickvalley** [betagouv/territoires-en-transitions#179]
- [x] afficher les orientations économie circulaire dans les thématiques correspondantes indiquées dans les .md (cf. la génération de code)
- [x] afficher le référentiel climat-air-énergie avant le référentiel économie-circulaire dans la liste déroulante

**Comment by penelopel** [comment]
@Nickvalley en attendant qu'on reprenne l'UX de cette partie, est-ce que ce sera pas pertinent de changer le nom de "thématiques" qu'on ne comprend pas trop ? 
![image](https://user-images.githubusercontent.com/5320547/124779821-5f9ea480-df42-11eb-8d78-0a65399c5816.png)

Par exemple "Tous" ou "Combinés" ou "Combinés par thème" (c'est juste une lettre de plus que "Economie circulaire)

![image](https://user-images.githubusercontent.com/5320547/124779870-6b8a6680-df42-11eb-9c16-70741f83a095.png)

**Comment by Nickvalley** [comment]
En 3ème choix après économie circulaire et climat-air-énergie : « Les deux » ou « Vue combinée » ?
Et je reste d’avis que des infos. au survol des différents composants ça aiderait exemple ici : « Choisir le référentiel à visualiser »

**Comment by bertrandlalo** [comment]
Question : Que faire des actions du référentiel ECI qui n'ont pas de thématiques ?
