### ISSUE TITLE
B - L'utilisation de la fonction "refresh-F5" entraine la perte du compte plus de compte associer à la fonction "(modifier) du hearder" puis des bugs de navigation et d'affichage

### ISSUE THREAD

**Issue by Nickvalley** [betagouv/territoires-en-transitions#181]
![20210612_Refresh Perte du compte puis bugs d'affichages  Screen 1  Refresh - Nom CL disparu](https://user-images.githubusercontent.com/67585509/121853213-ee782280-ccf0-11eb-8ca0-8a5b42163594.JPG)

![20210612_Refresh Perte du compte puis bugs d'affichages  Screen 2  Refresh - Nom CL disparu -- Menu qui génère des bugs d'affichage](https://user-images.githubusercontent.com/67585509/121853225-f1731300-ccf0-11eb-8785-ce9d92a6e573.JPG)

![20210612_Bug d'affichage](https://user-images.githubusercontent.com/67585509/121853230-f3d56d00-ccf0-11eb-8b7f-0fbbf81a2723.jpg)

**Comment by Ynote** [comment]
@Nickvalley Je n'arrive pas à reproduire sur https://app.territoiresentransitions.fr de mon côté. Je me demande s'il est possible que quelque chose soit resté en cache de ton côte (ou du côté de la personne chez qui c'est arrivé). Je vais essayer de creuser cette piste. J'ai peur que cette histoire de cache va nous impacter plus d'une fois.

Si tu as le temps, je veux bien que tu retestes de ton côté en vidant ton cache.

**Comment by Ynote** [comment]
Vu ensemble, pour reproduire : 
- Aller sur une vue du référentiel
- Cliquer sur un statut de la barre d'avancement
- Rafraichir la page

Constat : 
- la navigation ne fonctionne plus
- l'affichage des pages est cassée
- On perd l'epci id sur lequel on est de façon aléatoire.
