### ISSUE TITLE
Discuter avec Camille pour inciter au remplissage

### ISSUE THREAD

**Issue by Emelinejy** [betagouv/territoires-en-transitions#1823]
Mettre des boutons qui renvoient vers la liste des tâches non renseignées ! (sur le tableau de bord notamment)

**Comment by cami-na** [comment]
À discuter 
- [maquette](https://www.figma.com/file/YhEoPD2YxqHuEaPn8nKWql/Maquettes-2k22?node-id=1263%3A26089) 
- reformuler "Taux de remplissage" par "État des lieux" ?
