### ISSUE TITLE
Ajouter bouton d'appel à l'action sur le tableau de bord

### ISSUE THREAD

**Issue by Emelinejy** [betagouv/territoires-en-transitions#1888]
- [x] [Maquette](https://www.figma.com/file/YhEoPD2YxqHuEaPn8nKWql/Maquettes-2k22?node-id=1276%3A25733)

- [x] Rediriger le lien "Mettre à jour" de la page "Labellisation" pour amener vers la vue des tâches détaillées

**Comment by cami-na** [comment]
[Maquette](https://www.figma.com/file/YhEoPD2YxqHuEaPn8nKWql/Maquettes-2k22?node-id=1276%3A25733)
