### ISSUE TITLE
Améliorations du Tableau de bord à discuter avec Camille

### ISSUE THREAD

**Issue by Nickvalley** [betagouv/territoires-en-transitions#1890]
Priorité 1 : 
- [ ] Graphique de visualisation de l'historique de progression dans les référentiels dans le temps du score (global) réalisé et programmé (graphe retiré de la version initiale du nouveau tableau de bord déployé avec le nouveau backend)

Priorité 1 bis :
- [ ] Graphique détaillé à l'instant T par sous-axe (CAE) ou action (ECi) (#1563) 

Priorité 2 - En lien avec reprise des fonctions plans d'actions : 
- [ ] Synthèse d'avancement des plans d'actions personnalisés (actions réalisées/en cours/Prévues)

**Comment by Emelinejy** [comment]
Voir pour mettre sur refléter sur le Tableau de bord chaque nouvelle fonctionnalité => 
- gestion des membres : info sur le nombre de membres...
- historique : info sur date de dernière modification sur le profil de la collectivité et par qui
- plan d'actions : récap' des actions en cours ou à venir...
