### ISSUE TITLE
T - Afficher le contexte / réglementation / exemples/ ressources dans les mesures(CAE) des référentiels (en plus de la description #MineD'or)

### ISSUE THREAD

**Issue by MartinRUAU** [betagouv/territoires-en-transitions#192]
- [ ] Ajouter dans les markdowns *(tâche métier/intra)* des orientations ECi les contenus : 
   - **Contexte**, 
   - **Réglementation**, 
   - **Exemples** 
   - **Ressources** 

- [ ] Afficher les contenus dans les orientations conformément à la maquette : 
   - Dans une modale les éléments informatifs avec la Description dépliée par défaut
   - Changer la façon de rajouter un commentaire

[Maïtané]
Je propose qu'il existe 4 champs - accordéon dans une mesure :
1. **Description et contextes** qui regroupera Description, Contexte et enjeux, Contexte réglementaire *(Contenu ADEME)*
2. **Exemples de bonnes pratiques** *(Contenu ADEME)*
3. **Ressources** *(Contenu ADEME)*
4. **Commentaire** *(Champ modifiable par l'utilisateur)*

**Comment by maiwann** [comment]
![image](https://user-images.githubusercontent.com/27999224/123094949-c9408e00-d42d-11eb-99f7-5b062002d792.png)

**Comment by Nickvalley** [comment]
Suite à la proposition, je suis plutôt d'avis de séparer dans le produit la description et le contexte (à discuter Maïtané) du coup on aurait l'affichage suivant :
1. **Description *(Contenu ADEME)*
2. **Contexte** qui regroupera Contexte et enjeux, Contexte réglementaire *(Contenu ADEME)*
3. **Exemples et bonnes pratiques** *(Contenu ADEME)*
4. **Ressources** *(Contenu ADEME)*

5. **Commentaire** *(Champ modifiable par l'utilisateur)* --> Mieux distinguer visuellement ce champ de contenu modifiable par l'utilisateur du contenu des référentiels

**Comment by maiwann** [comment]
Après discussion avec Nicolas et Martin, je vais revoir l'affichage du haut des mesures avec :
- Dans une modale les éléments informatifs
- Changer la façon de rajouter un commentaire

Peut-être en faire une nouvelle issue ?

**Comment by maiwann** [comment]
En attendant de savoir, voilà les maquettes d'après ce qu'on a discuté hier @Nickvalley @MartinRUAU (je ne suis pas sure du bouton "voir les détails", si vous avez une meilleure formulation, je prends)

Au clic sur le bouton "Voir les détails", la modale s'afficherait :

![Capture d’écran 2021-08-11 à 12 03 42](https://user-images.githubusercontent.com/27999224/129010804-49a96b80-c66b-4f39-a19e-35dacec8e311.png)


![Capture d’écran 2021-08-11 à 12 03 49](https://user-images.githubusercontent.com/27999224/129010797-17004e16-bae8-4d73-afd1-dd2719c23952.png)

**Comment by maiwann** [comment]
Note : Pour l'instant, je n'ai pas changé le champ commentaire car j'ai en tête qu'il va évoluer dès qu'on va se positionner sur une "discussion" que pourraient avoir les conseillers et les collectivités. D'ici là, je propose qu'on le garde comme cela. On en rediscute si ça vous semble pas top @Nickvalley @MartinRUAU

**Comment by MartinRUAU** [comment]
C'est pas mal comme ça! Pour "Voir les détails", on pourrait mettre "Afficher les détails", ce qui permettrait d'avoir un bloc de même taille que "Créer une fiche actions", mais c'est un détail, ça me va comme ça! Pour le champ commentaires, je trouve qu'il ne se distingue pas encore assez, malgré le fait qu'il se retrouve "tout seul", à voir avec Nico pour le choix!

**Comment by maiwann** [comment]
@Nickvalley Qu'est ce que je fais des sections qui sont vides ? Je voudrais enlever le titre si possible, plutôt qu'avoir une section qui s'ouvre et est vide

**Comment by maiwann** [comment]
Note : la 2.3.3 ne comporte aucune des nouvelles sections (et est marquée en TODO ^^' )

**Comment by Nickvalley** [comment]
Oui à discuter. Côté produit sur ECi Martin a aussi fait des sections vides ET des sections absentes donc faudrait qu'on en rediscute avec @derfurth et @bertrandlalo car je n'avais pas en tête que l'on aurait des sections de descriptions vides. J'imagine que pour le produit c'est plus simple de rechercher une section et si elle est absente de ne rien afficher que de vérifier si la section est vide...mais peut-être que ça peut gérer les deux...

**Comment by Nickvalley** [comment]
> 
> 
> Note : la 2.3.3 ne comporte aucune des nouvelles sections (et est marquée en TODO ^^' )

Je demande au bureau d'appui Cit'ergie si c'est prévu pour bientôt, si c'est pas prêt lorsque nous voulons pousser le contenu en production nous pourrons afficher avec un contenu vide ou des informations a minima

**Comment by maiwann** [comment]
J'ai fini les copier/coller à l'instant. Je compte refaire une passe sur le fond et la forme du contenu lorsque la carte aura été implémentée une première fois. J'en profiterai aussi pour vérifier les liens (pour l'instant je ne l'ai pas fait pour gagner du temps).

@Nickvalley j'aurai besoin de ta relecture sur la réglementation de la 6.2.4 qui était un tableau pas facile à transformer en listes donc tout n'est peut-être pas parfait 😬

**Comment by bertrandlalo** [comment]
@maiwann  @Nickvalley 

Voilà ce que ça peut rendre.
Question : dans les markdowns, il n'y a que la section "contexte"  qui contient 2 parties "contexte et enjeux" et "reglementations". Du coup, je suis obligée de les traiter comme un seul bloc... cf screenshots ci-dessous. 
Sinon, il faudrait changer les md pour avoir : 
```
## contexte 
Le contexte et les enjeux. 

## reglementation
Les réglementations 
...
```
En gros : 
 -  ##XXX définie un bloc "XXX" (ex : description, ressources, exemples, ...) 
 - **xxx** définissent du gras au sein des parties

![screen1](https://user-images.githubusercontent.com/22340670/131826455-6b60609e-fd76-45a8-b4a8-fe70c3bd9f66.jpg)
![screen2](https://user-images.githubusercontent.com/22340670/131826466-e57dc8ac-fef6-4f54-8767-7ec60cb9577c.jpg)
![add-contexte-reglementation-and-co](https://user-images.githubusercontent.com/22340670/131826471-cb869fc0-0ce6-45f6-9a47-f531af702861.gif)

**Comment by Nickvalley** [comment]
> je suis obligée de les traiter comme un seul bloc... cf screenshots ci-dessous.

C'est OK pour le bloc unique "Contexte et réglementation". 

_Nota : Dans la majorité des cas y'a du réglementaire mais pas partout, surtout sur économie circulaire et ça nous évitera d'avoir plein de blocs absents et aussi de trop mettre en avant l'aspect "contenu réglementaire" qui n'est pas la vocation de notre produit et sur lequel nous devons faire attention à ne pas nous positionner en responsabilité car l'information peut-être obsolète vis-à-vis du contenu en vigueur sur lequel le Ministère et le autorités légales de contrôle compétentes (exemple DREAL) ont la responsabilité_

**Comment by maiwann** [comment]
Rien à dire de plus que Nicolas, mais ça me fait trop plaisir de voir tout ce contenu s'intégrer et prendre vie 😍 ❤️

**Comment by Nickvalley** [comment]
> 
> 
> > Note : la 2.3.3 ne comporte aucune des nouvelles sections (et est marquée en TODO ^^' )
> 

Visiblement ils sont pas pressés et n'avaient pas prévu de le faire avant l'automne. J'ai demandé qu'ils repriorisent car on voit bien que cette mesure voirie (celle dont on a parlé en dernier entretien conseiller de façon critique sur le fait qu'elle ne soit pas dans le bon domaine) mérite des explications a minima de contexte sur pourquoi la "Voirie" fait partie du patrimoine de la collectivité

**Comment by Nickvalley** [comment]
> @Nickvalley j'aurai besoin de ta relecture sur la réglementation de la 6.2.4 qui était un tableau pas facile à transformer en listes donc tout n'est peut-être pas parfait 😬

Est-ce que tu parlais bien de la 6.2.4 par ce que j'ai pas l'impression que y'avait un tableau pour la 6.2.4? 🤔 . 

Par contre la partie réglementaire de la 6.2.4 parle d'un "décret d'application à paraître" qui 1/n'est pas un décret mais un arrêté et 2 est déjà paru le 10 avril 2020 ["Arrêté du 10 avril 2020 relatif aux obligations d'actions de réduction des consommations d'énergie finale dans des bâtiments à usage tertiaire"](https://www.legifrance.gouv.fr/loda/id/JORFTEXT000041842389/2021-09-02/)! Ce type de contenu obsolète m'interpelle alors que c'est la première lecture métier que je fais et je tombe direct sur une info dépassée...
