### ISSUE TITLE
T [Pair] - Dans les fiches actions : Préciser les limitations des champs de saisie pour ne pas avoir de surprise à la validation

### ISSUE THREAD

**Issue by pntbr** [betagouv/territoires-en-transitions#20]
hint texte sous le champ id texte 
- [x] ex: 1.2.3, A.1.a, 1.1 permet le classement

hint budget 
- [x] ne doit comporter que des chiffres sans espaces.
erreur sous buget

valider sans titre
- [x] alert il manque un titre à la fiche actions.

valider avec un mauvais champ budget
- [x] alert attention ce champ comporte des caratères non autorisés

**Comment by maiwann** [comment]
@derfurth Est-ce que le message de précision sous le champ budget peut être tout le temps présent ? (et pas que quand on met des espaces)

(j'adore le petit message d'erreur quand on valide sinon !)
