### ISSUE TITLE
Bug statuts de demande de labellisation

### ISSUE THREAD

**Issue by Nickvalley** [betagouv/territoires-en-transitions#2009]
Voir PR #2192

https://app.territoiresentransitions.fr/collectivite/5075/tableau_bord demande en cours ?

- Syndicat pour la valorisation et le traitement des dechets menagers et assimiles du Puy-de-Dome et de la Haute Loire (VALTOM) - 4896
- CC Intercom Bernay Terres de Normandie - 4184
- CA de Nevers - 4770

Contexte : En qualifiant les collectivités proche de la Demande de 1ère étoile @margot.niedzwiedzinski a identifié une incohérence sur le compte de la CA de Dinan : 
   - Sur le tableau de bord la collectivité s'affiche avec une "Demande envoyée" et pourtant elle n'a pas renseigné tous les statuts car il manque le statut sur la tâche ajoutée 1.1.1.3
   - Et la collectivité n'apparaît pas dans la liste Retool des demandes de label (même pas en brouillon avec la coche verte)
   - Et les personnes référentes de la CA Dinan ne se sont pas connectées depuis l'arrivée de la fonctionnalité de demande de label

**➡️ Autres collectivités concernées (Liste en cours) :**

- CC du Sud Estuaire - NC
- SYTEVOM SYndicat Transfert Elimination Valorisation des Ordures énagères - NC
- Ploërmel Communauté - NC
- CC Ecueillé-Valençay - NC
- SICTOM de la region de Nogent-le-Rotrou

Cas particulier collectivité : CA Concarneau Cornouaille Agglomération, ou pour CAE le bouton est actif mais pas sur ECI (première fois que je vois ce cas donc je le remonte) : https://app.territoiresentransitions.fr/collectivite/4212/tableau_bord

**Comment by Margotnied** [comment]
+2 : 
-  CA du Grand Chambéry
- Syndicat pour la valorisation et le traitement des déchets ménagers et assimilés du Puy-de-Dôme et de la Haute Loire (VALTOM)

**Comment by Emelinejy** [comment]
Problème résolu sauf en lecture seule sur CA Nevers
