### ISSUE TITLE
Je peux regarder des tutos qui m'expliquent la prise en main de l'outil

### ISSUE THREAD

**Issue by penelopel** [betagouv/territoires-en-transitions#202]
Tuto 1 pour DTECI : création de compte / accès au référentiel / mes données qui s'ajoutent / mes données à compléter / ce que j'ai de plus par rapport à l'outil d'avant en terme de référentiel (V3 + indicateurs + notation et pondération) 

Tuto 2 : 
Nouveau ! Outil de travail pour leur plan d’action
=> Je peux lier mon plan d’action personnel au référentiel (NB : pas encore facile à utiliser)
=> Je peux compléter/nourrir mon plan d’action avec le référentiel (en ajoutant action)
=> je peux ajouter mes propres indicateurs

**Comment by Nickvalley** [comment]
@penelopel Cette carte n'était plus dans aucun backlog. Je l'ai remise dans la Story-map

**Comment by Nickvalley** [comment]
Réglé via la mise en place de Crisp qui permet la mise en ligne de vidéos et screenshots.
Parcours initial d'onboarding mis en ligne sur Crisp avec visuels
