### ISSUE TITLE
[Spécification métier] Gestion des preuves

### ISSUE THREAD

**Issue by Nickvalley** [betagouv/territoires-en-transitions#2046]
- [ ] Onglet de gestion de toutes les preuves
- [ ] Possibilité d'exporter une ou toutes les preuves importées en conservant la structure de dépôt dans le référentiel (exemple : 1.1.1_[NOM FICHIER]

**Comment by Emelinejy** [comment]
Spécification sur https://www.notion.so/territoires-en-transitions/Je-peux-d-poser-des-fichiers-preuves-7f3c3b12297e40b38a2bb1e0263b3c92#78b8b92b30cb4cc09b4c1bfab471f708

Reste 2 questions en suspens à voir avec Camille : renommage des fichiers lors du téléchargement ? téléchargement de plusieurs documents en même temps ?
