### ISSUE TITLE
Lorsque j'arrive sur le référentiel, j'ai une indication visuelle sur ce qui a changé par rapport à la version précédente du référentiel

### ISSUE THREAD

**Issue by penelopel** [betagouv/territoires-en-transitions#207]
tag "nouveau"

**Comment by Nickvalley** [comment]
Je rebascule cette fonctionnalité dans la Story-map car en principe en dehors du passage de la V2.2 vers la v3 il ne devrait pas y avoir de nouvelles choses sur les référentiels avant la sortie des versions 2022 des référentiels  (janvier 2022) qui devraient se contenter de mises à jour à la marge des référentiels.
