### ISSUE TITLE
US En tant qu'équipe, je peux savoir qui se crée un compte et utilise l'application

### ISSUE THREAD

**Issue by penelopel** [betagouv/territoires-en-transitions#208]
A ce stade, on ne peut pas suivre qui se crée un compte et/ou utilise l'outil. 

Il nous faudrait un petit outil d’admin qui demande au keycloak de l’ADEME qui crée un compte et utilise l'outil

- [x] faire un point sur les DCPs
  - [x] ajouter un endpoint pour retool dans notre API afin de pouvoir recupérer les DCPs sans passer par le VPN

----
- [x] faire une interface pour lister les utilisateurs
- [x] personne et les collectivités liées
- [x] proxy pour l'activité lié à un utlisateur
  - [ ] dernière connexion (à voir au niveau du keycloak) 
  - [x] OU volume de données crée sur le référentiel et les fiches actions
----
- [x] collectivités et des personnes liées (doit permetre d'identifier les collectivités sans utilisateurs)

**Comment by derfurth** [comment]
Ok on s'en chargera sans doute avec retool.
