### ISSUE TITLE
Quand je rentre une donnée dans un indicateur, un autre indicateur affiche ces données si je filtre

### ISSUE THREAD

**Issue by maiwann** [betagouv/territoires-en-transitions#213]
Remettre en place les filtres de recherche sur les référentiels, indicateurs

(Idéalement il faudrait tenir Aurélia de Hennebont au courant de la résolution du bug)

**Comment by maiwann** [comment]
Par exemple, chez Hennebont, les indicateurs 3a et 1a ont les mêmes données, alors que je n'ai rempli que l'un des deux avec l'emoji 🐞 

![image](https://user-images.githubusercontent.com/27999224/122735457-572a4680-d27f-11eb-966a-30d503120eaa.png)
![image](https://user-images.githubusercontent.com/27999224/122735536-690be980-d27f-11eb-80ec-a755e4b21f35.png)

**Comment by maiwann** [comment]
Hum… mais quand je ne filtre pas, 3a n'a pas les données ?!

![image](https://user-images.githubusercontent.com/27999224/122735933-c6079f80-d27f-11eb-83eb-0a9f15e67873.png)

**Comment by Nickvalley** [comment]
Plus de fonction recherche sur les indicateurs donc plus de bug
