### ISSUE TITLE
B- Etoile à auditer pour CA Pays Voironnais sur page "Labellisation ECi"

### ISSUE THREAD

**Issue by Emelinejy** [betagouv/territoires-en-transitions#2160]
----

A priori c'est le seuil précédent qui est choisi.

- CA du Pays Voironnais - Score >65% et seulement 1ère étoile qui s'affiche https://app.territoiresentransitions.fr/collectivite/4437/tableau_bord 
----

ce n'est pas la bonne étoile qui s'affiche par rapport au score atteint
OK au 01-08 - en Production : Est Ensemble - 5386 à 59% mais seulement la deuxième étoile proposée pour la Labellisation, Toulouse Métropole - 4276 à 40 % mais seulement la première étoile proposée
- sur upcoming : CC Porte du Périgord - 4019, SIRTOM Vallée de la Grosne - 5047, SM Cyclad - 4038

**Comment by Margotnied** [comment]
Ajout  CA du Pays Voironnais
