### ISSUE TITLE
Afficher la notation dans le référentiel ECi

### ISSUE THREAD

**Issue by derfurth** [betagouv/territoires-en-transitions#217]

**Comment by maiwann** [comment]
![image](https://user-images.githubusercontent.com/27999224/122904707-de93ba80-d350-11eb-9d4b-bd164e01c30d.png)

La maquette avec les 3 niveaux de notation pour la page Référentiel

**Comment by maiwann** [comment]
Et la maquette pour la page Mesure : 
![image](https://user-images.githubusercontent.com/27999224/122904816-f8cd9880-d350-11eb-8a8c-260218d8fb2e.png)

**Comment by Nickvalley** [comment]
Une différenciation mais qui nécessite pas forcément de refaire une maquette vu que c'est une information en moins
- Quand on est sur action ou une tâche en dessous des mesures/orientations y'a pas de points, juste des %
- Quand on est sur une tâche qui n'a pas d'enfant : Pas fait = 0% ; Fait = 100%. 


+ Je me rend compte qu'il manque l'affichage des scores programmés : Si statut = "Prévue" alors le score de réalisé est à 0% mais le score "programmé"(=lorsque ce qui est prévu sera fait) est à 100%. Je pense qu'on peut gérer cette partie dans un deuxième temps mais ce sera indispensable d'avoir un truc lisible pour Cit'ergie donc ça serait bien de commencer à imaginer tout de suite la façon de l'afficher donc je veux bien en discuter dès à présent car je pense qu'on pourra discuter ces maquettes en fin de semaine très concrètement avec les conseillers pour qu'ils réagissent dessus.
+Et plus tard certainement que le "Prévu" et "En cours" devront pouvoir être gérés avec un curseur entre 0 et 100% permettant de dire combien est réalisé et combien programmé. A suivre dans les discussions avec les conseillers et collectivités.
