### ISSUE TITLE
TT - Je veux pouvoir visualiser l'ensemble de mon plan d'actions de façon synthétique

### ISSUE THREAD

**Issue by Nickvalley** [betagouv/territoires-en-transitions#221]
- [x] Cf. maquette de vue de synthèse du plan d'actions. Inverser les statuts (à droite) et retard (à gauche)

**Comment by maiwann** [comment]
Pour ça j'ai besoin de faire du pair avec quelqu'un sur le front :)

**Comment by penelopel** [comment]
### Retours utilisateurs (via mail) sur la fonctionnalité "Pouvoir visualiser l’ensemble d’un plan d’actions de façon synthétique
"

1. Est-ce que ça vous serait utile ? 
- OUI  +++
- Pas nécessairement, ou alors seulement dans le cas où l’ensemble des différents programmes d’actions sont regroupés sur la plateforme et cela permettrait d’avoir une vision d’ensemble lorsque le plan n’est pas porté par son pôle respectif.
- oui
- oui

2. Si oui, dans quelle optique ?
- Présenter et rendre compte de l’avancement de la mise en œuvre du Plan d’action aux élus
-  surtout pour le chef de projet qui peut en un seul coup d’œil voir l’état d’avancement du plan d’actions
-  Prendre de la hauteur

3. Quelles informations rechercheriez-vous dans une telle synthèse ? 
- Un visuel parlant et efficace qui reprenne les actions et leur taux d’avancement
- directions pilotes, actions, état d’avancement, commentaires
-  La liste des actions pour une catégorie. S’il est possible de cliquer sur l’action pour renvoyer à la fiche cela peut également être une autre façon de chercher.

**Comment by derfurth** [comment]
Prévoir une discussion avec @maiwann

**Comment by maiwann** [comment]
Discussion avec Nicolas : 
- Le pliage/dépliage ++
- quand je fais précédent, est-ce que je peux me retrouver à l'endroit où j'étais ?
- réduire la taille des titres pour qu'ils soient moins monumentaux / idem pour les titres des fiches

**Comment by maiwann** [comment]
@derfurth @bertrandlalo A priori on va s'en tenir aux points que j'ai listés au-dessus, peut-être pas nécessaire de faire du pair finalement 🤔 Qu'en pensez-vous ?

**Comment by Nickvalley** [comment]
@maiwann J'ai mis à jour la description et je me dis que ce serait bien de faire un maquette des choses basiques qu'on pense modifier a minima et confronter ces maquettes aux personnes qui nous font déjà des retours sur les fonctionnalités plan d'actions listées dans la description

**Comment by maiwann** [comment]
![Plan d'actions](https://user-images.githubusercontent.com/27999224/129341463-2aa7018e-8c9f-4841-8989-c2e22a41734d.png)

cc @Nickvalley

**Comment by maiwann** [comment]
Note @Nickvalley : si on permet de replier des parties du référentiel, on perd peut-être de la découvrabilité, dans le sens où les personnes vont moins facilement découvrir des actions si elles sont cachées. Est-ce que c'est un souci ? (on pourrait dans un 1er temps ne pas permettre de replier les choses et voir si la frustration est toujours là ? Parce qu'une fois qu'on a mis la fonctionnalité, ça sera compliqué de la retirer 😬 )

**Comment by Nickvalley** [comment]
> 
> 
> Note @Nickvalley : si on permet de replier des parties du référentiel, on perd peut-être de la découvrabilité, dans le sens où les personnes vont moins facilement découvrir des actions si elles sont cachées. Est-ce que c'est un souci ? (on pourrait dans un 1er temps ne pas permettre de replier les choses et voir si la frustration est toujours là ? Parce qu'une fois qu'on a mis la fonctionnalité, ça sera compliqué de la retirer 😬 )

Il faut qu'on puisse avoir une vue d'ensemble de la structure puis rentrer dedans. 
Ce que j'ai en tête : Les filtres gardent l'affichage de la structure et déplient l'ensemble du référentiel sur le résultat du filtre. 
On plie-déplie uniquement sur les axes et ensuite les sous-axes pourraient être dépliés par défaut. 
Je pense que ce serait bien de maquetter la version avec 3 niveaux de structure en lien avec l'US #72 car pour l'instant il n'y a que la maquette de la modale de gestion de la structure du plan d'actions

**Comment by Nickvalley** [comment]
Carte à nettoyer en créant des nouvelles cartes dans la story-map sur plans d'actions
