### ISSUE TITLE
Amélioration du rattachement d’un membre déjà existant [front]

### ISSUE THREAD

**Issue by derfurth** [betagouv/territoires-en-transitions#2234]
https://www.notion.so/territoires-en-transitions/Gestion-des-acc-s-et-invitation-f5b381344b35470c957b1159a1af9329#6a2e723b8fcf4003a4ffd88431595412

Étapes:
- [x]  integration graphique et scenarios - Arthur
- [x]  ajout data réelles + actions - Raphaëlle
- [x]  redaction de tests e2e - Arthur -> review par Marc

**Comment by cparthur** [comment]
Étapes:
- [ ] integration graphique et scenarios - Arthur
- [ ] ajout data réelles + actions - Raphaëlle
- [ ] redaction de tests e2e - Arthur -> review par Marc
