### ISSUE TITLE
T - Import de la fonte Marianne

### ISSUE THREAD

**Issue by derfurth** [betagouv/territoires-en-transitions#2255]
A priori la fonte Marianne est chargée avec un chemin relatif, ce qui cause une erreur.

<img width="1376" alt="image" src="https://user-images.githubusercontent.com/1872471/178691269-76f70fd4-5734-446b-8bb6-41d02cc17344.png">

**Comment by marc-rutkowski** [comment]
Le problème semble venir de la version de react-dsfr utilisée (ou de notre manière de l'utiliser ?) pour laquelle les chemins d'origine des fontes (du type `url("../fonts/Marianne-Light.woff2")`) ne sont pas ré-écrits au moment du build.

Rien de bien grave :  la requête échoue mais la fonte est tout de même correctement chargée lors de l'inclusion de la feuille de styles dsfr.css car celle-ci est correctement traitée par le build (les chemins sont ré-écrits sous la forme `url("/static/media/Marianne-Light.[hash].woff2")`

A traiter avec le #2193
