### ISSUE TITLE
T - Je visualise les actions que je n'ai pas encore renseignées

### ISSUE THREAD

**Issue by Nickvalley** [betagouv/territoires-en-transitions#226]
- [ ] Sur les pages du référentiel où on peut remplir les statuts, ajout d'un toggle qui permet de filtrer les actions non-renseignées = "Afficher uniquement les actions non-renseignées" 

OLD -- 

Permettre d'identifier facilement les actions qui ne sont pas encore renseignées pour une collectivité. 
Solution à discuter : 
- [ ] Vue des référentiels filtrée aux actions sans statut de coché
- [ ] Au clic sur l'étoile de complétude - afficher la liste des actions sans statut de renseigné

**Comment by Emelinejy** [comment]
Il me semble que la solution la plus aboutie serait un filtre, qui permettrait de ne laisser apparaitre que les actions au statut filtré. 
Cela permettrait également de filtrer les actions "prévues" et "non réalisées" pour un usage futur (construction d'un plan d'actions et suivi du plan d'actions).
