### ISSUE TITLE
Jauge et graph' non renseignées

### ISSUE THREAD

**Issue by Emelinejy** [betagouv/territoires-en-transitions#2295]
Problème persistent pour 4649
https://app.territoiresentransitions.fr/collectivite/4649/action/cae/cae_1.1.2 

---
Mardi 26/07
Jauge et graph' non renseignées alors que statuts renseignés pour 
- 4480 CAE
- 4489 CAE
- 5213 ECi
=> résolution via insertion d'une fausse mise à jour

**Comment by bertrandlalo** [comment]
J'espère que ce sera réglé avec https://github.com/betagouv/territoires-en-transitions/issues/2318 ! Normalement oui 🤞
