### ISSUE TITLE
B - Dans les tableaux les titres des axes CAE renvoient vers des pages qui n'existent pas.

### ISSUE THREAD

**Issue by derfurth** [betagouv/territoires-en-transitions#2302]
https://www.notion.so/territoires-en-transitions/Navigation-version-mobile-et-autres-3d1e88aa2d9e49ce800982b7373d8262#cde874b07d4b40ef97918c5cfca6233a

**Comment by Emelinejy** [comment]
Sans objet car déjà signalé lors des retours de test et résolu
