### ISSUE TITLE
US FRONT - Gérer le flow d'invitations des utilisateurs

### ISSUE THREAD

**Issue by Nickvalley** [betagouv/territoires-en-transitions#241]
- [x] #1371
- [x] #1350

**Comment by maiwann** [comment]
# Les maquettes

## Cas 1 : Je suis le premier à ajouter une collectivité : Je l'ajoute (comme maintenant) + on me demande les données de contact (nouvelle modale)



![contact_modale](https://user-images.githubusercontent.com/27999224/134364542-aeafd08f-8352-4105-b91d-b2303cced215.png)

## Cas 2 : Je veux rajouter une collectivité, mais qqun l'a déjà rajoutée : Je dois demander une invitation. Pour ça : 
### soit je clique sur "Demander l'accès" et j'ai les infos de contact 

![Capture d’écran 2021-09-22 à 16 06 53](https://user-images.githubusercontent.com/27999224/134364736-d8c92a22-ff05-472f-81a3-4502dba603b0.png)
![invitation_modale](https://user-images.githubusercontent.com/27999224/134364808-32228a9e-f076-47dc-b2f3-ae6d5da2b577.png)

### Soit quelqu'un qui a déjà accès va chercher le lien d'invitation dans les paramètres (nouvelle icône à coté du nom de la collectivité) et me l'envoie par mail
![Capture d’écran 2021-09-22 à 16 24 22](https://user-images.githubusercontent.com/27999224/134364908-fdc36575-8ed1-4c48-8db6-b630609d15f2.png)
![Paramètres](https://user-images.githubusercontent.com/27999224/134365000-88e9db96-89f3-4549-8be7-433d3975fc2e.png)




## Note : L'affichage de la liste des collectivités se trouve changé, avec : 

### Format replié
![Capture d’écran 2021-09-22 à 16 06 53](https://user-images.githubusercontent.com/27999224/134365214-cc373f7a-950d-4d92-a1ca-30e6dc564428.png)




### Format déplié au clic sur Découvrir (et on replie en cliquant sur…replier)
![Capture d’écran 2021-09-22 à 16 07 06](https://user-images.githubusercontent.com/27999224/134365193-e92e801a-393d-41af-8e53-6ccef6538c2a.png)

**Comment by maiwann** [comment]
Il faut peut-être créer plusieurs issues ?

- Proposer des liens d'invitation
- Restreindre l'accès de celleux qui n'ont pas le lien
- Lister les utilisateurs d'une collectivités dans la page Paramètres
- Pouvoir retirer les droits des utilisateurs
- Pouvoir rajouter des informations de contact
- Modifier la présentation de la liste des collectivités

**Comment by maiwann** [comment]
## Modifs maquettes

Pour la 1e connexion : 
- On pré-remplit les champs de connexion avec les infos de la personne
- On enlève le numéro de téléphone

2e connexion :
- Rajouter le contact de aide@

**Comment by maiwann** [comment]
Question épépinage : Est-ce qu'on peut inviter des gens même si ils ont pas de compte ou ça coince ?

**Comment by maiwann** [comment]
Ecrire le contenu du mail d'invitation avec : 
- un lien pour créer un compte
- un lien qui ajoute la coll. à mon compte (donc il faut que j'en ai un)

**Comment by maiwann** [comment]
Ecrire un message si on a cliqué sur le lien d'invitation mais pas de compte

**Comment by maiwann** [comment]
Rajouter un bouton pour générer le lien d'invitation, et préciser sa date d'expiration.

**Comment by maiwann** [comment]
Préciser mieux où l'invitant peut trouver le lien d'invitation, coté invitant et invité

**Comment by maiwann** [comment]
Ecrire un mail prévenant les personnes qui ont déjà un compte que la fonctionnalité est arrivée + qu'il faut qu'ils mettent à jour leurs données de contact dans la page paramètres

**Comment by maiwann** [comment]
Note : Je viens de rajouter une ligne dans le tableau des droits qui dit que les utilisateurs non liés à la collectivités ne doivent pas voir les champs avec des noms-prénoms des fiches-actions.

Ca peut être mis dans une autre carte si vous me dites que c'est mieux :) @derfurth @bertrandlalo

**Comment by penelopel** [comment]
Matrice des droits à jour : https://docs.google.com/spreadsheets/d/1arVHOYz8LacfDs_usaH5MuunDEsRfenTbKAF6XYhuOA/edit#gid=0

FLOW AUDITEUR 
1) Déclencheur : Le bureau d'appui attribue un auditeur à une collectivité : 
- Si c'est la première fois : L'auditeur reçoit un mail l'invitant à se créer un compte sur Territoires en Transition et la collectivité est déjà rattachée à son compte quand il arrive. 
- Si ce n'est pas la première fois, L'auditeur reçoit un mail lui indiquant qu'une nouvelle collectivité lui a été attribuée sur Territoires en transition (elle est rattachée à son compte). 

2) Désormais, l'auditeur a des collectivités attachées à son compte sur Tet. L'auditeur a accès aux modalités pour auditer ces collectivités (à définir)
3) Une fois que l'auditeur a validé son audit, il ne peut plus le modifier. Il est rétrogradé au statut "compte utilisateur". 

FLOW CONSEILLER 
1) Déclencheur :Le bureau d'appui (ou une collectivité) attribue un conseiller à une (sa) collectivité : 
- Si c'est la première fois : L'auditeur reçoit un mail l'invitant à se créer un compte sur Territoires en Transition et la collectivité est déjà rattachée à son compte quand il arrive. 
- Si ce n'est pas la première fois, L'auditeur reçoit un mail lui indiquant qu'une nouvelle collectivité lui a été attribuée sur Territoires en transition (elle est rattachée à son compte). 

2) Pour les collectivités attachées à son compte, le conseiller a accès aux référentiels/indicateurs etc.
Warning: comment faire pour pas que les collectivités réécrivent par dessus les conseillers ? 
Options : 
a) avoir un historique
b) le conseiller a des droits "supérieurs" à la collectivité (= par ex: si une collectivité veut modifier des choses après lui, ça lui envoie un mail pour qu'il valide ou non ; la collectivité n'a plus les droits de modif quand il y a un conseiller) 
c) Avoir des champs de commentaires/justifications distincts entre conseiller et collectivité 

3) Une fois que le conseiller a fini son accompagnement, il est rétrogradé manuellement au statut "compte utilisateur" par la collectivité ou le bureau d'appui.

**Comment by penelopel** [comment]
# ARRIVEE DES UTILISATEURS 


# J'arrive de moi-même directement vers l'application

## Cas 1 : Je suis le premier à ajouter une collectivité : Je l'ajoute (comme maintenant) + on me demande les données de contact (nouvelle modale qui sera préremplie)


![contact_modale(1)](https://user-images.githubusercontent.com/27999224/134695885-010f337a-cc54-4bc1-8e40-74b095ee115c.png)


## Cas 2 : Je veux rajouter une collectivité, mais qqun l'a déjà rajoutée : J'arrive sur la page suivante quand j'essaie de l'ajouter 

![image](https://user-images.githubusercontent.com/5320547/143008025-8581b078-312c-4959-bb3d-118f81e9823b.png)


# J'arrive par un lien d'invitation

## Cas 1: Je ne suis pas connecté

![page_lien_invit](https://user-images.githubusercontent.com/27999224/134696857-7822f03c-50ee-4a1e-a776-9c22ddca9522.png)

## Cas 2: Je suis connecté 

Je peux arriver avec 3 types de lien : 
- Un lien utilisateur : la collectivité est directement ajoutée sur mon compte 
- Un lien auditeur ou un lien conseiller : la collectivité est directement ajoutée sur mon compte avec l'affichage de mon rôle

![image](https://user-images.githubusercontent.com/5320547/143008691-7353fee8-a54a-48db-91e5-04ab18211ac9.png)



# INVITATION DES UTILISATEURS 

# Cas n°1  : c'est un utilisateur qui invite un utilisateur agent 

=> La page qui gère cela est la page paramètre. La page paramètre est disponible via une icône à coté du nom de la collectivité

![Capture d’écran 2021-09-22 à 16 24 22](https://user-images.githubusercontent.com/27999224/134364908-fdc36575-8ed1-4c48-8db6-b630609d15f2.png)

La page paramètres 

![image](https://user-images.githubusercontent.com/5320547/143009537-44f1ca07-4eb4-459b-96ff-5f4f03b779e8.png)


# Cas n°2 : c'est le bureau d'appui qui invite un utilisateur agent, un conseiller ou un auditeur 

=> Cela se fait via retool. Spécification sur  #981
