### ISSUE TITLE
Retours sur l'intégration des pages référentiels et indicateurs

### ISSUE THREAD

**Issue by Ynote** [betagouv/territoires-en-transitions#250]
## Description

Cette issue reprend les retours de @Nickvalley et @MartinRUAU sur les pages référentiels et indicateurs suite à #186.
On se propose avec @newick de se le départager ainsi : 

Pour @newick : 
- [x] Page référentiel : Quand on développe une description, mention "Un titre" superflue car le titre est déjà "Description"
- Page indicateurs : 
  -  [x] L'interface pour ajouter un nouvel indicateur n'a pas été redesigné (champ titre trop petit, etc.)
  -  [x] Les boutons "modifier" dans les indicateurs des référentiels sont à retirer
  -  [x] Idem boutons dans les thématiques, à retirer
  -   [x] Y'a une icone ("précédent" et "suivant" au survol) qui s'affiche pas bien avant le champ 2016 et entre le champ "2022" et "objectif"
  -  [x] je ne vois plus les descriptions des actions et des tâches, seule celles des mesures et des indicateurs sont présentes (sur 2.2.2.1 par exemple il devrait en avoir une)
- [x] Référentiel Climat-air-énergie : Plier-déplier sur les sous-titres please :)
-  [x] Bouton "Nouvel indicateur" pas explicite. Utiliser plutôt un verbe d'action "Ajouter un indicateur"?
  -  [x] ~~Le titre "Commentaire" s'affiche deux fois lorsque l'on déplie~~ --> C'est normal, on pourrait remplacer le label par "Votre commentaire" s'il te plait Erick ?

**Comment by maiwann** [comment]
@Nickvalley Je veux bien ton avis sur les points qui me sont assignés que je n'ai pas cochés, j'ai expliqué après la petite flèche --> pourquoi je n'appliquais pas directement ta proposition

**Comment by penelopel** [comment]
> le bouton "Créer une fiche action" serait à mon sens plus explicite en étant remplacé par le texte "Ajouter à mon plan d'actions --> Je suis d'accord mais c'est un libellé plus long =/ Donc je préfère voir si ça parle aux personnes avant de le changer partout (ça prendra bcp plus de place) 

"Ajouter à mon plan" sinon ?

**Comment by Ynote** [comment]
> Si la page Mesure n'a pas d'indicateurs, il y a tout de même le titre "Les indicateurs", est-ce qu'on peut l'enlever dans ce cas ?

@maiwann Oui tutafé, je peux m'en occuper.

**Comment by Nickvalley** [comment]
> 
> 
> > le bouton "Créer une fiche action" serait à mon sens plus explicite en étant remplacé par le texte "Ajouter à mon plan d'actions --> Je suis d'accord mais c'est un libellé plus long =/ Donc je préfère voir si ça parle aux personnes avant de le changer partout (ça prendra bcp plus de place)
> 
> "Ajouter à mon plan" sinon ?

OK, alors remplacer par "Ajouter à mes actions" (c'est plus court qu'avant)

**Comment by Nickvalley** [comment]
>Les indicateurs liés aux mesures sont bien trop en bas des pages, impossible de les voir! Fonction plier de base serait top.~~ --> C'est à dire plier les actions ? Ca me chafouine car autant je comprends le souci, autant plier les actions ça veut dire un clic de plus pour accéder au contenu principal… On reparle du problème ?

Nous avons à nouveau le retour sur les premiers tests (CC Coeur de Var) sur le besoin prioritairement d'avoir une vue d'ensemble synthétique pour commencer. On va rajouter quelques clics mais gagner beaucoup de scrolls et surtout répondre au besoin d'avoir une compréhension d'ensemble avant de pouvoir commencer à renseigner
