### ISSUE TITLE
Afficher une page post connexion

### ISSUE THREAD

**Issue by maiwann** [betagouv/territoires-en-transitions#26]

**Comment by maiwann** [comment]
Après réflexion sur cette issue et la #27 je propose plutôt ces maquettes : 2 boutons une fois connecté, l'une pour les plans d'actions, l'autre pour accéder aux référentiels.

![Accueil-connectée](https://user-images.githubusercontent.com/27999224/118977789-da056c00-b976-11eb-862d-f24419a832ae.png)


Et une fois sur la page référentiels, la possibilité de voir tout trié par thématique, OU Cit'ergie seulement, OU Eci seulement.
![Accueil-connectée-1](https://user-images.githubusercontent.com/27999224/118977801-dd98f300-b976-11eb-949b-7b56b28a6b31.png)

**Comment by Nickvalley** [comment]
1ère maquette : 
- Dire "Bonjour" : Comme c'est la première chose que la personne voit en arrivant, j'aimerais ajouter un truc comme :  "Bienvenue" pour écrire au moins "Bienvenue! Que souhaitez-vous faire?" Qu'en penses-tu?
- Que penses-tu plutôt d'avoir "Voir mes actions" plutôt que "Voir mon plan d'actions" sachant que j'imagine qu'on va très bientôt avoir des comptes avec plusieurs plans d'actions distincts
2ème maquette : 
- Remplacer "Cit'ergie" par "Climat-Air-Énergie sur la 2ème maquette

**Comment by maiwann** [comment]
> Que penses-tu plutôt d'avoir "Voir mes actions" plutôt que "Voir mon plan d'actions" sachant que j'imagine qu'on va très bientôt avoir des comptes avec plusieurs plans d'actions distincts

Est-ce que ça peut être "voir mes fiches-actions" ? C'est pour bien faire les différence avec les actions des référentiels… Sauf si juste le fait de parler de **mes** actions est suffisant pour qu'on fasse la distinction ?

**Comment by Nickvalley** [comment]
En fait la question que je me pose c'est comment que l'on veut faire naviguer les collectivités comme Pays Voironnais (et beaucoup d'autres collectivités) qu'on vient d'avoir à l'instant qui ont au moins deux plans d'actions gérés par deux référents différents "CODEC" et "PCAET". 
Est-ce qu'on a deux boutons sur cette page d'accueil ou bien est-ce qu'ils n'en gardent qu'un et que sur la page plans d'actions ils pourront switcher entre leurs différents plans d'actions (fonction ajout d'un nouveau plan d'actions supplémentaire en leur donnant des noms distincts)?

**Comment by Nickvalley** [comment]
Du coup ça m'aide à préciser et j'imagine que le plus simple c'est qu'on démarre comme tu proposes avec "Voir mon plan d'actions" c'est ok et qu'on renommerait "Voir mes plans d'actions en même temps que l'on créera la fonction de gestion de multiples plans d'actions (probablement dans 1 ou 2 sprints).

**Comment by maiwann** [comment]
Ok donc j'ai mis à jour !
![Accueil-connectée(1)](https://user-images.githubusercontent.com/27999224/119013093-f2857e80-b996-11eb-9268-22a51887b190.png)
![Accueil-connectée(2)](https://user-images.githubusercontent.com/27999224/119013102-f4e7d880-b996-11eb-94b6-6cf123b2d173.png)

**Comment by maiwann** [comment]
![image](https://user-images.githubusercontent.com/27999224/120485622-936f3300-c3b4-11eb-87b0-631709bdd08c.png)

@derfurth Voilà la maquette pour l'issue !
