### ISSUE TITLE
[#conseiller] Je peux modifier manuellement la réduction de potentiel en dehors dès règles de réduction automatiques (override)

### ISSUE THREAD

**Issue by Nickvalley** [betagouv/territoires-en-transitions#269]
*Description à mettre à jour*

- [ ] Je peux voir les règles de réduction de potentiel et les points minimum autorisés pour l'action
- [ ] Si besoin, je peux réduire manuellement le potentiel de points max.
- [ ] Le fait que le potentiel ait été modifié est visible explicitement (point théoriques auto. et points corrigés)

- [ ]Plus tard : Lorsque les points de potentiel seront calculés automatiquement à partir des caractéristiques je peux apporter une justification sur la modification de potentiel apportée manuellement si elle diffère du calcul automatique (règles de base)

Lié à #73

**Comment by penelopel** [comment]
Hello,

Pour nourrir la réflexion sur ce point, comment pourrait-on montrer visuellement les "niveaux" de labellisation qu'on pourrait potentiellement atteindre en programmant de nouvelles actions ? Une échelle ? Un indice "Plus que XX points à programmer pour postuler au niveau gold" ? 

Une autre forme d'incitation possible serait l'ajout du pourcentage de collectivités qui ont réalisé ou planifier chaque action. 
"XX% des communes de taille similaire ont fait/programmé cette action."

**Comment by Nickvalley** [comment]
Proposition à challenger d'affichage du score avec le potentiel de score à venir (ce qui est "Programmé" et "En cours")
![image](https://user-images.githubusercontent.com/67585509/133582624-42cc47ad-a999-4e83-8197-9158c46fefb0.png) 😃

**Comment by cami-na** [comment]
### Modification manuelle du potentiel de points sur lequel est évaluée une collectivité (conseillers CAE et auditeurs ECI)

En tant que conseiller CAE et auditeur ECI, je veux modifier le potentiel d’une action afin de l’ajuster aux compétences de la collectivité et qu’elle ne soit pas pénalisée pour la labellisation

**Infos métier**

- Les points permettent de noter les actions réalisées par les collectivités de manière qualitative en vue de leur labellisation
- Nombre de points maximum = 500 ; ce nombre de point peut être réduit (réduction de potentiel). Exemple : si la collectivité n’a pas toutes les compétences pour réaliser les actions des référentiels, elle n’est pas notée sur 500 points mais seulement 400 ou 350
- Actuellement dans l’EMT les conseillers font cette modification manuellement
- Dans l’app il est prévu prochainement une automatisation de l'affichage des actions et du potentiel de points selon le profil de chaque collectivité (autre parcours avec validation et édition possible des critères par le ou la référente https://pad.incubateur.net/OclWer1DS7mDuwj5j3emrg#)

En parallèle de cette automatisation permettant notamment de réduire les risques d'erreur, il existe toujours des cas particuliers qui ne sont pas pris en compte dans les réductions de potentiel. Il semble donc nécessaire d’avoir cette fonctionnalité de modification du potentiel de points, même si elle ne sera a priori que très peu utilisée.

**Critères d’acceptation**

- Pour chaque niveau 1.2.3 des référentiels Économie circulaire et Climat Air Énergie : affichage des du potentiel de points (théorique ou réduit automatiquement) et option modification pour rôles conseiller et auditeur
       
- Champ "Nouveau potentiel" avec limitation automatique du nombre de points minimum et maximum selon l'action
- Champ texte "Justification" 
- Suivi des modifications (auteur, date, nombre de points initial et nouveau nombre de points, justification)
- Documentation des règles de réduction de potentiel pour l'action concernée

[Proposition de maquettes](https://www.figma.com/file/YhEoPD2YxqHuEaPn8nKWql/Maquettes-2k22?node-id=119%3A13881)

**Comment by cami-na** [comment]
Ok donc si je comprends bien,on mettra en ligne la possibilité de personnaliser les référentiels en annonçant que ces règles peuvent évoluer selon les cas d'usages repérés (en recensant tous les cas où les conseiller·es auraient aimé avoir l'override)

**Comment by Nickvalley** [comment]
Oui c'est l'idée. Et si on se rend compte qu'on n'arrive vraiment pas à éviter l'override partout : 
- 1/ on aura quand même sûrement réussi à améliorer les règles de personnalisation pour tous sur les cas généralisables où qui peuvent être gérés avec plus de valeur pour tous (et pas de façon réservée aux seuls conseillers CAE expérimentés)
- 2/ Peut-être que l'override ne sera possible/utile pas partout mais qu'à certains endroits bien spécifiques ou limités à certains utilisateurs tel que conseiller/auditeur pour éviter que cela enlève de la valeur ajoutée partout dans le produit et/ou complexifie sa prise en main pour celleux (majorité) qui en feront un usage moins "expert".
