### ISSUE TITLE
Afficher une page de statistiques d'utilisation et impact du produit

### ISSUE THREAD

**Issue by Nickvalley** [betagouv/territoires-en-transitions#295]
cf maquettes :)

**Comment by maiwann** [comment]
![Stats](https://user-images.githubusercontent.com/27999224/134876414-52d110c8-7b1a-4500-8035-cf2f3a8a91cd.png)


Sur le dernier graphique, en gris les actions programmées, en bleu les réalisées.
Je n'ai pas bien réussi à m'imaginer les chiffres et la relation entre les courbes, on peut pairer si le résultat est étrange :)

**Comment by maiwann** [comment]
@Nickvalley Manque une petite phrase pour expliquer l'impact :)

**Comment by Nickvalley** [comment]
Les autres startup parlent de page de statistiques ou chiffres et pas d'impact... y compris pour celles en accélération ou transfert donc je serais pour éviter d'appeler impact nos statistiques "de vanité" pour l'instant. 

Je propose : 
TITRE : "Statistiques de Territoires en Transitions"
Phrase d'explication :  "Découvrez ici les statistiques de déploiement et d'utilisation de la plateforme Territoires en Transitions."

- Je pense qu'à côté du nombre de collectivités il serait plus utile d'avoir le nombre d'utilisateurs de la plateforme (à discuter comment le mesurer).

- Les graphiques n'auront que deux valeurs au démarrage prises par quinzaine semaine du 27/09 et semaine du 11/10. Si la collecte des infos est automatique et ne nécessite pas de travail manuel nous pouvons envisager une collecte bi-mensuelle, voir hebdomadaire de l'information. A discuter.

Et pour les plans d'actions nous pourrions mesurer d'un côté le nombre de collectivités utilisant la fonctionnalité plan d'actions (par exemple en commençant à compter à partir de > 5 actions et mise à jour d'au moins 1 action datant de moins de 3mois) et de l'autre le nombre d'actions inscrites aux plans d'actions

Et pour le texte : 
- "remplis à plus de 80%"
- expliciter les acronymes CAE et ECi

**Comment by Nickvalley** [comment]
Nombre d'utilisateurs = Vraies personnes avec des droits de modification sur des vraies collectivités

**Comment by maiwann** [comment]
> Je pense qu'à côté du nombre de collectivités il serait plus utile d'avoir le nombre d'utilisateurs de la plateforme (à discuter comment le mesurer).

Ok, est-ce qu'on se dit que c'est une discussion à reavoir plus tard du coup ?

**Comment by maiwann** [comment]
> Et pour les plans d'actions nous pourrions mesurer d'un côté le nombre de collectivités utilisant la fonctionnalité plan d'actions (par exemple en commençant à compter à partir de > 5 actions et mise à jour d'au moins 1 action datant de moins de 3mois) et de l'autre le nombre d'actions inscrites aux plans d'actions

Ok, est-ce que c'est un chiffre de plus à traquer qu'on rajoute dans l'autre carte ? @Nickvalley

**Comment by maiwann** [comment]
(maquette mise à jour)

**Comment by Nickvalley** [comment]
Nombre de collectivités et nombre d'utilisateurs cela me semble être la base des stats de notre plateforme à avoir en termes de vanité donc on peut dire que c'est décidé maintenant sans en rediscuter plus tard. 

Faut peut-être qu'on discute ce qui détermine un "utilisateur" pour le compter d'un point de vue numérique de façon pertinente. Y'a peut-être une norme à beta.gouv @penelopel pour les stats utilisateurs?

**Comment by Nickvalley** [comment]
> 
> 
> > Et pour les plans d'actions nous pourrions mesurer d'un côté le nombre de collectivités utilisant la fonctionnalité plan d'actions (par exemple en commençant à compter à partir de > 5 actions et mise à jour d'au moins 1 action datant de moins de 3mois) et de l'autre le nombre d'actions inscrites aux plans d'actions
> 
> Ok, est-ce que c'est un chiffre de plus à traquer qu'on rajoute dans l'autre carte ? @Nickvalley

Au final ce qui m'intéresse vraiment c'est le nombre de collectivités qui utilisent notre fonctionnalité plan d'actions comme leur outil de suivi de référence. Pour l'instant c'est "0". Donc on peut se permettre de ne pas le traquer pour l'instant en attendant de préciser comment le mesurer de façon pertinente/pérenne

**Comment by maiwann** [comment]
> Nombre de collectivités et nombre d'utilisateurs cela me semble être la base des stats de notre plateforme à avoir en termes de vanité donc on peut dire que c'est décidé maintenant sans en rediscuter plus tard.

Est-ce qu'on se dit qu'on veut suivre : 
- Le nombre d'utilisateurs inscrits sur la plateforme
- Le nombre de collectivités liées à au moins un utilisateur 

Et ça fait le taf ?

**Comment by maiwann** [comment]
> Au final ce qui m'intéresse vraiment c'est le nombre de collectivités qui utilisent notre fonctionnalité plan d'actions comme leur outil de suivi de référence. Pour l'instant c'est "0". Donc on peut se permettre de ne pas le traquer pour l'instant en attendant de préciser comment le mesurer de façon pertinente/pérenne

Ok donc pour l'instant j'enlève "Plans d'actions" de la carte et on le rajoutera plus tard

**Comment by Nickvalley** [comment]
> 
> 
> > Nombre de collectivités et nombre d'utilisateurs cela me semble être la base des stats de notre plateforme à avoir en termes de vanité donc on peut dire que c'est décidé maintenant sans en rediscuter plus tard.
> 
> Est-ce qu'on se dit qu'on veut suivre :
> 
>     * Le nombre d'utilisateurs inscrits sur la plateforme
> 
>     * Le nombre de collectivités liées à au moins un utilisateur
> 
> 
> Et ça fait le taf ?

Pour moi c'est OK pour démarrer

**Comment by maiwann** [comment]
Alors voilà la mise à jour de la page Stats : 

![Stats(2)](https://user-images.githubusercontent.com/27999224/135420855-67003323-9b63-477b-a26f-0026ea25c03a.png)
