### ISSUE TITLE
T - Afficher les actions liées aux indicateurs.

### ISSUE THREAD

**Issue by derfurth** [betagouv/territoires-en-transitions#298]
Régression suite à l'intégration, cf. IndicateurReferentielCard.svelte

- [ ] Afficher les action liées à la suite du texte de la description

![image](https://user-images.githubusercontent.com/1872471/124457273-e6f5e780-dd8b-11eb-943b-fe7fb474f468.png)

**Comment by Ynote** [comment]
C'est en cours sur la PR #235

**Comment by Ynote** [comment]
C'est en production, je me permets donc de clôre l'issue. 

cf screenshot : 

![Screenshot 2021-07-12 at 19-09-05 Ma fiche action](https://user-images.githubusercontent.com/548778/125328539-b9d5a600-e344-11eb-8661-363ad847f9eb.png)
