### ISSUE TITLE
US - Avoir une vue synthétique des indicateurs de ma collectivité dans la vue indicateurs

### ISSUE THREAD

**Issue by penelopel** [betagouv/territoires-en-transitions#313]
plus tard #669
- [x]  Pouvoir visualiser mes indicateurs selon la structure des référentiels nationaux
- [x] Afficher/Cacher les indicateurs que je n'utilise pas (aucune donnée saisie dans l'indicateur)

- [x] Je peux retrouver facilement un indicateur grâce à la fonction recherche

**Comment by maiwann** [comment]
Je propose, de la même façon que pour les actions des référentiels on peut choisir thématique/Eci/Climat-Air-Energie, on puisse choisir dans la page Indicateurs : 
- Mon plan d'actions (qui filtrerai les indicateurs selon ceux qui se trouvent dans le plan d'action, qu'ils soient remplis ou non)
- Thématique
- Eci
- Climat-Air-Energie

Et il faudrait dessous un bouton-interrupteur "Afficher uniquement les indicateurs renseignés"

**Comment by penelopel** [comment]
Retour utilisateur qui pousse à prioriser cette issue : 

"J'ai eu un échange avec ma collègue qui s'occupe du PCAET et de Citer'gie hier pour lui montrer le référentiel ECi et compléter ensemble certains indicateurs. 

Il se trouve qu'un grand nombre de ces derniers se trouve être dans le référentiel Citer'gie. Afin de ne pas perdre trop de temps de son côté comme du mien, est-il possible d'avoir un document excel reprenant tous les indicateurs demandés pour le label ECi que l'on retrouve sur la nouvelle version ? 

Cela nous permettrait de gagner du temps et de simplifier la saisie des données."

**Comment by maiwann** [comment]
TODO Maquette

**Comment by maiwann** [comment]
![image](https://user-images.githubusercontent.com/27999224/128036803-53f318a6-738e-4979-81ea-ed3d21a34aac.png)

**Comment by bertrandlalo** [comment]
@maiwann @Nickvalley  vous préférez quelle version ? 

1. Carte grisée
![v-card](https://user-images.githubusercontent.com/22340670/134351501-45bdbde9-7a2e-43e1-8c68-4f785e9aca17.jpg)

2. Onglet repliable grisé
![v-expandable-gray](https://user-images.githubusercontent.com/22340670/134351506-689b6723-93f1-471a-a6e6-3c264a6094dd.jpg)

3. Onglet repliable blanc
![v-expandable](https://user-images.githubusercontent.com/22340670/134351513-7e07359e-0fa0-4395-b892-7bb31f51b639.jpg)

**Comment by maiwann** [comment]
Je préfère la version 2, qu'on puisse replier et que les blocs soient distinguables grace à la couleur de fond 🙏
