### ISSUE TITLE
US - Naviguer plus facilement entre les mesures/orientations.

### ISSUE THREAD

**Issue by Nickvalley** [betagouv/territoires-en-transitions#323]
- [-] Créer une page par référentiel -> #332
- [x] Ajout d'un fil d'ariane en haut à gauche, qui se comporterait comme suit : 
   - Niveau 1 : "Climat-Air-Énergie" ou "Économie circulaire" permet de revenir à l'un des deux référentiels
   - Niveau 2 : Domaines ou Axes du référentiel
   - Niveau 3 : Liste des mesures du domaine ou de l'axe
- [-] ~~Remettre le bouton retour qui permet un retour direct au niveau de scroll initial sur la page précédente (Ne plus revenir sur le 1.1 du référentiel ECi à chaque fois qu'on fait "retour" pour aller sur l'axe ou sous-axe suivant mais rester dans l'arborescence précédente ?)~~ Bouton retour inutile à discuter

**Comment by maiwann** [comment]
Je rejoins la question de Clarification sous la capture d'écran, du coup pour le savoir, y a t-il des personnes qui ont remonté le besoin de circuler plus facilement entre les mesures du référentiel ?

**Comment by MartinRUAU** [comment]
Oui @maiwann c'est remonté dernièrement, navigation entre les axes et orientations pas intuitive quand tu bosses dessus!

**Comment by maiwann** [comment]
- Pouvoir aller à la mesure suivante / précédente
- Naviguer rapidement entre les mesures sans repasser par le menu

**Comment by maiwann** [comment]
Inspiration : https://cdn.dribbble.com/users/68180/screenshots/2518346/breadcrumb_dropdown.gif

**Comment by maiwann** [comment]
Mises à jour : 

- Le lien "retour" devient un fil d'ariane en haut à gauche, qui se comporterait comme [sur ce lien : ](https://cdn.dribbble.com/users/68180/screenshots/2518346/breadcrumb_dropdown.gif)

- En bas à droite de la page, avant le footer, un lien vers la mesure suivante est proposé 


![Referentiel_mesure(1)](https://user-images.githubusercontent.com/27999224/129343714-07ac6ad4-da43-4b77-988c-2050ba0f3ce6.png)

**Comment by maiwann** [comment]
>  En bas à droite de la page, avant le footer, un lien vers la mesures suivante (et précédente à discuter Ux? ) est proposé

Alors pourquoi pas, j'avais l'impression que c'était surtout pour dérouler le référentiel que les personnes naviguaient dedans, et donc logiquement plutot pour aller au suivant qu'au précédent… mais peut-être pas ?


>  Conserver le bouton retour avec retour direct à l'ancre dans le référentiel (a discuter UX) ( Ne pas revenir sur le 1.1 à chaque fois qu'on fait "retour" pour aller sur l'axe ou sous-axe suivant mais rester dans l'arborescence précédente ? )

Pour moi, cliquer dans le fil d'ariane ça te fait remonter d'un niveau en arrière, comme si c'était le bouton retour. Et c'est cliquer sur *la petite flèche* du fil qui déroule toutes les possibilités. 
- Je clique sur CAE je retourne à la page du référentiel
- Je clique sur la flèche à coté de CAE, on me propose les 3 référentiels (ECi, thématiques, CAE)
Et ça nous évite d'avoir en plus un bouton retour, même si il faudra vérifier si les personnes l'utiliseront
