### ISSUE TITLE
Suppression doublons de comptes primo-utilisateurs

### ISSUE THREAD

**Issue by Nickvalley** [betagouv/territoires-en-transitions#329]
- Supprimer les comptes en doublon des primo-utilisateurs ayant aussi un compte DTECI sans plan d'actions sur le compte primo-utilisateur
- Fusionner les comptes primo-utilisateurs/DTECI ayant également un plan d'actions

- [x] identifier les doublons et si besoin de  fusionner (x vers y) ou supprimer @Nickvalley 
- [ ] faire les requête sql pour transférer les données d'un compte vers l'autre (si nécessaire) puis supprimer les comptes en doublons @derfurth 

# Nettoyage des comptes en doublon : 
---

## Nota
Pour les comptes avec le même nom, vérification d'ID à faire en base pour distinguer les comptes

## // Primo-utilisatrices à 2 collectivités //
- Saint-Louis 3 comptes: 
    - [x] Compte DTECI : CA Saint-Louis Agglomération en doublon à supprimer : a1yjrAVNRSelASYfa7A7Sw (Vide aussi mais à conserver pour garder un compte sur les 3)
    - [x]  a1yjrAVNRSelASYfa7A7Sw conservé
    - [x] Compte TeT : CA Saint-Louis Agglomération : Idem vide à supprimer car doublon ```ID = saint_louis_agglo```
- Cyclad : 
    - Compte DTECI : Cyclad
        - Référentiel renseigné à conserver
    - Compte TeT : Cyclad ```ID = cyclad```
        - [x] Plan d'actions à transférer de ```ID = cyclad``` à l'autre compte Cyclad ```ID = bCf5BMSgROSI95SVPLxaLQ```
        - [x] puis supprimer le compte en doublon ```ID = cyclad```
- Coeur du Var : 
    - Compte DTECI : Communauté de Commune Coeur du Var : 
        - Référentiel renseigné à conserver
    - [x] Compte TeT : CC Coeur du Var vierge à supprimer ```epci_id=coeur_var```
- CC Touraine Vallée de l'Indre
    - Compte DTECI : CC Touraine Vallée de l'Indre 
        - Référentiel renseigné à conserver (axe 1 : 2,6%)
    - [ ] Compte DTECI : CC Touraine Vallée de l'Indre vierge et axe 1 à 0% --> Supprimer ```epci_id=LVY_RUD5TF6xF8CifHJAXA```
    - [ ] Compte TeT : CC Touraine Vallée de l'Indre - vierge à supprimer ```epci_id=touraine_indre```
- CC Terres du Haut Berry
    - Compte DTECI : CC Terres du Haut Berry ```epci_id=dTzEc7JiS8ODR-Aapdq0JA```
        - Référentiel renseigné à conserver
    - Compte TeT : CC Terres du Haut Berry
        - [ ] Début de saisie d'un plan d'actions à transférer de ```epci_id=terres_haut_berry``` vers ```epci_id=dTzEc7JiS8ODR-Aapdq0JA```
        - [ ] Puis supprimer ```epci_id=terres_haut_berry```
- CC Piémont Cévenol
    - [ ] Compte DTECI :Communauté de communes du Piémont Cévenol Vierge à supprimer ```epci_id=DLqG7DdGQ9KGCEetxTSKGw```
    - Compte TeT : CC Piémont Cévenol ```epci_id=piemont_cevenol```
        - Début de saisie d'un plan d'actions et référentiel à conserver
- CA Pays Voironnais
    - Compte DTECI : CA du Pays Voironnais ```epci_id=KfxbeRrZS0uJiQU8yYOodg```
        - Référentiel renseigné à conserver
    - Compte TeT :CC Pays Voironnais
        - [ ] Début de saisie d'un plan d'actions à transférer de ```epci_id=pays_voironnais``` vers : ```epci_id=KfxbeRrZS0uJiQU8yYOodg```
        - [ ] Puis supprimer ```epci_id=pays_voironnais```
- CA Bourges Plus : supprimer le compte primo utilisateur TeT vierge : ```epci_id=bourges_plus```
- [ ] CC Sundgau :  Supprimer le compte primo-utilisateur vierge epci_id=sundgau

## Doublons de DTECI

- [ ] CU Dunkerque : Supprimer le doublon vierge : ```epci_id=97de0fb8-ffa1-46da-86b6-c4ff21db758a```
- Cap excellence (deux utilisateurs différents?)
    - CA CAP Excellence : 7 orientations renseignées (1.1, 21, 22 23 25 35 36) A conserver
    - cap excellence : 6 orientations renseignées
        - [x] 4.3 renseignée en plus (transférer la saisie en manuel en fait de 432 4341 4342)
        - [ ] Puis supprimer le compte ```epci_id=A286jJSlQ2yxfR0WNtw21w```
- Rennes Métropole
    - [ ] Rennes Métropole : - 1 orientation de saisie --> Supprimer ```epci_id=BvqvwkOXRLKGdi8ymdnQRA```
    - Rennes Métropole  
        - 10 orientations de saisies --> conserver
- Simer
    - [ ] SIMER : Vierge --> Supprimer ```epci_id=WMjcRDo0RMyDPyntkbanNg```
    - SIMER : 
        - 13 orientations de saisies --> Conserver
- Intercom de la Vire au Noireau
    - Intercom de la Vire au Noireau : 
        - score axe 1 26% : conserver 
    - [ ] Intercom de la Vire au Noireau : vierge supprimer ```epci_id=EUHkM7zkQ_KikcWG2rjBzQ```
- Lille
    - Lille : Axe 1 1,3% 
        - conserver
    - Métropole européenne de Lille : 
        - Pas la même collectivité : conserver
- SIVOM de Mortain - Le Neufbourg
    - [ ] SIVOM de Mortain - Le Neufbourg : vierge supprimer ```epci_id=JeKXs-LjRK6uN_KuaHWk0w```
    - SIVOM de Mortain - Le Neufbourg : 
        - Axe 1 à 36,6 % compte de test de Cyril ADOUE à supprimer
- CC Les Balcons du Dauphiné
    - [ ] CC Les Balcons du Dauphiné : axe 1 : 6,6% à supprimer ```epci_id=XSCGG0Y6ReqJPVn3V_6SgA```
    - Communauté de communes des Balcons du Dauphiné
        - axe 1 à 7,7% 2 orientations saisies à conserver
- Métropole du grand Paris
    - [ ] Métropole du Grand Paris : Référentiel vierge supprimer ```epci_id=QSrkfvUCTd-6pPucZo90hQ```
    - Métropole du Grand Paris : 
        - Axe 1 11,9% : conserver
- Grand Avignon
    - Communauté d'Agglomération du Grand Avignon : 
        - Axe 11,2% conserver
    - [ ] Grand Avignon : Axe 1 2,6% supprimer (1.1 renseignée uniquement) ```epci_id=eR55PXl0SWSls3CUtzHfKQ```
- CC Territoriale Sud-Luberon
    - CC Territoriale Sud-Luberon : axe 1 pas à 0 conserver (2 orientations saisies)
    - CC Territoriale Sud-Luberon : 
        - [x] Reprendre à la main 2.3.1.1 en faite 
        - [ ] Puis supprimer ```epci_id=Uvr0-EcxQSqNyB8el3Tjvw```
- CA d'Epinal
    - [ ] CA d'Epinal : Axe 1 à 2,6 % supprimer ```epci_id=CDtBVN48Rjy1JOio5h08sw```
    - CA d'Epinal : Axe 1 à 20,1 % conserver
- Caux Seine Agglo
   - doublon ```epci_id=90b57065-734d-442f-b254-7836a42f5396 vierge à supprimer ```

**Comment by bertrandlalo** [comment]
EPCI avec doublons non-mentionnées : 
- **Communauté d'Agglomération du Centre Littoral** : supprimer `f29e105d-06e2-469e-81e3-b8cd3a17c303` ; garder `PYka30ERS9iz1aN-9FdJzw` 
- **Haut-Bugey Agglomération** : supprimer `d03f8fae-1df5-4e5c-b8b3-4582b5f3508c` ; garder `NJbUlsWKQNSyXG0k8curWQ` 
- **SMDO** : supprimer `smdo` ; garder `NwcEIPmNQk2S4T6XLegaKw`


[duplicated_epci_and_actionstatus_count.csv](https://github.com/betagouv/territoires-en-transitions/files/6801630/duplicated_epci_and_actionstatus_count.csv)
