### ISSUE TITLE
T - Amélioration vue référentiels

### ISSUE THREAD

**Issue by Nickvalley** [betagouv/territoires-en-transitions#332]
- [x] une page par référentiel
- [x] Plier les axes du référentiel ECi de la même façon que le référentiel citergie.
- [x] Indenter les sous-domaines Citergie / orientations économie circulaire
- [x] Placer le score à droite du titre de l'axe pour qu'il soit visible à côté du titre lorsqu'il est plié et ne prenne pas trop de place [titre | chevron | score aligné à droite]

--------------------

- Par défaut lorsque l'on entre sur un référentiel celui-ci doit être plié sur les 6 Domaines (CAE) ou 5 Axes (ECi) pour permettre de donner une vue d'ensemble permettant de voir le score réalisé et programmé (% et nombre de points possibles par domaine/axe et global en un coup d'oeil). 

- Lorsque l'on clique sur un domaine/axe, celui-ci se déplie jusqu'aux mesures (CAE) ou aux orientations (ECi) avec le même affichage synthétique des scores que pour les domaines

Cf. affichage de synthèse actuel de l'EMT qu'il s'agit de rendre plus lisible et visuel ![image](https://user-images.githubusercontent.com/67585509/125222909-290eb400-e2cb-11eb-8551-b1ebd57dfca8.png)

**Comment by maiwann** [comment]
Ca c'est un terrain qu'on avait démarré avec @newick ! Du coup pas de souci, mais est-ce qu'il faut que je reprenne de 0 avec quelqu'un qui est là pendant ce sprint, ou est-ce qu'on attends le retour de @newick ?

**Comment by Nickvalley** [comment]
@maiwann j'ai ajouté dans la description de cette US la mini-fonction suivante car cela fait plusieurs fois que l'on nous fait la remarque et que je me dis que cela va vraiment de pair avec cette US sur la fonctionnalité de navigation plus aisée  dans les pages qui sont longues : 
 *+ disposer d'un moyen rapide de revenir au haut de page quand on a déroulé tout l'axe (fonctionnalité utile pour les référentiels dépliés, les plans d'actions dépliés et les indicateurs dépliés.* 

A voir ce qu'on peut proposer de sympa et ergonomique là dessus.)

**Comment by maiwann** [comment]
@Nickvalley Pour la demande de remonter rapidement en haut, j'aurai besoin de me rendre compte du contexte des personnes… Est-ce que ça peut rester à part, et faire l'objet d'une autre carte ?

**Comment by Nickvalley** [comment]
> 
> 
> @Nickvalley Pour la demande de remonter rapidement en haut, j'aurai besoin de me rendre compte du contexte des personnes… Est-ce que ça peut rester à part, et faire l'objet d'une autre carte ?

OK j'ai créé une carte et mis à jour la description #606

**Comment by maiwann** [comment]
![Referentiel_tout](https://user-images.githubusercontent.com/27999224/129344817-c2f1ba21-5453-4b22-b0b8-e16905accd03.png)

**Comment by maiwann** [comment]
@Nickvalley On a pairé avec Raphaëlle et voilà où on en est :
![screen-gauge](https://user-images.githubusercontent.com/27999224/133445722-81a12097-24fb-4258-b869-3d2b2b6d9b51.jpg)

C'est joli *mais* il n'y a pas les nombres de points pour ces niveaux… Est-ce que ça manque ou est-ce qu'on peut s'en passer ? 😬
