### ISSUE TITLE
T - Corriger le pourcentage des actions réglementaire pour eci

### ISSUE THREAD

**Issue by Nickvalley** [betagouv/territoires-en-transitions#335]
- [ ] 210, 220, 230, 410 les actions réglementaires qui valent 0 points restent à 0% lorsqu’elles sont en statut "faite" alors qu'elle doivent s'afficher à 100%

**Comment by derfurth** [comment]
@Nickvalley voir https://github.com/betagouv/territoires-en-transitions/blob/main/referentiels/data/table_correspondance.json
