### ISSUE TITLE
Après m'être déconnecté de l'app. je peux revenir en mode connecté sans repasser par la connexion via le keycloack

### ISSUE THREAD

**Issue by Nickvalley** [betagouv/territoires-en-transitions#351]
- 1/ Je suis sur app. en mode connecté. 
- 2/ Je me déconnecte
- 3/ Je prends l'url https://app.territoiresentransitions.fr/epcis/ dans mon historique de navigation et hop je suis à nouveau connecté sans être passé par le keycloack de l'ADEME 

Visiblement le bouton "déconnecter" n'a pas vraiment d'action de déconnexion sur le keycloack.

**Comment by Ynote** [comment]
L'url https://app.territoiresentransitions.fr/epcis/ est actuellement accessible en mode lecture même lorsque l'on est déconnecté. Le cas décrit ci-dessus ne décrit un problème de connexion. Il faudrait améliorer l'accès aux pages en tant que personne connectée. 

À rediscuter ensemble au moment où on traitera cette carte.
