### ISSUE TITLE
Remarques sur l'intégration du Design System pour Maïwann (sorties du sprint du 05/07)

### ISSUE THREAD

**Issue by Nickvalley** [betagouv/territoires-en-transitions#352]
@maiwann : Tâches à redécouper en cartes distinctes en prévision du sprint du 02/08

-  [x] l'affichage des actions des référentiels est trop "large en hauteur (je sais pas trop comment dire, peut-être trop de marges)) " donc il faut énormément scroller pour pouvoir balayer le référentiel. Designer des blocs plus étroits
   - Supprimer les mentions "Cit'ergie" et économie-circulaire dans les vues par référentiels
      - Supprimer la flèche bleue en bas à droite de chaque bloc étant donné que tout le bloc est cliquable

  -  [x] Remplacer le bouton "Créer une fiche action" par "Ajouter à mes actions" (solution plus explicite et plus courte -1 caractère)

## Indicateurs

  -  [x] Le fait que les champs à déplier aient un titre tout à gauche et un bouton "+" tout à droite donne l'impression qu'il faut cliquer sur le plus pour interagir ce serait plus intuitif d'avoir un bloc unique bien délimité pour chaque item que l'on peut déplier

  -  [x] On pourrait avoir un crayon plutôt qu'un gros bouton "modifier"? (A moins que ce ne soit pas, Ux friendly?) --> C'est pas méga explicite mais en même temps c'est une action qu'ils feront quasi jamais, donc ça se teste !

**Comment by maiwann** [comment]
3/4 sont déjà faites, et une carte existe pour ce qui reste #332
