### ISSUE TITLE
Affichage de la page création de compte

### ISSUE THREAD

**Issue by derfurth** [betagouv/territoires-en-transitions#372]
Affichage en se rendant directement sur https://app.territoiresentransitions.fr/auth/register/
![image](https://user-images.githubusercontent.com/1872471/125062907-30f20c80-e0af-11eb-9898-a0ff67f8d059.png)

Affichage en passant par le root et en cliquant sur créer un compte
![image](https://user-images.githubusercontent.com/1872471/125063120-64349b80-e0af-11eb-9807-01f9a6b29665.png)

**Comment by Ynote** [comment]
C'est possiblement lié à https://github.com/sveltejs/sapper/issues/1572
