### ISSUE TITLE
Suivi des contacts conseillers et collectivités (à reprendre dans le CRM?)

### ISSUE THREAD

**Issue by Nickvalley** [betagouv/territoires-en-transitions#381]
=>En attente version finale CRM //  En attente arrivée chargé-e de déploiement
Conseillers interrogés : 
- [ ] Catherine BOSSIS
- [x] Sébastien DENIS
- [ ] Grégory GARNIER
- [ ] Etienne GHEWY (en contact avec l'expérimentation Cit'ergie Start en BFC)
- [x] Élodie HOUGUET
- [ ] Thibault LAVILLE
- [x] Jean LEROY
- [x] Jean-Luc MANCEAU
- [x] Carole PIEDVACHE
- [x] Géraldine ROUSSELLE
- [ ] Emmanuel VERLINDEN
- [x] Loïc LEPAGE
- [ ] Linda LESCUYER
- [ ] Anaïs LE DORE
- [ ] Pascaline COUSIN

- [ ] Marie-Luce SAILLARD
- [ ] Michaël TOMA

Voir les collectivités avec Camille

**Comment by Emelinejy** [comment]
Contacts dans Notion + Airtable
