### ISSUE TITLE
T - Je veux pouvoir retirer une collectivité de mon compte utilisateur

### ISSUE THREAD

**Issue by Nickvalley** [betagouv/territoires-en-transitions#386]
Pouvoir retirer une collectivité que l'on a ajoutée à son compte utilisateur

Proposition : Bouton "-" sur la carte avec pop-up qui demande "Souhaitez vous vraiment retirer cette collectivité de votre liste" Confirmer/Annuler

**Comment by maiwann** [comment]
Plutot pour une icône "Poubelle" en haut à droite, et avec la double confirmation bien sur :D

**Comment by penelopel** [comment]
Juste pour l'orthographe - "Souhaitez-vous vraiment retirer cette collectivité de votre liste ?"

@maiwann on la met où la poubelle exactement ?

**Comment by maiwann** [comment]
![Capture d’écran 2021-07-27 à 14 13 21](https://user-images.githubusercontent.com/27999224/127151844-8ad8f96f-d5fa-4681-9ac0-a3e700dd4a65.png)

Par ici ! Je fais une maquette à mon retour si c'est plus simple :)

**Comment by maiwann** [comment]
![Capture d’écran 2021-08-02 à 12 02 11](https://user-images.githubusercontent.com/27999224/127843934-16481b5a-aba1-48a2-a859-e4b094dcb342.png)
