### ISSUE TITLE
SYBERT en triplon

### ISSUE THREAD

**Issue by MartinRUAU** [betagouv/territoires-en-transitions#410]
- [x] Identifier le compte avec données de la V2.2
- [x] Supprimer les 2 comptes en trop 
- [x] Soit remplacer sa collectivité avec les bonnes données, soit lui dire de sélectionner après suppression des triplons la bonne collectivité dans la liste

**Comment by derfurth** [comment]
Import fait et mail envoyé !

**Comment by MartinRUAU** [comment]
Parfait!! 💯
