### ISSUE TITLE
TT - Je veux pouvoir renseigner des indicateurs en dehors de la plage 2016-2022

### ISSUE THREAD

**Issue by Nickvalley** [betagouv/territoires-en-transitions#43]
- [ ] Les indicateurs doivent pouvoir être renseignés en dehors de la plage 2016-2022 : de 2008 à 2020 pour l'année 2021
- [ ] L'année maximale de saisie des indicateurs de réalisation correspond à l'année N-1 de l'année en cours (année N). Ex: en 2021 = 2020

**Comment by maiwann** [comment]
Résumé des entretiens : Les différentes plages des personnes sont : 

2020 - 2024
2016 - …
(2016) 2022-2028
2019 - 2026
2020 - 2026

Il y a un intérêt à ne pas "juste" respecter ces plages pour pouvoir avoir de l'historique sur les indicateurs. Du coup, je vais proposer un format qui comporterait plus d'années, mais au sein de laquelle les personnes pourront scroller…

**Comment by Nickvalley** [comment]
+ 1 retour 2012-2026 sachant que toutes les plages de données souhaitées dans le futur sont pour saisir des objectifs et pas des résultats

**Comment by maiwann** [comment]
Coté maquettes, j'ai choisi de faire un slider pour voir les différentes dates.

La question me semble donc : Quelle est la première année qu'on propose ? 2000 ? 2005 ? Y a-t-il des données que les collectivités ont qui remontent jusque là @MartinRUAU ?

**Comment by maiwann** [comment]
![image](https://user-images.githubusercontent.com/27999224/126173615-50e7edb1-ff27-49d0-a320-98b96ceb4307.png)

**Comment by maiwann** [comment]
D'après @MartinRUAU Cit'ergie ça débute en 2008 donc on a qu'à mettre ça !

**Comment by maiwann** [comment]
Mise à jour de la maquette : Le composant Indicateur change, et se déplie / replie, version repliée en hait, version dépliée en dessous
![image](https://user-images.githubusercontent.com/27999224/126613216-51653fc0-c333-41ac-bec7-1341b59364ca.png)

Pour les années, on a un slider qui permet de circuler dedans grâce aux flèches à droite et gauche
