### ISSUE TITLE
T - Bug d'affichage des description quand on veut lier une fiche action d'un référentiel

### ISSUE THREAD

**Issue by bertrandlalo** [betagouv/territoires-en-transitions#434]
![bug-affichage-fiches-editions](https://user-images.githubusercontent.com/22340670/127000612-04d0237d-d821-4986-8778-00fff3a5ec43.jpg)

@maiwann, on est d'accord que ce n'est pas l'affichage voulu ?

**Comment by maiwann** [comment]
On est d'accord ! Les paragraphes devraient être les uns sous les autres plutot ^^'
