### ISSUE TITLE
T - Validation des indicateurs

### ISSUE THREAD

**Issue by MartinRUAU** [betagouv/territoires-en-transitions#44]
- [ ] Lorsque je saisi un caractère non autorisé, l'application me dit que la valeur est enregistrée alors qu'elle devrait me dire que l'information saisie ne correspond pas au format attendu (nombre)

**Comment by Ynote** [comment]
Il faudrait caractériser les indicateurs sur lesquels il faut une validation pour pouvoir avancer sur le sujet. 

Par ailleurs, on pourrait également caractériser le fait qu'une valeur invalide ne soit pas bloquante ?

**Comment by derfurth** [comment]
On devra déterminer comment définir des contraintes sur les indicateurs à partir des markdowns 
ex valeur maximale
