### ISSUE TITLE
TT - Corriger des incohérences de comportement et de contenu

### ISSUE THREAD

**Issue by derfurth** [betagouv/territoires-en-transitions#451]
Liste des petits fix à corriger :

**#Header** 
- [x] Mettre "Se connecter" sur une ligne dans le header (s'affiche toujours sur 2 lignes) 

**#Accueil** 
- [x] Ajouter une collectivité existante : Mettre les collectivités dans l'ordre alphabétique car les nouvelles collectivités créées ne sont pas classées dans l'ordre alphabétique mais se rajoutent à la fin de la liste

**#Référentiels**
- [x] Remplacer "cit'ergie" par climat-air-énergie dans le référentiel climat-air-énergie
- [x] Remplacer le texte du bouton "Valider" par "Ajouter" quand on ajoute une collectivité à sa liste.
- [x] Harmoniser la numérotation des référentiels avec des points partout : "1." dans climat-air-énergie" alors que "1"(sans point) dans "économie-circulaire". Ajouter les points dans économie circulaire.
- [x] A l'intérieur d'une mesure/orientation : Afficher les numéros des actions sur la même ligne que le titre de l'action

**#Plan d'actions**
- [x]  "sans categorie" à renommer par "Fiches actions non classées" et les mettre à la fin
- [x] Le statut de la fiche action a perdu son style (comparer avec les maquettes)
- [x] Les filtres ne fonctionnent pas (si on filtre on n'obtient pas le bon résultat et si on renlève le filtre on ne retrouve pas les informations d'origine sans le filtre)

**#Ajout d'une fiche action**
- [x] Ajouter un bouton "Retour" pour abandonner la création d'une nouvelle fiche [si le fix est simple prévoir l'ajout d'un message de validation s'il y a des informations qui ont déjà été saisies "Les informations que vous avez commencé à renseigner seront perdues si vous n'enregistrez pas cette nouvelle fiche-action, souhaitez-vous poursuivre?"]
- [x]  Dans le formulaire, les champs (Titre en particulier) devraient être plus longs pour permettre de lire l'intégralité du contenu lorsqu'il est plus long (de façon générique proposition de fix rapide en mettant tous les champs texte (Titre, Catégorie, Structure pilote, Personne référente, Élu référent et Partenaires) à la même largeur que les champs Description et Commentaire
- [x] Quand on lie une action du référentiel à une fiche action, le clic en dehors de la modale doit permettre de fermer celle-ci
- [x] Remplacer le bouton "Valider" par "Enregistrer" (Uniformiser les boutons d'enregistrement en utilisant toujours "Enregistrer" plutôt que "Valider"
- [x] - [ ] "Valider" à renommer en "Enregistrer" sur le bouton de création de la fiche et d'ajout d'un axe de la structure du référentiel (catégorie)

- [x] Mettre en place un feedback qui confirme l'Enregistrement d'une information après avoir cliqué sur un des boutons "Enregistrer" dans l'application

#Tickets à part :
- [x] Bugs de styles des titres & co => cf ticket #503 
- [x] Ergonomie de l'application : Supprimer les boutons d'enregistrement sur les commentaires et rendre les champs réactifs pour symboliser l’enregistrement de l'information à la sortie du champ (+ avertissement si jamais on quitte la page en étant sur un champ de saisie actif sur lequel on a fait des modifications)

#Fix déjà résolus : 
- [x] Quand l'EPCI ID n'est plus dans l'URL, rediriger vers l'accueil (--> Résolu par la migration React?)
- [x] Indicateurs => Les chiffres ne sont pas enregistrés !! déjà fixé
- [x] Impression que c'est lent à l'affichage  (--> Résolu par la migration React)

---
- [x] Identifier en pair les petites incohérences
- [x] Déterminer la passe de fix
- [x] Fixer les incohérences cf. checklist synthétique en début de Commentaire

**Comment by bertrandlalo** [comment]
Petits trucs à faire : 
- [ ] cit'ergie => climat air énergie

**Comment by Nickvalley** [comment]
En complément: 
- [ ] Le non concerné ne s'affiche pas correctement sur les statuts (cf screen.) (cas 1: bouton actif mais statut à 0% ; cas 2: statut non concerné mais le bouton non concerné n'est pas actif)
![image](https://user-images.githubusercontent.com/67585509/128468137-866a179a-8843-46d1-a2a9-264dfa727fca.png)

- [ ] Le statut "Faite" n'est parfois pas pris en compte lorsque l'on change les statuts (cf. vidéo)
https://user-images.githubusercontent.com/67585509/128468210-13dee402-df7b-4e95-83e8-50c00da2e8bb.mp4

**Comment by Nickvalley** [comment]
- [ ] Plan d'actions les filtres ne fonctionnent pas (si on filtre pas le bon résultat et si on enlève le filtre on ne retrouve pas les informations)

**Comment by penelopel** [comment]
- [ ] Mettre "Se connecter" sur une ligne (c'est toujours sur 2 lignes) 
![image](https://user-images.githubusercontent.com/5320547/128516403-b16587b6-e9ae-4998-8e8b-f588dfb681cb.png)

- [ ] Réparer le bouton de création de compte de la page de création de compte pour qu'il ait une taille normale 
https://app.territoiresentransitions.fr/auth/register/
![image](https://user-images.githubusercontent.com/5320547/128516530-e3632bf5-b807-4ee5-a2aa-05876d006ee3.png)

**Comment by Nickvalley** [comment]
Quand on clique sur "Non concerné" le score reste à 0% et n'affiche pas "Non concerné" 
![image](https://user-images.githubusercontent.com/67585509/128833828-bb1b57a2-6535-408e-889e-cd3e51928c64.png)

**Comment by Nickvalley** [comment]
Le numéro des actions du référentiels ne s'affiche pas sur la même ligne que le titre de l'action

![image](https://user-images.githubusercontent.com/67585509/128833970-f9c2ce16-0809-4352-8bcf-ca164a438d04.png)
![image](https://user-images.githubusercontent.com/67585509/128834202-ba1a196a-849b-45c8-a5be-a5940e5fd167.png)

**Comment by maiwann** [comment]
Pour la dernière c'est normal @Nickvalley ! C'était pour gagner de la place tout en conservant l'info, et j'ai un peu anticipé si on avait d'autres infos mineures (type Base/MeO/Effet) à caler, je les mettrait à coté. Peut-être c'est trop anticipé ?

**Comment by maiwann** [comment]
- [ ] Avoir un header plus court : Au clic sur "Nom de collectivité" une petite liste déroulante propose "Changer de collectivité" ou "Déconnexion"
![image](https://user-images.githubusercontent.com/27999224/129030723-6e90f624-b87e-440f-a4a9-591e509bb2dd.png)

**Comment by Nickvalley** [comment]
> Pour la dernière c'est normal @Nickvalley ! C'était pour gagner de la place tout en conservant l'info, et j'ai un peu anticipé si on avait d'autres infos mineures (type Base/MeO/Effet) à caler, je les mettrait à coté. Peut-être c'est trop anticipé ?

Le numéro de l'action est directement lié au titre donc c'est quand même beaucoup plus lisible s'ils sont accolés sur une même ligne. Les autres infos à caler on peut les mettre après elles sont liées à la description ou caractérisation de l'action (Base/MeO/Effet c'est plutôt des informations qu'on peut afficher sous forme de boutons de "tagging" comme les labels sur github)

**Comment by Nickvalley** [comment]
> 
> 
>     * [ ]  Avoir un header plus court : Au clic sur "Nom de collectivité" une petite liste déroulante propose "Changer de collectivité" ou "Déconnexion"
>       ![image](https://user-images.githubusercontent.com/27999224/129030723-6e90f624-b87e-440f-a4a9-591e509bb2dd.png)

Je ne suis pas favorable à cette évolution en l'état pour l'instant car : 
- Cela ne résoud pas la place car il faudrait l'illustrer avec un vrai nom long de collectivité (ex. "SM départemental d'études et de traitement des déchets ménagers et assimilés de Vendée (TRIVALIS)" ) en attendant qu'on formate les noms court et qu'on connaisse la longueur max. de ces "noms courts" 
- cela crée une confusion entre le profil utilisateur (statique) qui est connecté et la navigation (dynamique) dans l'outil tout particulièrement s'il va consulter un autre compte ou change de compte car il en gère plusieurs (ex. conseiller Cit'ergie). Je préfère que l'on conserve en haut à droite le bouton pour gérer le profil et la déconnexion uniquement et qu'on dissocie la navigation.
 
![image](https://user-images.githubusercontent.com/67585509/129760722-61dc23b2-7368-4fce-a8d7-c94a805879f5.png)

**Comment by maiwann** [comment]
> Le numéro de l'action est directement lié au titre donc c'est quand même beaucoup plus lisible s'ils sont accolés sur une même ligne. Les autres infos à caler on peut les mettre après elles sont liées à la description ou caractérisation de l'action (Base/MeO/Effet c'est plutôt des informations qu'on peut afficher sous forme de boutons de "tagging" comme les labels sur github)

OK du coup on peut faire cette modification :)

**Comment by maiwann** [comment]
> Je ne suis pas favorable à cette évolution en l'état pour l'instant car :

Ok alors je met une carte pour qu'on ai une discussion sur la navigation du header :)

**Comment by penelopel** [comment]
Tout est bon pour moi ! 

Petit ajout : 

- [ ] Supprimer la collectivité sans nom qui bug quand on appuie sur les boutons et est en premier sur la liste
![image](https://user-images.githubusercontent.com/5320547/131538349-fbda56a0-8a54-495f-b3a0-f9b1c5a42cb3.png)

**Comment by Nickvalley** [comment]
Incohérences de comportement fixées 💪 🎉
