### ISSUE TITLE
US - Afficher le niveau de labellisation actuel

### ISSUE THREAD

**Issue by Nickvalley** [betagouv/territoires-en-transitions#453]
Pour chaque collectivité, afficher en haut du tableau de bord (au dessus de la vue courante existante actuellement): 

# Niveau de labellisation obtenu : 
- [x] le niveau de labellisation obtenu par la collectivité sur économie circulaire (saisie via retool) 
   - [x] 0 à 5 étoiles
   - [x] Score global réalisé
   - [x] Score global programmé
   - [x] Date de labellisation ?
- [x] le niveau de labellisation obtenu par la collectivité sur climat-air-énergie (saisie via retool 0 à 5 étoiles)
   - [x] 0 à 5 étoiles
   - [x] Score global réalisé
   - [x] Score global programmé
   - [x] Date de labellisation ?
   
- [x] FRONT : afficher la labellisation dans l'application. Condition affichage du score : Pour 0 étoile et 1 étoile - Ne pas afficher le score réalisé et programmé (car absence de score reconnu par audit) @marc-rutkowski 

- [x] Le métier peut mettre à jour ces infos sur le retool. 

Maquettes : https://www.figma.com/file/YhEoPD2YxqHuEaPn8nKWql/Maquettes-2k22?node-id=187%3A14865

Données Excel avec niveau de label / date de labellisation / % réalisé / % programmé (chaque labellisation) :
[Labellisation CAE-ECi.xlsx](https://github.com/betagouv/territoires-en-transitions/files/8170059/Labellisation.CAE-ECi.xlsx)

**Comment by maiwann** [comment]
J'ai 2 propositions, laquelle préférez-vous ?

Étoiles à coté VS en dessous

![Screenshot 2021-09-22 at 17-55-33 Territoires en Transitions](https://user-images.githubusercontent.com/27999224/134378758-3237a34f-7ba8-45c6-9fce-dd89c292b8fc.png)
![Screenshot 2021-09-22 at 17-55-27 Territoires en Transitions](https://user-images.githubusercontent.com/27999224/134378763-5a0ff0a1-d86a-4928-83a9-34198a48c12e.png)

(moi j'ai une légère préférence pour en-dessous, mais ça reste léger…)

**Comment by maiwann** [comment]
Et pour afficher le niveau de labellisation, je propose : 
![Screenshot 2021-09-22 at 18-26-14 Territoires en Transitions](https://user-images.githubusercontent.com/27999224/134383761-2b164dc1-02d5-4b4d-94c6-20fcc75268eb.png)

Et derrière "Demander la labellisation" pour l'instant on pourrait seulement mettre une modale avec la marche à suivre, et étoffer pour la suite ?

mais il me faudrait : 
- 1 phrase pour chaque niveau de labellisation

**Comment by maiwann** [comment]
Plus près du score

> Votre score vous permet d'atteindre la X étoile

**Comment by maiwann** [comment]
@Nickvalley Préciser les niveaux pour avoir de 1 à 5 étoiles

**Comment by cami-na** [comment]
### Visualiser la progression dans le parcours de labellisation

En tant que personne référente d’une collectivité, je veux visualiser la progression de ma collectivité dans le parcours de labellisation afin de me projeter dans les prochaines étapes à effectuer 

**Infos métier** 

Pour les référentiels CAE et ECi

Conditions pour candidater aux différents niveaux de labellisation 
- Première étoile : cf [checklist](https://www.figma.com/file/88b79ioNG1wTm8z6CKM59I/Archives?node-id=377%3A31318) 
- Deuxième étoile : 35% des actions réalisées
- Troisième étoile : 50%
- Quatrième étoile : 65%
- Cinquième étoile : 75%

Types de scores
_Comment sont-ils calculés ? par rapport au nombre d'actions ou de points par action ?_
- Score réalisé 
- Score programmé 
- Score labellisé : c’est le score réalisé validé par l’audit et la commission de labellisation

**Critères d’acceptation**

Présenter sur le tableau de bord :
- Niveau actuel de labellisation et objectif (à ajouter dans un 2e temps : Prochaines étapes)
- Chiffres clés : indicateurs remplis (%), nombre de points, score réalisé (%), score programmé (%)
- Barre de progression des différents niveaux avec traduction visuelle du score réalisé et du score programmé

_Rappel à présenter aussi au niveau de l’action ?_

[Proposition de maquette ](https://www.figma.com/file/YhEoPD2YxqHuEaPn8nKWql/Maquettes-2k22?node-id=187%3A14865)
