### ISSUE TITLE
US - Évolution de la vue de synthèse/accueil pour une collectivité

### ISSUE THREAD

**Issue by penelopel** [betagouv/territoires-en-transitions#457]
- [x] Jauge d'avancement pour ECI, CAE
- [x]  Plan d'action 
- [x] #675
- [x] Liens --> issue #676

**Comment by maiwann** [comment]
- Avancement de mon plan d'actions
- Score par domaine / axe pour chaque référentiel

**Comment by penelopel** [comment]
@maiwann après consultation du design initial il y a un certain nombre de points qui n'ont pas été bien intégrés, notamment les boutons en bleu et la barre bleue pour ses collectivités. Ca vaut le coup de le remettre non ? 

Design initial : 
![image](https://user-images.githubusercontent.com/5320547/128518505-0237184a-4b21-4f7a-a8ca-61ebb28153d7.png)

Design actuel : 
![image](https://user-images.githubusercontent.com/5320547/128518669-02506ac8-f900-4083-b470-a46c10ef4beb.png)

Par ailleurs, et ça vaut pour cette page et toutes les autres, sais-tu pourquoi on a mis le fond en bleu clair plutôt que blanc ? Ne devrait-on pas mettre un fond par défaut blanc comme dans tes design ?

**Comment by maiwann** [comment]
@penelopel Yes mais je pense que cette issue va transformer de toute façon cette vue donc ça va bouger.
Pour le fond, +1 pour passer sur le fond blanc (ce n'est pas un effet calculé de ma part) je fais une carte pour ça

**Comment by MartinRUAU** [comment]
Top top cette maquette, ça donne envie :) ! Juste pour les plans d'actions, il faudrait que la légende "texte" corresponde aux couleurs de la progression dans la barre, ce serait bien plus clair! Avec le bouton "nouveau", ca fait le lien avec la #68 ! Ah oui et il faudra penser à la légende soit au pluriel, soit au singulier (dans le cas 0 ou 1 action)

**Comment by maiwann** [comment]
Alors le souci avec les couleurs c'est que c'est pas possible, les contrastes ne seraient pas suffisant pour les minimum nécessaires (pour le vert foncé ça passerait mais pas pour le vert clair et le gris :( )

**Comment by Nickvalley** [comment]
C'est super.

**Nombre de plans d'actions :** Je pense qu'on n'aura pas plus de 3 plans d'actions par collectivité avant un certain temps (selon mon intuition, ça devrait être un maximum sur les 6 prochains mois et ça ne viendra que sous réserve qu'on réussi vraiment à créer un outil collaboratif qui servirait aussi à suivre des actions connexes liées indirectement à la transition écologique.

En réaction à cette maquette : 
- Pas remarque de fond

- Forme : est-ce qu'on pourrait : 
   - Ajouter un picto pour illustrer le bouton "indicateurs" afin de le rendre plus attractif, essayer d'avoir quelque chose d'un peu plus sexy si c'est possible que ce que Gauthier avait fait pour la homepage (le principe est OK, faudrait juste jouer plus sur le rouge/orange/vert).
![image](https://user-images.githubusercontent.com/67585509/130086838-49bb570c-f661-40fc-b474-3bc179e1b949.png)
   - réintroduire les logos de la planète et de la circularité (perdus en route d'intégration du design système d'Etat) pour illustrer les référentiels à gauche des titres (a discuter peut-être ?)

**Comment by penelopel** [comment]
1) Après discussion : on garde la maquette de Maïtané telle quelle. (Ne pas tenir compte du commentaire de Nicolas au-dessus)

2) Pour clarifier, ce nouveau design est juste pour "Mes collectivités". 
Pour "Consulter toutes les collectivités", l'affichage initial reste le même.

**Comment by bertrandlalo** [comment]
@maiwann  @Nickvalley : 
Pour l'instant, on n'a qu'un seul plan d'action. Du coup, on fait quoi dans la colonne de gauche ? 
Aussi, cette carte devra être mise en prod après la #81 (notation citergie), sinon ça rend bizarre !

**Comment by maiwann** [comment]
On fait la version avec un seul plan d'actions à gauche, c'est pas grave !

+1 pour après la #81 :)

**Comment by bertrandlalo** [comment]
@maiwann  @Nickvalley Nouvelle micro question : 
Sur la maquette, le titre des axes d'Economie Circulaire sont différents de ceux des markdown (plus courts). 
Est-ce qu'on change les markdown pour préférer ces titres plus court ou est-ce qu'on réécrit, juste pour la vue de synthèse, ces titres ? 
Ex : `Définition d'une stratégie globale de la politique économie circulaire et inscription dans le territoire` est devenue `Stratégie globale`

**Comment by maiwann** [comment]
Je pense pas qu'on puisse se permettre de modifier tous les titres, donc juste pour la vue de synthèse s'il te plait !

**Comment by maiwann** [comment]
Fait en pair avec Raphaëlle tout à l'heure, c'est bon pour moi !
