### ISSUE TITLE
T - Intégrer Matomo (statistiques d'usage de l'outil)

### ISSUE THREAD

**Issue by Nickvalley** [betagouv/territoires-en-transitions#48]
matomo du beta

**Comment by Ynote** [comment]
Les statistiques récupérées par Matomo sont visibles publiquement sur https://stats.data.gouv.fr. Pour l'instant, c'est moi qui ai un accès admin sur l'interface, s'il y a besoin d'avoir un autre accès admin, on peut le demander sur `domaine-dev` sur le Mattermost du beta.
