### ISSUE TITLE
T Je peux consulter l'url principale

### ISSUE THREAD

**Issue by Nickvalley** [betagouv/territoires-en-transitions#50]
- [x] https://territoiresentransitions.fr
- [x] certificat
- [x] redirection http vers https
- [x] redirection www vers none-www
- [x] favicon

**Comment by Ynote** [comment]
Petit screenshot des redirections effectuées dans Gandi : 

![Screenshot 2021-06-08 at 17-26-28 Vos noms de domaine - Gandi net](https://user-images.githubusercontent.com/548778/121213630-b26f3880-c87e-11eb-8fc0-a4cbde363751.png)

**Comment by Ynote** [comment]
@Nickvalley @MartinRUAU @maiwann Est-ce qu'on veut une favicon ou on peut clore l'issue sans ça ?
