### ISSUE TITLE
La taille/graisse des titres n'est pas la bonne

### ISSUE THREAD

**Issue by maiwann** [betagouv/territoires-en-transitions#503]

**Comment by maiwann** [comment]
Page Référentiels :

![image](https://user-images.githubusercontent.com/27999224/128198870-32aa99e8-ef9c-4f1a-8b37-a8ca62c6e5a9.png)

font-weight : 600 sur les titres des mesures

**Comment by maiwann** [comment]
![image](https://user-images.githubusercontent.com/27999224/128199016-22a66dd7-f2c9-4c9e-b87d-3fe929171f69.png)

h1 : J'ai enlevé le font-weight: inherit; et le font-size: inherit;
h3 : j'ai l'impression qu'il faut enlever tous le css lié à la classe "fr-h3"

**Comment by maiwann** [comment]
Le résultat qu'il faudrait avoir : 
![image](https://user-images.githubusercontent.com/27999224/128199855-73a0efb9-5597-47f6-bb44-c90746a665f0.png)

**Comment by Nickvalley** [comment]
Corrigé avec la migration React et évolution prévue avec l'US #221
