### ISSUE TITLE
[TS] T -Réfacto la gestion de l'EPCI ID courante

### ISSUE THREAD

**Issue by bertrandlalo** [betagouv/territoires-en-transitions#567]
- [ ] get rid of `epciId`
- [ ]async check that this epci exists, and if not redirect with popup

**Comment by Nickvalley** [comment]
@bertrandlalo Est-ce que l'on peut clôturer cette carte [TS]? 
(Nettoyage du Jardin en cours en vue du séminaire et prochain sprint :-) )
