### ISSUE TITLE
T - Revoir l'ergonomie de la saisie de l'axe 5

### ISSUE THREAD

**Issue by Nickvalley** [betagouv/territoires-en-transitions#571]
Actions de l'axe 5 à renommer explicitement pour faciliter la saisie dans l'axe 5 et permettre de faire un lien avec les plans d'actions

- [x] Identifier les collectivités qui ont commencer à renseigner les statuts sur l'axe 5 ECi
- [x] Faciliter la saisie de l'axe 5 donc l'objectif est de permettre de visualiser les actions mises en place par la collectivité sur les 7 axes de l'économie circulaire
   - [x] Lier une action du référentiel à une fiche-action du plan d'actions (CODEC ou PLPDMA)
   - [x] Identifier les cibles
   - [x] Identifier les piliers de l'économie circulaire

> Identifier les actions dans le plan d'actions de la collectivité

**Comment by derfurth** [comment]
`SELECT nom,  nb_actions
FROM epci,
(SELECT epci_id, count(epci_id) as nb_actions
FROM (SELECT epci_id
      FROM actionstatus
      WHERE action_id like 'economie_circulaire__5.%' and not latest) as five
GROUP BY epci_id) as counted
WHERE epci_id = uid;
`
![image](https://user-images.githubusercontent.com/1872471/131554755-478db2f6-8dc7-4a7b-a5ce-fa69fb4222a0.png)
