### ISSUE TITLE
Envoi d'un mail aux utilisateurs pour les tenir au courant des avancées + proposer de faire des retours

### ISSUE THREAD

**Issue by Nickvalley** [betagouv/territoires-en-transitions#603]
- 1/ Sur le produit : demande de retours, demande d'entretiens utilisateurs ? Choix de priorisation pour les prochaines features ? (les primo-utilisateurs répondaient bien à ce genre de question et ça leur montre bien comment ils peuvent être impliqués) 
- 2/ Leur donner le lien vers la storymap mise à jour pour avoir de la visibilité sur la plateforme. 
- 3/ Promo : leur demander s'ils connaissent d'autres collectivités qui pourraient être intéressées ?

**Comment by maiwann** [comment]
https://pad.incubateur.net/JXuRiFlaREGIvJCZqJR1jw?edit Le lien vers le pad où je propose 2 messages selon si se sont des primo-utilisateurs ou de nouveaux utilisateurs :)
