### ISSUE TITLE
Actualiser les contenus de la page d'accueil sur ECi

### ISSUE THREAD

**Issue by Nickvalley** [betagouv/territoires-en-transitions#605]
- Mettre plus explicitement à jour l'intérêt de passer par le référentiel économie circulaire et se préparer à une labellisation. OBJECTIF : Donner envie à davantage de nouvelles collectivités de s'y mettre.

**Comment by penelopel** [comment]
@Nickvalley tu me diras si besoin d'aide là dessus.
