### ISSUE TITLE
T - Envoyer le mail mot de passe perdu lors de la création de compte

### ISSUE THREAD

**Issue by derfurth** [betagouv/territoires-en-transitions#670]
- [ ] Quand je crée mon compte je reçoit le mail mot de passe perdu
  - [ ] Rajouter l'explication sur la page de confirmation

**Comment by maiwann** [comment]
La phrase : 
> Un **mail automatique vient de vous être envoyé¨¨ afin que vous puissiez créer votre mot de passe. Si vous ne le recevez pas, pensez à **regarder votre dossier "Indésirable"**.

**Comment by Nickvalley** [comment]
Obsolète avec l'arrêt de l'utilisation du service Keycloak
