### ISSUE TITLE
US - Je veux pouvoir créer plusieurs plans d'actions pour ma collectivité

### ISSUE THREAD

**Issue by Nickvalley** [betagouv/territoires-en-transitions#68]
- [ ] Pouvoir créer plusieurs plans d'actions
   - [ ] Objet Plan d'Action
   - [ ] Un endpoint plan d'action
   - [ ] Un composant création de Plan d'action qui ressemble au composant création des axes de la structrure dd'un plan d'actions (un titre à saisir)

- [ ] Afficher les axes dans leur plan d'action
- [ ] Un axe est rattaché à un plan d'action 

----

- [ ] Pouvoir suivre plusieurs plans d'actions relatifs à la transition écologique différents dans l'outil. Ex. PLPDMA, PCAET, CRTE, etc.
- Une fiche-action doit pouvoir être affichée dans la structure de plusieurs plans d'actions

Personnes chez qui enquêter pour l'Ux: 
- Touraine vallée de l'indre
- CC Coeur de Var
---

**Comment by penelopel** [comment]
### Retours utilisateurs (via mail) sur la fonctionnalité  "Pouvoir créer plusieurs plans d’actions pour une même collectivité"

1. Est-ce que ça vous serait utile ? 
* OUI et NON
* oui
* non
* oui

2. Si oui, pourquoi ? Avez-vous un exemple en tête ?
- oui, car la collectivité suit plusieurs plan d’actions (PCAET, CTEC, projet EIT) – NON parce que cela impliquerait parfois de rentrer 2 fois la même action qui figure dans les 2 plans – Il serait peut être plus interessant de pouvoir rattacher chaque action à un « programme » de manière indépendante (via des TAG ou des mots clés par exemple)  - et ensuite de pouvoir visualiser l’avancement des plans d’actions liés à ces « TAG »
- Concrètement la transition écologique et énergétique apparaît de plus en plus dans les différents plans réglementaires et/ou volontaires. Il serait vraiment intéressant et utile de pouvoir tous les croiser dans une même plateforme et de voir ainsi parfois avoir les infos des différents pôles d’une même intercommunalité sans avoir à toujours mobiliser les équipes. Je pense notamment lorsque l’on répond à des AAP, cela peut être le cas.
- Nous n’en avons pas l’utilité pour le moment mais d’autres collectivités ont plusieurs programmes d’actions. A voir si cela ne complexifie pas les choses

**Comment by maiwann** [comment]
J'ai besoin de plus d'infos là dessus : 
Est-ce que si je filtre pour trouver les actions dont je suis référent, je dois pouvoir filtrer sur tous les plans d'action en même temps ? Ou est-ce que c'est ok qu'il soient séparés ? (si tout doit être mutualisé, ça me semble plus compliqué à représenter dans une interface simple 😬 car tout va être au même endroit ) @Nickvalley

**Comment by Nickvalley** [comment]
> 
> 
> J'ai besoin de plus d'infos là dessus :
> Est-ce que si je filtre pour trouver les actions dont je suis référent, je dois pouvoir filtrer sur tous les plans d'action en même temps ? Ou est-ce que c'est ok qu'il soient séparés ? (si tout doit être mutualisé, ça me semble plus compliqué à représenter dans une interface simple 😬 car tout va être au même endroit ) @Nickvalley

Je pense qu'il faudrait plutôt les deux et pouvoir filtrer si l'on veut voir tout où seulement dans un des plans d'actions mais que dans l'immédiat ça peut être ok de séparer. 

A l'avenir lorsque d'ici quelques sprints on pourra afficher des choses différentes en fonction du profil (conseiller, référent collectivité, personne ressource de collectivité) il me semble que pour les personnes qui se connecteront en tant que personnes ressources qui alimentent les données ou mettent à jour ce sera indispensables qu'elles puissent avoir une page qui permette de voir directement "Mes actions" qui récapitulera toutes les actions qui les concernent directement dans l'ensemble des plans d'actions de la collectivité s'il y en a plusieurs.

**Comment by Nickvalley** [comment]
@maiwann As-tu déjà pu créer des maquettes pour cette US du sprint en cours?

**Comment by maiwann** [comment]
Les maquettes : 
La page d'accueil commence à changer pour pouvoir proposer le bouton "Ajouter un plan d'actions" via une modale pour préciser le nom : 

![Multi_plans_accueil](https://user-images.githubusercontent.com/27999224/129370406-39609783-0e4e-455f-a232-bd36ddc6e46c.png)
![multi_plans_nom](https://user-images.githubusercontent.com/27999224/129370409-b768902e-0dbe-4cba-be9d-d72b3263f040.png)

Pour pouvoir rajouter une fiche-action à plusieurs plans, on rajoute un bouton sous "Catégorie" qui ouvre lui aussi une modale permettant de choisir le plan en question, puis sa catégorie

![Fiche-action](https://user-images.githubusercontent.com/27999224/129370499-04d6fb68-7836-4f81-91e7-baf36bdc2161.png)
![Fiche-action_autre_plan](https://user-images.githubusercontent.com/27999224/129370551-46c4106d-1364-45a1-afe2-5cd507578d88.png)

**Comment by Nickvalley** [comment]
Remplacer le terme "catégorie" par "arborescence"

On avait chercher à remplacer catégorie par autre chose et on avait dit "structure" et maintenant que j'ai eu des retours comme quoi le terme est ambigu car on a aussi les "organisations/entreprises/structures pour ce terme dans les plans d'actions je me dit qu'on pourrait parler d' "arborescence" du plan d'actions ?  :thinking_face:  Je me dit que 1/ on peut pas confondre ce terme qui est clair. 2/ c'est un beau mot de la langue française conoté nature :smile:
