### ISSUE TITLE
Je visualise où en sont les autres collectivités au regard des informations disponibles sur la plateforme

### ISSUE THREAD

**Issue by MartinRUAU** [betagouv/territoires-en-transitions#680]
- A partir de la liste des collectivités je peux retrouver facilement les collectivités ayant le plus progressé au regard de l'utilisation de la plateforme : 
   - [ ] Progression courante dans les référentiels (Score décroissant sur chacun des référentiels CAE et ECi)
   - [ ] Nombre d'actions sur les plans d'actions de la collectivité
   - [ ] Nombre d'indicateurs renseignés

**Comment by Nickvalley** [comment]
Doublon. #1873 
Possible via la vue toutes les collectivités
