### ISSUE TITLE
Auto-complétion dans le choix des collectivités

### ISSUE THREAD

**Issue by maiwann** [betagouv/territoires-en-transitions#718]
A faire après #849 

- [x] pouvoir utiliser les epcis banatic/ commune insee
  - [x] importer les collectivités
- [x] n'afficher que les collectivités qui ont des données dans la liste des autres collectivités
- [x] utiliser l'autocompletion pour choisir les collectivités à ajouter.

**Comment by maiwann** [comment]
Voilà les maquettes : 

## Lors de la création de la collectivité

![Capture d’écran 2021-08-31 à 10 33 53](https://user-images.githubusercontent.com/27999224/131470580-ec7179e4-fc41-4ea1-99af-8214b4a420ee.png)

Les informations récupérables automatiquement sont récupérées
![Capture d’écran 2021-08-31 à 10 34 04](https://user-images.githubusercontent.com/27999224/131470577-6f534139-4337-4315-ab44-619760954667.png)


Le bouton "Lier une collectivité" correspond à une autre issue
![Capture d’écran 2021-08-31 à 10 34 12](https://user-images.githubusercontent.com/27999224/131470576-7a2db634-317d-4792-af6e-fe43701d861c.png)

Le bouton "Personnaliser les référentiels" est pour la #73

**Comment by maiwann** [comment]
Lister les règles pour les noms abrégés

**Comment by penelopel** [comment]
=> Pour être en prod, il faudra que le nouveau back soit en prod, donc plutôt en 2 sprints.
