### ISSUE TITLE
TT - Je peux gérer mes fiches actions sur une structure à 3 niveaux

### ISSUE THREAD

**Issue by Nickvalley** [betagouv/territoires-en-transitions#72]
- [ ] Gestion de la structure d'un plan d'actions depuis la page plan d'actions (liste des fiches) à partir d'un bouton "Gérer la structure" (Gérer la structure du plan d'actions)

- [ ] Modale de gestion de la structure : 
   - [ ] Permet de CRED un axe ou sous-axe
   - [ ] Les axes et sous-axes sont triés par ordre alphabétique
   - [ ] La profondeur est limitée à trois niveaux (axes, sous-axes, fiches-actions)

Attention modifications par rapport aux maquettes : 
- Gérer les catégories = "Gérer la structure" sur les pages plan d'actions et fiche action
- Police de la modale : Utiliser du gras pour les sous-axes et enlever les puces pour s'approcher dès la création de l'affichage final sur la page "Plan d'actions
- L'ex champ "Catégorie" devient "Structure (axe, sous-axe)"

------------------
- Je peux afficher mon plan d'actions avec une structure sur 3 niveaux (axes, sous-axes, fiches-actions) au lieu de deux seulement
- Je peux gérer cette structure de mon plan d'action (création/modification/suppression d'axes et sous-axes)

**Comment by maiwann** [comment]
Je pense réaliser une pop-up qui sera accessible via le bouton "Nouvelle catégorie" (qu'on renommera en "Créer/Modifier une catégorie")

**Comment by penelopel** [comment]
### Retours utilisateurs (via mail) sur la fonctionnalité  "Personnaliser la structure selon laquelle s’affiche un plan d’actions sur plus de 2 niveaux (par exemple : Catégorie > Sous-catégories > Fiches-actions au lieu de Catégorie > Fiches-actions)"

1. Est-ce que ça vous serait utile ? 
- OUI
- oui si cela signifie que l’on peut avoir une fiche action dans plusieurs sous-catégories. Parfois une seule et même action peut permettre de répondre à plusieurs catégories/ champs de compétence.
- non
- oui

2. Si oui, pourquoi ? Avez-vous un exemple en tête ?
- Pour pouvoir mieux « coller » à la structure de notre PCAET, qui comprend 4 niveaux :  Axe, sous axes, fiche projet – actions concrètes
-  Je n’ai pas d’exemple existant pour le moment mais cela pourrait être utile lorsque notre programme d’actions sera élaboré (peut-être : Energies renouvelables > Habitat > Fiche action 1 …)

3. De combien de niveaux auriez-vous idéalement besoin ? 
- à minima 3, voire 4
- 3 niveaux cela semble adéquat. Cela permet une catégorisation sans surcharger la chose non plus.
- Je pense que 2 niveaux (catégorie/sous-catégorie) sont suffisants

**Comment by maiwann** [comment]
Voilà pour ma proposition : 

- Le bouton "Nouvelle catégorie" serait renommé en "Gérer les catégories" et il ouvrirait une modale : 
![Capture d’écran 2021-08-02 à 11 51 34](https://user-images.githubusercontent.com/27999224/127842726-d4fae6c2-9663-466d-b26a-99fc2068bb99.png)
![Capture d’écran 2021-08-02 à 11 51 40](https://user-images.githubusercontent.com/27999224/127842750-20d9a4aa-6a47-4ede-a41e-86d3eae08c01.png)
![Capture d’écran 2021-08-02 à 11 51 47](https://user-images.githubusercontent.com/27999224/127842748-cf203d6e-716d-40dc-874b-cf1f65f2bdf0.png)
![Capture d’écran 2021-08-02 à 11 51 54](https://user-images.githubusercontent.com/27999224/127842747-48037607-fa33-4875-a038-c2ecab802719.png)

**Comment by maiwann** [comment]
J'ai besoin de vos indications @bertrandlalo @derfurth pour savoir ce qui serait le plus simple à implémenter pour écrire le nom de la catégorie : idéalement, je me dis que si on reste dans la modale avec un champ label qui se cale au bon endroit, ca serait bien mais je sais pas si c'est compliqué à faire pour vous ?

**Comment by maiwann** [comment]
TODO : 
- [ ]Parler de structure / axes / sous-axes
- [ ] Rajouter des listes à puces

**Comment by maiwann** [comment]
Le bouton "Nouvelle catégorie" serait renommé en "Gérer la structure" et il ouvrirait une modale :

![Capture d’écran 2021-08-03 à 16 39 53](https://user-images.githubusercontent.com/27999224/128035068-fb3e439b-5cf0-4364-b9c0-2ff1326899a8.png)

![Capture d’écran 2021-08-03 à 16 40 01](https://user-images.githubusercontent.com/27999224/128035065-dff9fb8f-9966-4976-9a87-68449ad8486a.png)

![Capture d’écran 2021-08-03 à 16 40 08](https://user-images.githubusercontent.com/27999224/128035062-e26a7be6-1e5c-4712-8529-76f7dbda84f9.png)

![Capture d’écran 2021-08-03 à 16 40 16](https://user-images.githubusercontent.com/27999224/128035057-3810d7aa-30dc-49ee-97e0-50b4015b2dd2.png)

Pour l'instant le bouton "Gérer la structure" existe seulement dans la fiche-action, et avec l'issue #68 on rajoutera le bouton à un autre endroit

**Comment by maiwann** [comment]
Et pour une idée du niveau à plusieurs titres, voilà une maquette. Attention elle contient aussi les changements pour la #221 dans la façon dont s'affichent les fiches-actions 

![Plan d'actions(1)](https://user-images.githubusercontent.com/27999224/129371329-f2c24d72-36bb-47df-a438-1760d51b46d9.png)

**Comment by maiwann** [comment]
Et on rajoute un bouton "Gérer les catégories" à droite de "Catégorie" et à droite du titre du plan d'actions (voir au-dessus)

![Fiche-action copie](https://user-images.githubusercontent.com/27999224/129371903-b993fea0-bd6f-412e-9cdb-ca869801e992.png)

**Comment by maiwann** [comment]
@Nickvalley Ce qui est dans la description demande des choses en plus que ce qu'il y a sur les maquettes, est-ce qu'on peut en rediscuter ou essayer a minima comme sur les maquettes avant de rajouter des fonctions ?

> Les axes ont un champ numérotation optionel (le même que sur les fiches action)
> A coté du titre je peux créer un nouveau sous axe (un axe dont le parent est celle du titre)
> A coté du titre je peux supprimer cet axe après avoir confirmé mon action

**Comment by Nickvalley** [comment]
Du coup je n'avais pas mis à jour la description (dernier edit par Florian en sprint planning du 2/08) suite à notre discussion sur le maquettage donc voici ce qu'il faut a minima pour débuter : 

- Par contre la fonction (modale) "Gérer la structure du plan d'actions" doit permettre d'ajouter/supprimer et modifier un axe ou sous-axe de la structure

> Les axes ont un champ numérotation optionel (le même que sur les fiches action) - Obsolète suite à notre discussion. la numérotation des axes et sous-axes peut être gérée directement par leur titre et un classement alphabétique et cela devrait suffire
> A coté du titre je peux créer un nouveau sous axe (un axe dont le parent est celle du titre)  --> faisait référence à la modale donc maquette OK avec les boutons (Ajouter un sous-axe)
> A coté du titre je peux supprimer cet axe après avoir confirmé mon action "Souhaitez-vous supprimer cet axe de la structure de votre plan d'actions ? Boutons : Annuler/Supprimer" --> A ajouter dans la modale car il faut pouvoir supprimer des axes et sous-axes que l'on a créé par erreur où que l'on ne veut plus utiliser

+ il manque la fonctionnalité pour modifier un axe ou sous-axe

Je mets à jour la description

**Comment by Nickvalley** [comment]
@maiwann j'ai mis à jour la description. 
Attention modifications par rapport aux maquettes : 
- Gérer les catégories = "Gérer la structure" sur les pages plan d'actions et fiche action
- Police de la modale : Utiliser du gras pour les sous-axes et enlever les puces pour s'approcher dès la création de l'affichage final sur la page "Plan d'actions

**Comment by maiwann** [comment]
> il manque la fonctionnalité pour modifier un axe ou sous-axe

Pour ça j'ai besoin de discuter avec @bertrandlalo ou @derfurth de comment on peut faire pour rajouter / modifier les axes (comment on peut proposer un champ pour qu'il soit écrit / réécrit)

**Comment by maiwann** [comment]
Le bouton "Nouvelle catégorie" serait renommé en "Gérer la structure" et il ouvrirait une modale :

![Capture d’écran 2021-08-18 à 15 58 47](https://user-images.githubusercontent.com/27999224/129911765-c59bb541-05c5-4db1-a445-1f8a4143f519.png)
![Capture d’écran 2021-08-18 à 15 58 52](https://user-images.githubusercontent.com/27999224/129911761-de1929ac-8169-4f4f-b881-c010c34b2aeb.png)
![Capture d’écran 2021-08-18 à 15 58 58](https://user-images.githubusercontent.com/27999224/129911758-d867be51-bbcd-4637-9afc-a02a86427232.png)
![Capture d’écran 2021-08-18 à 15 59 24](https://user-images.githubusercontent.com/27999224/129911751-cfc0bda4-d8fb-43ca-b500-8677d739dda6.png)
