### ISSUE TITLE
T - Onboarding - Formulaire de création de compte remplacer le bouton "Envoyer" par "Créer mon compte"

### ISSUE THREAD

**Issue by penelopel** [betagouv/territoires-en-transitions#733]
- [ ] Formulaire de création de compte remplacer le bouton "Envoyer" par "Créer mon compte"

**Comment by penelopel** [comment]
Soucis repérés : 
- à quoi ressemble l'arrivée d'un premier utilisateur maintenant ?
![image](https://user-images.githubusercontent.com/5320547/134908811-9ceea39a-a19e-4cb9-aef0-cc1bfe05e5a1.png)
- Des utilisateurs ne comprennent pas qu'il faut ajouter sa collectivité pour pouvoir modifier les données.

**Comment by penelopel** [comment]
![image](https://user-images.githubusercontent.com/5320547/134926110-ed0104d8-3fcc-4710-960a-c8459a204f5a.png)

![image](https://user-images.githubusercontent.com/5320547/134926383-cec08e33-ae5f-4231-b88f-1aae893fb4d9.png)

**Comment by maiwann** [comment]
Pas de feedback quand on a cliqué une 1e fois sur le bouton "Envoyer" pour se créer un compte

**Comment by maiwann** [comment]
## Création de compte
Création de compte : Préciser l'intérêt ?

## Haut de l'écran
Vos collectivités -> Tableau de bord

Avoir 2 types d'accueil ?
- écran si j'ai pas de collectivité
- écran une fois qu'on en a rajouté une…

## Liste
On aura les filtres ensuite pour la liste

Différencier les 2 zones : 
- Actions dans la zone du haut
- Droit en lecture seulement zone du bas

**Comment by maiwann** [comment]
Bandeau lecture seule à revoir

**Comment by maiwann** [comment]
Voilà mon avancement pour la soirée @penelopel si tu veux me dire ce que tu en penses :)
![Choix_collectivite_2](https://user-images.githubusercontent.com/27999224/134943630-76bcd19b-7d51-4356-8afd-2010d9afe4f4.png)

**Comment by penelopel** [comment]
Sympaaa ! 

* Je m'interroge sur "Tableau de bord" (plus joli) versus "Espace de travail" (plus "vrai") ? Ou autre chose. 

* Au niveau du texte que dirais-tu de : 
- Vous n'avez pas encore de collectivité ! 
- Pour travailler sur une collectivité, vous devez l'ajouter à votre tableau de bord. Souhaitez-vous en rajouter une ?

* Pour la liste de toutes les collectivités, que mettrais-tu derrière le bouton "Voir" (ou "Consulter") ? Plan d'action ?

**Comment by maiwann** [comment]
> Je m'interroge sur "Tableau de bord" (plus joli) versus "Espace de travail" (plus "vrai") ? Ou autre chose.

Je sais pas si je vois une grosse différence entre les deux, peut-être qu'on teste l'un des deux et si ça coince on change ?

> Pour la liste de toutes les collectivités, que mettrais-tu derrière le bouton "Voir" (ou "Consulter") ? Plan d'action ?

Je mettrais le tableau de bord de la collectivité en modale, pour avoir une vue d'ensemble de là ou elle en est… Qu'en penses-tu ?

**Comment by maiwann** [comment]
(maquette mise à jour avec le texte que tu proposes, moins la dernière phrase sinon ça commençait à devenir un peu trop long)

**Comment by maiwann** [comment]
Une fois que j'ai cliqué sur "Ajouter une collectivité" j'ai accès à un champ qui filtre la liste des collectivités selon ce que j'y écris (de l'autocomplete si c'est le bon terme ?)

![Choix_collectivite_modale(2)](https://user-images.githubusercontent.com/27999224/135239982-d57b0fe7-eaaa-42d2-a55e-5ae9c8afd195.png)
