### ISSUE TITLE
US - Mise à disposition des données du référentiel dans retool par collectivité

### ISSUE THREAD

**Issue by maiwann** [betagouv/territoires-en-transitions#746]
Document d'Émeline pour référence

**Comment by maiwann** [comment]
Pour la maquette, on va rajouter une petite roue à droite des titres des référentiels, qui ouvrira une modale toute bête avec…un seul bouton 😅 

![image](https://user-images.githubusercontent.com/27999224/135870893-b63f1d0c-e226-4f7c-a713-85a70735620c.png)


![image](https://user-images.githubusercontent.com/27999224/135871844-ffddc9ba-31c3-4b0a-b7f9-b05d0ff3cf67.png)

**Comment by penelopel** [comment]
=> Emeline fournit une version exemple vendredi.

**Comment by derfurth** [comment]
![image](https://user-images.githubusercontent.com/1872471/141080506-514ad208-0e3c-4b59-9251-137f40d2214e.png)
colonnes (A?), D, E, F, G dans un csv

**Comment by Nickvalley** [comment]
OLD 

## Les colonnes

Nom de l'axe
Nom du sous-axe

Identifiant
Nom de la mesure ou action ou tâche
Nombre de points possibles
Description
Contexte
Exemples
Ressources
Preuves
Nom des indicateurs

Statut des actions complétées
Score obtenu en réalisé
Score obtenu en programmé (lié à  la #842
