### ISSUE TITLE
Je peux remplir les indicateurs CRTE (COT) dans l'outil

### ISSUE THREAD

**Issue by Nickvalley** [betagouv/territoires-en-transitions#77]
- [x] Je peux visualiser les indicateurs CRTE parmi les référentiels d'indicateurs de la plateforme
- [x] Les indicateurs identiques entre les différents référentiels (ECi, CAE, CRTE) sont mutualisés pour ne pas avoir à les renseigner plusieurs fois
- [x] Je peux utiliser et lier ces indicateurs à mon plan d'actions comme les autres indicateurs de la plateforme

---
Métier : 
- [x] Ajouter les indicateurs CRTE aux référentiels (Terminé Martin)
- [x] Lier les indicateurs communs aux autres référentiels (Terminé Martin)

**Comment by bertrandlalo** [comment]
- [ ] Codegen : extraire le champ "valeur" et par défaut égal à l'ID
- [ ] Sanity-Check : vérifier que le champ "valeur" correspond bien à un ID d'indicateur
- [ ] Dans l'interface : mettre à jour les valeurs de l'indicateur ID "valeur" --> "valeurId"
