### ISSUE TITLE
E Gérer à minima le système de notation ECI

### ISSUE THREAD

**Issue by Nickvalley** [betagouv/territoires-en-transitions#79]
Pour chaque axes/mesure / action / tâche je voudrais voir : 
**xx % (xx point / xx)**
par ex. 60% (47/80)

--- 

Le NC manuel pondère la notation

**Code couleur**
- Non renseigné : pas de "badge"
- 0 - 34 : Rouge red 600 #DC2626
- 35 - 49 : Orange amber 500 #F59E0B
- 50 - 64 : Jaune amber 300 #FCD34D
- 65 - 74 : Vert clair (j'ai rien trouvé d'approchant dans tailwind #C0D72D)
- 75 - 100 : Vert foncé emerald 600 #059669

**Comment by maiwann** [comment]
![Referentiel_mesure](https://user-images.githubusercontent.com/27999224/120653867-69d00d80-c481-11eb-9461-f8954e371685.png)

Voilà la maquette, disponible aussi sur https://www.figma.com/file/huNGZwSwBUa5dJAzXkh2Mh/TeT?node-id=82%3A10001

En résumé : 
 le pourcentage est en noir et gras, en taille 16
 le nombre de points obtenu / total de points possible est en gris foncé, en regular et en taille 14
