### ISSUE TITLE
E Gérer les labellisations

### ISSUE THREAD

**Issue by Nickvalley** [betagouv/territoires-en-transitions#80]

**Comment by maiwann** [comment]
Ce que je vois issu des entretiens utilisateurs, pour le socle minimal (j'essaie de prioriser)

## Notation
- Pouvoir re-préciser une note quand une tâche est entre "pas faite" et "faite
- Pouvoir valoriser des choses que la collectivité fait "en plus" du référentiel
- Pouvoir donner une visibilité sur les points obtenus et son potentiel à la collectivité 

## État des lieux
- Pouvoir échanger avec les utilisateurs pour repréciser des description de tâches

## Audit
- Pouvoir échanger avec les auditeurs pour repréciser des notes / descriptions

**Comment by maiwann** [comment]
Note pdt entretien : 
- Pouvoir assigner les personnes de la collectivité à des mesures

**Comment by maiwann** [comment]
Note : Pouvoir demander x ou y document, avec une date butoir

**Comment by Nickvalley** [comment]
Gestion profils collectivités : - Pouvoir indiquer dans le profil d'une collectivité qu'elle est engagée en démarche de labellisation Cit'ergie ou économie circulaire
- Pouvoir connaître la région de rattachement d'une collectivité pour son suivi
- Récupérer automatiquement les informations importantes d'une collectivité (coordonnées, population
- Pouvoir attribuer un ou plusieurs conseillers à une collectivité

État des lieux : 
- Pouvoir personnaliser la notation
- Pouvoir ajouter des actions
- Pouvoir saisir des actions partiellement réalisées et programmées
- Afficher le score réalisé + programmé
- Récupérer le benchmark européen

Audit : 
- Gérer un statut d'avancement du processus en cours de la collectivité (Etat des lieux, Programme d'action, Audit, Visite annuelle, etc.)
- Permettre à l'auditeur de valider l'évaluation de la collectivité (statut d'audit des actions)
- Permettre de suivre un statut d'avancement de la validation de l'audit (idem inspiration statut d'avancement de remplissage du référentiel)
- Permettre à l'auditeur de commenter l'évaluation réalisée (par la collectivité et/ou le conseiller) et proposer des modifications de la notation
- Permettre de suivre les échanges entre l'auditeur et les personnes évaluatrices (conseiller et/ou collectivité)

Autres étapes du processus : 
- Gérer les visites annuelles
- Gérer le prédiagnostic Cit'ergie d'engagement en démarche

**Comment by Nickvalley** [comment]
US détaillées de l'Epic reprises dans le sprint backlog avec le label "labellisation"
