### ISSUE TITLE
TT - Améliorer le Header et permettre l'accès à l'aide [Helpdesk]

### ISSUE THREAD

**Issue by Emelinejy** [betagouv/territoires-en-transitions#806]
Après la mise en place de la gestion des droits #241, faire évoluer le Header pour faciliter la navigation : 
- [ ] Affichage du Prénom de l'utilisateur au lieu de "Déconnexion". Au clic sur le prénom. Accès à un menu pour accéder soit à son profil, soit pour se déconnecter. 
   - [ ] "Mon profil" (mise à jour Prénom/Nom/Email)
   - [ ] "Déconnexion"
-  [ ] Aide > Ajout d'un icône aide à gauche du Prénom utilisateur/bout déconnexion qui permet d'accéder au Helpdesk/FAQ

![image](https://user-images.githubusercontent.com/67585509/139197689-548c80d0-2133-4d34-97d3-16a0fa73a4a6.png) 
- [ ] Ajouter le logo du programme "Territoires engagés" (reprendre de la Home)

**Comment by Nickvalley** [comment]
@cami-na Je te réaffecte cette carte qui était au frigo en lien avec ton travail que tu as déjà fait sur l'amélioration du header. L'enjeu prioritaire pour moi c'est de préparer l'arrivée d'un bouton "Aide" pour faciliter l'accès à notre future FAQ aux utilisateurs.

**Comment by cami-na** [comment]
**En tant que visiteur** 
- Lien vers la page Aide (URL à préciser)
- Lien vers la page de Création de compte
- Lien vers la page Me connecter

**En tant qu'utilisateur connecté**
- Lien vers la page Aide
- Liens vers la page Mon profil (à spécifier ?) et option Déconnexion

[Proposition de maquette](https://www.figma.com/file/YhEoPD2YxqHuEaPn8nKWql/Maquettes-2k22?node-id=136%3A20742)

**Comment by cami-na** [comment]
Vu avec Émeline 
- En pause : en attente du contenu de la page Aide (FAQ) 
- Page profil non prioritaire
