### ISSUE TITLE
US - Je peux accéder à la demande d'audit grâce à un bouton

### ISSUE THREAD

**Issue by penelopel** [betagouv/territoires-en-transitions#807]
- [x] il y a un bouton "Demande d'audit" situé à droite de la ligne "Économie circulaire"/"Climat Air Énergie" - complétude - score global
![image](https://user-images.githubusercontent.com/92379675/139254264-2683ed20-c7d0-421b-a914-993dc1b5382d.png)

- [x] Quand on clique sur le bouton "Economie circulaire", on arrive sur une page ou une pop-up avec inscrit : 

Titre : "Demande d'audit du label Economie circulaire"
Texte (avec checkbox à remplir manuellement dans un premier temps) : 
Pour pouvoir faire une demande d'audit, vous devez : 
- Renseigner 100% du référentiel d'évaluation,
- Fournir les preuves obligatoires attendues,
- Avoir un score minimal sur certaines sous-actions,
> 100 % à la sous-action 1.1.1
au moins 20 % aux sous-actions 1.1.2 et 1.1.3
100 % à la sous-action 3.2.0 (si le montant annuel d'achats de la collectivité est supérieur à 100 millions d'€)
100 % aux sous-actions 2.1.0, 2.2.0, 2.3.0 et 4.1.0 (c'est-à-dire respecter la règlementation si l'EPCI est concerné dans le cadre des compétences exercées)
-  Faire acte de candidature en fournissant : 
>  Un courrier d'acte de candidature (motivation et palier visé, précision des compétences, engagement à améliorer de façon continue sa politique ECi, identité et coordonnées du référent technique,)
Le règlement du label signé
Les derniers statuts approuvés par l’autorité préfectorale ou arrêté préfectoral portant création de l’EPCI
Éventuellement, la délibération d'engagement dans le processus de labellisation.

L'ensemble des fichiers est à envoyer à dteci@ademe.fr en respectant l'architecture suivante. (= lien de téléchargement du dossier outil collecte preuve)  

-- 

### Plus tard 
On garde la suite pour plus tard => Spécifié en #889

- [ ] Il y a en bas un bouton "Déposer la demande de candidature" qui est grisé (pas cliquable) tant que toutes les checkboxes ne sont pas vertes. 

- [ ] Une fois que toutes les checkboxes sont cochées, on peut cliquer sur le bouton.
- [ ] Après avoir cliqué sur le bouton, Une checkbox supplémentaire apparait pour m'avertir que le référentiel va passer en statut "Audit en cours" pour ma collectivité et que je ne pourrai momentanément plus modifier le référentiel et les fichiers preuves jusqu'à la fin du processus d'audit. _(Nota : fonctionnement idéal à terme = création d'une branche de clone du référentiel pour l'audit pour faire la photo avant et après audit et l'octroi du label tandis que la collectivité peut continuer à travailler sur la branche courante - mais ce sera pour plus tard quand on aura du retour d'expérience sur l'usage pendant la phase d'audit, peut-être pas utile si à l'avenir les audits peuvent se faire plus vite grâce à notre produit)_

**Comment by Emelinejy** [comment]
Pour faire une demande d'audit, il faut :
**Faire acte de candidature**
- Courrier d'acte de candidature (motivation et palier visé, précision des compétences, engagement à améliorer de façon continue sa politique ECi, identité et coordonnées du référent technique,)
- Règlement du label signé
- Derniers statuts approuvés par l’autorité préfectorale ou arrêté préfectoral portant création de l’EPCI 
- Éventuellement la délibération d'engagement dans le processus de labellisation

**Avoir un score minimal sur certaines sous-actions**
- 100 % à la sous-action 1.1.1 
- au moins 20 % aux sous-actions 1.1.2 et 1.1.3
- 100 % à la sous-action 3.2.0 (si le montant annuel d'achats de la collectivité est supérieur à 100 millions d'€)  
- 100 % aux sous-actions 2.1.0, 2.2.0, 2.3.0 et 4.1.0 (c'est-à-dire respecter la règlementation si l'EPCI est concerné dans le cadre des compétences exercées)

**Fournir les preuves attendues pour justifier les scores**
Voir annexe 1 du guide du candidat 
[Guide du candidat au label Eci_03_11_21.docx](https://github.com/betagouv/territoires-en-transitions/files/7468654/Guide.du.candidat.au.label.Eci_03_11_21.docx)

**Comment by penelopel** [comment]
Yes je m'en occupe

**Comment by Emelinejy** [comment]
Serait-il possible de rajouter "Avoir **un taux de complétude de 100 % et** un score minimal sur certaines sous-actions" dans la deuxième condition ? 
Cette information a disparu au fil des échanges : désolée !

**Comment by penelopel** [comment]
Attention, on a mis taux de remplissage partout donc il vaut mieux garder
ce terme.

Et on ne dit plus qu'il faut écrire à DTECI à la fin ?

**Comment by Emelinejy** [comment]
Texte à modifier dans la modale : 
**Demande d'audit du label Économie circulaire**
Pour pouvoir faire une demande d'audit, vous devez :
**Renseigner 100% du référentiel d'évaluation**
**Fournir les preuves obligatoires attendues pour justifier les scores**
- [ ] Se référer à la rubrique "preuve" des différentes tâches
**Avoir un score minimal sur certaines sous-actions**
- [ ] 100 % à la sous-action 1.1.1
- [ ] au moins 20 % aux sous-actions 1.1.2 et 1.1.3
- [ ] 100 % à la sous-action 3.2.0 (si le montant annuel d'achats de la collectivité est supérieur à 100 millions d'€)
- [ ] 100 % aux sous-actions 2.1.0, 2.2.0, 2.3.0 et 4.1.0 (c'est-à-dire respecter la règlementation si l'EPCI est concerné dans le cadre des compétences exercées)
**Faire acte de candidature en fournissant **
- [ ] Un courrier d'acte de candidature (motivation et palier visé, précision des compétences, engagement à améliorer de façon continue sa politique ECi, identité et coordonnées du référent technique,)
- [ ] Le règlement du label signé
- [ ] Les derniers statuts approuvés par l’autorité préfectorale ou arrêté préfectoral portant création de l’EPCI
- [ ] Éventuellement, la délibération d'engagement dans le processus de labellisation.

Une fois les conditions remplies, merci de signaler votre intention de demande d'audit au Bureau d'Appui par mail à dteci@ademe.fr qui vous informera de la procédure à suivre
