### ISSUE TITLE
US - Quand je clique sur le bouton "Me porter candidat", je déclenche une série d'action

### ISSUE THREAD

**Issue by penelopel** [betagouv/territoires-en-transitions#808]
Au moment où le candidat a cliqué sur le bouton "Me porter candidat" : 
- Un mail automatique est envoyé à dteci@ademe.fr informant que le candidat souhaite être audité, avec l'utilisateur de la collectivité en copie. 

Question : est-ce que ça bloque la collectivité tout de suite ou ça attend qu'il y ait un auditeur attribué ? 

(=> Pendant ce temps là, DTECI trouve un auditeur pour la collectivité.)

**Comment by Emelinejy** [comment]
Prise en compte dans le cadre de "Je peux préparer et faire ma demande de labellisation/audit #889-1352-808"
https://www.notion.so/territoires-en-transitions/Je-peux-pr-parer-et-faire-ma-demande-de-labellisation-audit-889-1352-808-372a03d9642549c487e1cd8b9bc1c916
