### ISSUE TITLE
L'auditeur et la collectivité et/ou le conseiller peuvent échanger sur la plateforme

### ISSUE THREAD

**Issue by penelopel** [betagouv/territoires-en-transitions#809]
Process: ![image](https://user-images.githubusercontent.com/5320547/138908849-f94384ba-713a-47ad-990a-048eb38d4095.png)

Question : 
- comment garder la trace des échanges entre l'auditeur et la collectivité ? (avoir un dialogue sur la page "Audit" ?) --> Inspiration EMT : Fil de discussion sur la page de chaque action?
- comment s'assurer que les fichiers preuve à mettre à jour se fassent bien sur la plateforme et pas ailleurs ? Soit c'est la collectivité qui les met à jour mais du coup droit compliqué + il faut notifier l'auditeur, soit c'est l'auditeur qui met à jour. --> Inspiration EMT : Page "Log" d'activités pour chaque compte collectivité?

**Comment by Emelinejy** [comment]
Pour demander d'effectuer une correction dans l'évaluation
    Pour demander des précisions pour me permettre de valider l'évaluation
    Pour expliquer une modification effectuée dans la notation (du conseiller ou de la collectivité)
