### ISSUE TITLE
T - Permettre de facilement préciser les statuts d'avancement des actions liées aux fiches-actions

### ISSUE THREAD

**Issue by maiwann** [betagouv/territoires-en-transitions#82]
- Pouvoir modifier les statuts des actions du référentiels liées depuis les fiches-actions

Ajouter la barre de statuts/avancement dans la fiche 
![image](https://user-images.githubusercontent.com/1872471/126506572-1f05a03a-53db-4251-87cf-5edda666445c.png)

![image](https://user-images.githubusercontent.com/1872471/126506704-7ac23d08-08d1-42e7-9858-cdb9810283ec.png)

**Comment by bertrandlalo** [comment]
Cette carte est en fait liée à #288 , car il y a un hard reload de la fenêtre dans le composant Statut. Pour pouvoir utiliser le même composant, on doit envisager une meilleure gestion des états (avec un store?). Je fais donc passer cette carte après la #288
