### ISSUE TITLE
Problème Grenoble Alpes Métropole : page blanche

### ISSUE THREAD

**Issue by Emelinejy** [betagouv/territoires-en-transitions#827]
La Chargée de mission économie circulaire de Grenoble Alpes Métropole nous a remonté un problème
![image](https://user-images.githubusercontent.com/92379675/139241933-3946b18e-185b-46a7-a727-c17a115b2b59.png)

Elle rencontre de nombreuses pages blanches lors de navigation sur le produit 
![image](https://user-images.githubusercontent.com/92379675/139241707-8aa01c6c-d58c-472e-b57f-b54949998c87.png)

Ces pages blanches sont générées lorsqu'elle clique : 
- sur "voir les indicateurs" depuis la page accueil/tableau de bord de la collectivité
- sur "Indicateurs" en haut à droite, depuis la page "Référentiels" ou "Mon plan d'actions"
- lorsqu'elle essaye de déplier les axes depuis la page "Référentiels"
Bref, elle ne peut pas faire grand chose sur l'outil quand elle navigue dessus !

**Comment by bertrandlalo** [comment]
@Emelinejy  ça ressemble au problème de Perpignan, est-ce que tu peux lui proposer un RDV avec nous pour qu'on regarde ?

**Comment by derfurth** [comment]
Demander à utiliser avec Firefox ou Chrome, si ça ne marche pas ça peut être le même problème que perpignan.
