### ISSUE TITLE
T - Ajouter une stat. sur la complétude dans Retool

### ISSUE THREAD

**Issue by derfurth** [betagouv/territoires-en-transitions#830]
- [x] Taux de complétude par collectivité avec Email des utilisateurs des collectivités concernées

---
Finalité déploiement: 
- 1/Envoyer un mail aux collectivités qui ont déjà bien complété le référentiel ECi pour les encourager à aller chercher la 1ère étoile de labellisation
- 2/ Envoyer un mail aux collectivités qui ont peu complété le référentiel ECi pour les encourager à poursuivre le renseignement du référentiel

**Comment by derfurth** [comment]
![image](https://user-images.githubusercontent.com/1872471/140933383-40f8d24b-b64a-4f7f-96e3-4e5ccd4ae5bb.png)

**Comment by Emelinejy** [comment]
La complétude n'est pas bonne pour certaines collectivités : Syndicat du Bois de l'Aumône (34 % sur la plateforme - 38 % sur Retool sur référentiel ECi) ou encore Cyclad (96 % sur plateforme - 98,53 % sur Retool pour ECi et 0 % sur plateforme - 2,9 % sur Retool pour CAE)
Les adresses mails ne sont pas renseignées pour chaque collectivité et ce n'est pas forcément l'adresse mail d'une personne de la collectivité qui est indiquée. Ex : Nantes Métropole reprend l'adresse mail de Raphaëlle alors qu'il faudrait que ce soit celle d'Éric Provost qui s'affiche
