### ISSUE TITLE
Aider à remplir les "Commentaires" qualitatifs des actions qui sont "Prévues/En cours/Faites"

### ISSUE THREAD

**Issue by penelopel** [betagouv/territoires-en-transitions#841]
- [ ] Lorsque je modifie un statut je suis encouragé à saisir un commentaire qualitatif dans la tâche concernée

**Comment by Emelinejy** [comment]
Remplacer "Commentaire" par "Justification du score et/ou du statut"
Conserver le "+" permettant de déplier mais ajouter un crayon pour éditer le texte
Modifier l'emplacement du bouton "Ajouter une fiche action" et le descendre en dessous du champ "Justification" ? au même niveau que le futur bouton "Ajouter une preuve" ?
