### ISSUE TITLE
US - Afficher le score futur (prévu+en cours) de la collectivité

### ISSUE THREAD

**Issue by Nickvalley** [betagouv/territoires-en-transitions#842]
⚠️ A challenger design

- [ ] Afficher explicitement en texte : 
   - 1/ Réalisées : xx,x % ; 
   - 2/ En cours = xx,x % ; 
   - 3/ Prévues = xx,x% ; 
   - 4/ Pas faites = xx,x% 
   - 5/ Réalisé + En cours + Prévu = xx,x%
- [ ] Compléter l'affichage du score par une jauge suffisamment large pour être bien visible permettant de voir ces scores ci-dessus par statut (Réalisées/En cours/Prévues/Pas faites) 
CF. inspiration github : 
![image](https://user-images.githubusercontent.com/67585509/142408306-fcd2ff1e-c8f3-4bf2-b89a-a47946ea22d0.png)

**Comment by penelopel** [comment]
A préciser : 
* Que fait-on du statut "en cours" ? 
* Question de l'affichage du score d'un point de vue UI par rapport à l'UI existante.

**Comment by penelopel** [comment]
#### Réflexions sur le statut en cours : 
=> il n'est pas souhaitable que le bouton "en cours" signifie que ce soit juste du programmé. 

Du coup :
 
OPTION 1 : 
- Garder "En cours" et distribuer les points entre "fait" et "programmé", avec une granularité de 0.25/0.50/0.75 (ou autre)
Avantage :
*ça permettrait aux collectivités qui débutent de voir qu'elles ont déjà quelques points de réalisé. 
*ça permettrait de filtrer pour voir ce qui est en cours de ce qui n'est pas débuté 
*il y a des actions qui sont des actions qui se renouvellent et qui ne sont jamais entièrement faites (ex: former des personnels) donc ça permettrait d'avoir de la finesse dans la notation et dans la comparaison entre les collectivités.

Avec cette option : les points programmés sont la somme des points "prévus" plus une partie des points "en cours" (un moins ce qui a déjà été fait) 

OPTION 2 : 
- Supprimer le bouton "en cours" et ne permettre aux gens de ne mettre que "Prévu/programmé" ou "Fait"
Avantage : 
* C'est plus simple au niveau des points

Avec cette option : les points programmés sont la somme des points prévus seulement.

**Comment by penelopel** [comment]
A court terme : "en cours" => compte comme du programmé seulement. 
Programmé : "prévue" + "en cours"

**Comment by penelopel** [comment]
Vérifier l'usage de "en cours" à ce stade
