### ISSUE TITLE
Sortir de la valeur des indicateurs

### ISSUE THREAD

**Issue by penelopel** [betagouv/territoires-en-transitions#851]
Que cherchons-nous à tirer des indicateurs ? 
- Moyenne globale 
- Moyenne par niveau de label 
- Moyenne par type de collectivité (statut / compétence / taille) 
- Max et mini 
- Comparaison des moyennes par an / par cycle 
- Nombre de collectivité qui ont 100% à un indicateur 
- Comparaison avec valeur cible, valeur seuil 

- [ ] nuage de points dans les indicateurs pour voir les valeurs des autres collectivités

- [ ] Envisager une arborescence des indicateurs de CAE (ex : regrouper et donner un titre de la 1.a à la 1.j) 
- [ ] Si pertinent, lier des indicateurs à des tâches

**Comment by Emelinejy** [comment]
Redondance avec carte #931
- Nuage de points/lignes des autres collectivités sur les indicateurs pertinents
- Valeurs moyenne des collectivités ayant renseigné l'indicateur lorsque c'est pertinent

*Nota: Différent des valeurs cibles et seuil nationales fixées dans les référentiels ou par les réglementations (https://github.com/betagouv/territoires-en-transitions/issues/40)
