### ISSUE TITLE
US - Permettre aux utilisateurs de supprimer un axe ous sous-axe dans leurs plans d'actions

### ISSUE THREAD

**Issue by Nickvalley** [betagouv/territoires-en-transitions#867]
Plans d'actions : 
- [ ] Pouvoir supprimer un axe ou un sous-axe de son plan d'actions après l'avoir créé(e). 
*A discuter : le comportement pour les éventuelles fiches-actions rattachées. Proposition : Permettre la suppression s'il n'y a pas de fiche-action rattachée*

**Comment by derfurth** [comment]
je ne trouve pas les maquettes avec la suppression https://github.com/betagouv/territoires-en-transitions/issues/72#issuecomment-901139818 ni https://www.figma.com/file/huNGZwSwBUa5dJAzXkh2Mh/TeT?node-id=0%3A1

**Comment by Nickvalley** [comment]
Y’a pas eu de maquette de faite pour le « Delete » d’un axe ou sous axe.
Proposition :
Le mettre derrière le bouton « Edit » avec le logo corbeille en ayant plutôt le Edit en CTA et la corbeille en affichage classique.
Pour le comportement vis-à-vis des fiches actions :

-        Suppression d’un axe ou sous-axe sans fiches actions rattachées en dessous : Message simple de confirmation : « Souhaitez-vous vraiment supprimer cet axe/sous-axe ? | Boutons « Supprimer | Annuler ».

-        Suppression d’un axe ou sous-axe avec des fiches actions rattachées en dessous – l’enjeu c’est de ne pas les perdre car on ne peut pas savoir a priori si l’utilisateur veut les affecter ailleurs (possible tant qu’il peut encore les voir quelque part) ou s’il souhaite les supprimer (pas encore possible, mais bientôt via le retool. Donc proposition : Même message que pour la suppression d’un axe/sous-axe sans fiche-action rattachée avec en plus l’avertissement suivant : Attention : Cet axe/sous-axe contient encore des fiches-actions qui lui sont rattachées. Si vous supprimez cet axe les fiches-actions associées n’y seront plus rattachées.
On en discute si besoin, peut-être que je ne suis pas clair…

**Comment by Emelinejy** [comment]
Le message de suppression s'affiche bien : 
![Suppression axe](https://user-images.githubusercontent.com/92379675/145371467-6abac6a0-49bb-4a31-8071-3a13edfc1b72.PNG)
Mais aucune action n'est engendrée en cliquant sur OK
Et il n'est ensuite plus possible de voir l'arborescence et de recommencer en cliquant sur "Modifier l'arborescence"
![Suppression axe-suite](https://user-images.githubusercontent.com/92379675/145371565-75efa547-308b-4b45-b646-f5b884c951d2.PNG)

**Comment by Emelinejy** [comment]
Le message de suppression s'affiche bien et l'action fonctionne sur les sous-axes (les fiches-actions liées se retrouvent dans une catégorie "Sans catégorie"
MAIS il y a un affichage bizarre dans l'arborescence (avec des 0 et des 1 sous les axes et sous-axes, dont je n'arrive pas à voir à quoi ça fait référence... - pas au nombre de fiches-actions pour sûr) et il n'est pas possible de modifier l'axe 6 dans la capture d'écran ci-dessous par exemple
![Suppression axe 2021-12-13](https://user-images.githubusercontent.com/92379675/145849224-83c65dee-5bde-4845-be25-6de46111000f.PNG)

**Comment by derfurth** [comment]
En effet c'est le nombre de sous catégories, un affichage de test que j'ai oublié d'enlever.

**Comment by Emelinejy** [comment]
Il est indiqué dans la modale "Les fiches appartenant à sous axe 6.2. test ou a ses sous catégories seront rattachées à la catégorie "Fiches actions non classées".
Or, les fiches actions sont classées dans une catégorie "Sans catégorie" => est-il possible soit de revoir la redirection des fiches actions, soit de changer le texte ?

**Comment by derfurth** [comment]
Bien vu ! J'ai changé la catégorie Sans catégorie -> Fiches actions non classées, comme on ne parle plus de catégorie mais d'axes.
