### ISSUE TITLE
T - Indicateurs : Supprimer la double validation de l'enregistrement des données (deux boîtes vertes)

### ISSUE THREAD

**Issue by Nickvalley** [betagouv/territoires-en-transitions#885]
![image](https://user-images.githubusercontent.com/67585509/140917830-9817e4d9-69b5-41cb-94ea-82dc1e373d6c.png)

**Comment by Emelinejy** [comment]
OK plus de double validation
Mais des validations quand il n'y a pas eu de modification ! 
Cf #978
