### ISSUE TITLE
EPIC - Je peux préparer et faire ma demande d'étoile

### ISSUE THREAD

**Issue by penelopel** [betagouv/territoires-en-transitions#889]
[Description](https://www.notion.so/territoires-en-transitions/EPIC-Je-peux-pr-parer-et-faire-ma-demande-de-labellisation-audit-889-372a03d9642549c487e1cd8b9bc1c916)

**Comment by penelopel** [comment]
Il existait dans la version précédente de l'outil une checklist manuelle donc le code peut resservir de base. 
<img width="919" alt="image" src="https://user-images.githubusercontent.com/5320547/153034427-9c7cc6b0-2594-4b86-b863-8354ac315838.png">
<img width="933" alt="image" src="https://user-images.githubusercontent.com/5320547/153034460-666290ad-43e8-4892-9394-6a361ae927f3.png">


TEXTE : 

Demande d'audit
ÉCONOMIE CIRCULAIRE
Pour pouvoir faire une demande d'audit, vous devez :
Renseigner 100% du référentiel d'évaluation
Fournir les preuves attendues pour justifier les scores : Se référer à la rubrique "preuve" des différentes tâches
Avoir un score minimal sur certaines sous-actions
100% à la sous-action 1.1.1
Au moins 20% aux sous-actions 1.1.2 et 1.1.3
100% à la sous-action 3.2.0 (si le montant annuel d'achats de la collectivité est supérieur à 100 millions d'€)
100% aux sous-actions 2.1.0, 2.2.0, 2.3.0 et 4.1.0 (c'est-à-dire respecter la règlementation si l'EPCI est concernée dans le cadre des compétences exercées)
Faire acte de candidature en fournissant :
Le courrier d'acte de candidature (motivation et palier visé, précision des compétences, engagement à améliorer de façon continue sa politique ECi, identité et coordonnées du référent technique)
Le règlement du label signé
Les derniers statuts approuvés par l’autorité préfectorale ou arrêté préfectoral portant création de l’EPCI
Éventuellement la délibération d'engagement dans le processus de labellisation
Une fois les conditions remplies, merci de signaler votre intention de demande d'audit au Bureau d'Appui par mail à dteci@ademe.fr qui vous informera de la procédure à suivre.

**Comment by cami-na** [comment]
### US Préparation demande d’audit

En tant que personne référente d’une collectivité, je veux être informée des pré-requis pour l’obtention de la labellisation pour chacune des étoiles afin de préparer ma demande d’audit  

_Pour l’instant : uniquement pour la première étoile_

**Infos métier** 

Liste des pré-requis pour la labellisation : https://hackmd.io/0hBYBMHjRsmo-vJAy8W9hQ 

**Critères d’acceptation** 

**Sur le tableau de bord, tant que la collectivité n’a aucune labellisation** 
- Liste des pré-requis (version synthétique)
- Un bouton « Préparer la demande d’audit » qui ouvre dans le même onglet la page « Parcours de labellisation - Référentiel XX » de la rubrique « Audit et labellisation » (emplacement provisoire en attendant restructuration)
- Un bouton « Demander un audit » inactif tant que les cases n’ont pas été cochées dans la page Parcours de labellisation (manuel pour l’instant, sans automatisation ?)

————

**Sur la page « Parcours de labellisation - Référentiel XX »**

Un premier bloc qui reste fixe en haut au scroll
- Titre 2 « Objectif : première étoile » 
- Un bouton « Demander un audit » inactif tant que les cases n’ont pas été cochées dans la page Parcours de labellisation (manuel pour l’instant, sans automatisation ?)

**Un deuxième bloc avec la liste des pré-requis (à détailler)**
- Titre 2 « Préparer la demande d’audit »
- Liste avec des cases à cocher 
    - 1. Lien « Mettre à jour le référentiel » : ouverture de la page Référentiel XX dans un même onglet
    - 2. Lien des sous-actions : ouverture de la page (ancre ?) de la sous-action concernée dans un même onglet / Personnalisation du tableau selon le type de collectivité 
    - 3. Possibilité de téléverser directement les documents (système identique que pour l’ajout des preuves) - ajout à la bibli de documents de la collectivité ?

————

**Modale Demander un audit**

Au clic sur le bouton « Demander un audit » (depuis le tableau de bord ou la page Parcours de labellisation)

Affichage d’une modale
- Titre « Demander un audit »
- Contenu à préciser (explications sur le fait que le référentiel sera figé le temps de l’audit, le délai prévisionnel, etc. ??)
- Un bouton « Envoyer ma demande d’audit »

Après avoir cliqué sur le bouton « Envoyer ma demande d’audit » un message de succès est affiché (à rédiger)

**Comment by Emelinejy** [comment]
3ème option sur bouton "demander l'audit" (envoi mail automatique ou msg envoyer un mail) : notification dans Retool ?
Revoir message sur TdB : "demande d'audit envoyé"

**Comment by Emelinejy** [comment]
Mise en production le 12-05-2022
