### ISSUE TITLE
Besoin Retool pour le suivi d'usage des utilisateurs

### ISSUE THREAD

**Issue by Nickvalley** [betagouv/territoires-en-transitions#892]
- [ ] Connaître les gens avec compte et sans rattachement de collectivité
- [ ] Voir les utilisateurs par date de création de compte  (avec ou sans rattachement de collectivité)
- [ ] Voir les utilisateurs par date de dernière connexion (avec ou sans rattachement de collectivité)

**Comment by Emelinejy** [comment]
Réalisée dans le cadre des fonctions Retool suite mise en place nouvelle version février 2021
