### ISSUE TITLE
Problème message d'erreur création de compte 

### ISSUE THREAD

**Issue by Nickvalley** [betagouv/territoires-en-transitions#963]

**Comment by Emelinejy** [comment]
Tentative de création de compte :
- Page "Créer un compte" : renseigner les éléments demandés puis cliquer sur "Envoyer" ne génère aucune action...
- En recommençant la manipulation, un message d'erreur s'affiche 
![image](https://user-images.githubusercontent.com/92379675/142597975-52721bdc-9d9d-484e-86af-193c7822f323.png)

- Page "Se connecter" : en renseignant la même adresse mail (non validée pour "créer un compte"), nouveau message d'erreur
![image](https://user-images.githubusercontent.com/92379675/142598693-4b0b2b97-9674-459c-b360-43b7db885163.png)
- En recommençant et indiquant uniquement l'adresse mail et cliquant sur "Mot de passe oublié  ?" puis suivant la procédure (réception mail, création mot de passe), il est alors possible de se connecter.
