### ISSUE TITLE
Les check-boxes ne restent pas renseignées (après avoir refermé la modale pour vérifier - en parcourant le référentiel - que ces conditions sont bien validées)

### ISSUE THREAD

**Issue by bertrandlalo** [betagouv/territoires-en-transitions#967]
Les check-boxes ne restent pas renseignées (après avoir refermé la modale pour vérifier - en parcourant le référentiel - que ces conditions sont bien validées)

_Originally posted by @Emelinejy in https://github.com/betagouv/territoires-en-transitions/issues/807#issuecomment-967140434_

**Comment by penelopel** [comment]
Cela marche avec certaines boxes mais pas toutes ! Il y en a qui s'en vont.

**Comment by Emelinejy** [comment]
A chaque ouverture de la modale, si plusieurs boxes sont renseignées, seule la dernière box remplie est conservée (idem pour le "décochage") tout en conservant l'état des autres check-boxes (Si je coche 1 et 2 puis je ferme. Je rouvre, seule la boxe 2 est cochée. Je coche 3 et 1, je ferme. Je rouvre et 1 et 2 sont cochées).
